### ISSUE TITLE
High cpu usage when holding key in `:open`

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#454] opened 2018-04-28 22:10 UTC
Worse when you have a big profile with lots of history. Probably an easy fix: look at less history (approx line 500 in completions.ts).

**Comment by maxigaz** [comment] 2018-05-03 11:04
During our recent chat on Matrix, I tried changing the value of `maxresults` in [completions.ts](https://github.com/cmcaine/tridactyl/blob/master/src/completions.ts#L503) from 500 to 50 and running the newly compiled build with that change. Here are my observations:

Although there's still some lag while typing, it's noticably more responsive than using the stable version with the default value.

During my test, I don't think the suggestions that appear while typing are worse than before (although some of them *are* different, especially the ones towards the bottom of the list).

Using Manjaro Linux x86-64 with Firefox 59.0.2.

**Comment by bovine3dom** [comment] 2018-05-03 16:49
You mentioned that Vimium was much more performant. They keep their own cache: https://github.com/philc/vimium/blob/e3cce413029dd5efa718a48a057d0bcf77d31fb9/background_scripts/completion.coffee#L765b

---

I have reduced the number of history results we ask for to 50 in 4a8870c and made it into a setting, `historyresults`. If people find that completions have suddenly got much less useful, please say so in this issue.

**Comment by gsbabil** [comment] 2018-05-19 05:40
@bovine3dom @maxigaz 

Did some tests on the following two builds:

1. Tridactyl 1.12.0-95-gf31184f
2. Tridactyl 1.12.0-9-g82c4348 (AMO)

I'm still experiencing the sluggishness with the following steps:

- Press `Shift+O`
- Keep `backspace` (keep it pressed until the current URL is completely deleted)

On both [1] and [2] I have roughly the same sluggishness, as compared to what @maxigaz mentioned. To confirm - I do have `historyresults = 50` in `viewconfig` with [2].

_P.S._

If the page is just an image, `Shift+O` does not seem to work. Interestingly, other `nmap`s tend to work. For example I have `,j` set to `urlincrement +1`, and that would work on a tab with just an image.

Thanks.

**Comment by maxigaz** [comment] 2018-05-19 10:03
> Keep `backspace` (keep it pressed until the current URL is completely deleted)

I can still confirm the sluggishness when I do the same with v1.12.0-9-g82c4348 (stable version, AMO).

By the way, I notice it not only when I'm typing/editing a URL, but also in the case of search queries, with or without the keyword "search". The longer the search query or URL, the more sluggish it becomes.

**Comment by bovine3dom** [comment] 2018-05-19 10:27
> By the way, I notice it not only when I'm typing/editing a URL, but also in the case of search queries, with or without the keyword "search". The longer the search query or URL, the more sluggish it becomes.

That's expected - history search just gets slower the more you send to it. I think this will just have to get fixed in #434 or later as we need to make it async.

**Comment by gsbabil** [comment] 2018-05-19 22:13
@bovine3dom 

> Have you tried `set csp clobber`?

I did. Doesn't seem to help. 

To reproduce, you can go to [this image URL][0], and try pressing `:` or `Shift+O`. Basically, it seems that displaying the command-bar currently does not work on non-HTML pages.

_P.S._

Might be unrelated, but I tested [cVim][1] on Chrome, and it seems to be able to display the command-bar with `:` even on image pages. Also the `Shift+O > Backspace` test is really snappy with cVim+Chrome.


[0]: https://i.imgur.com/4S8LLqx.jpg
[1]: https://chrome.google.com/webstore/detail/cvim/ihlenndgcmojhcghmfjfneahoeklbjjh?hl=en

**Comment by cmcaine** [comment] 2018-05-20 16:56
@gsbabil commandline not appearing on imagedocuments is fixed by 45181d0c50024ceb391b80338bc66b640c512235. Thanks for reporting.

**Comment by gsbabil** [comment] 2018-05-20 17:51
@cmcaine 

Thanks!

**Comment by diabolicfutility** [comment] 2018-07-31 20:03
I also have this issue.

If whatever I type returns a lot of history results, even if it's a lot of text, then the typing is always smooth.

If whatever I type doesn't have a lot of history results, then around 7 or 8 characters in, the typing (or trying to do anything) becomes mega slow.

**Closed** 2018-10-28 10:56 UTC
Labels: blocked, bug
