### ISSUE TITLE
Redirect loop for a website

### ISSUE THREAD

**Issue by FrankEular** [tridactyl/tridactyl#1015] opened 2018-09-19 23:44 UTC
If I enable Tridactyl and visit https://www.jegeremacartenavigo.fr/connexion/connexion, then there is an obvious redirect loop. Especially, if I also enable both Tridactyl and Ublock Origin, then this loop becomes infinite. However, if I only enable Ublock Origin, there is no redirect loop.

*   Tridactyl version (`:version`):
1.14.0-1.14.0

*   Firefox version (Top right menu > Help > About Firefox):
60.2.0esr

*   URL of the website the bug happens on:
https://www.jegeremacartenavigo.fr/connexion/connexion

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/FrankEular/d96ef6fe53b190ed34efe43fb087af97

For the settings mentioned in https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md, only
:set noiframeon $URL_OF_THE_WEBSITE
is effective.

**Comment by bovine3dom** [comment] 2018-09-20 10:07
We are hoping that #639 will fix most of these sites which currently need noiframeon. Closing as duplicate of that.

**Closed by bovine3dom** 2018-09-20 10:07 UTC
