### ISSUE TITLE
commandline iframe breaks site

### ISSUE THREAD

**Issue by manulari** [tridactyl/tridactyl#1516] opened 2019-05-03 11:40 UTC
Tridactyl breaks [https://posteo.de/webmail/](https://posteo.de/webmail/).

This is a website offering a paid email service, but for testing this I think an account can be created and then deleted within 14 days without making payments or adding payment details.
To my knowledge they use roundcube webmail, so this may also be testable on some other roundcube instance.

The symptom is that it looks as if the inbox was completely empty and other navigation on the site also doesn't work. (I.e. no composing emails etc.)

Setting   
:seturl https://posteo.de/webmail/ noiframe true  
makes it work.

I'm filing this bug as per [the troubleshooting doc](https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md) -- I didn't find a github issue yet for the noiframe case.

This is on a recently installed tridactyl 1.14.9 with next to no customization on Firefox 66.0.3 installed through Ubuntu repositories. Tridactyl native executable is installed.
Let me know if you need further information.

**Comment by dylanfprice** [comment] 2019-05-14 21:41
Another instance. Would be great to link this issue from the [troubleshooting doc](https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md#user-content-settings-that-can-fix-websites).

Tridactyl version: 1.14.10-226-g8d31535
Firefox version: Mozilla Firefox 67.0
Operating system: linux

Seeing this when trying to load https://portal.insperity.com. Looks like some kind of infinite redirect loop. This happens before logging in so you should be able to repro just by going to the url.

`:seturl insperity.com noiframe true` fixes.

Let me know how I can help!

**Comment by bovine3dom** [comment] 2019-05-29 21:54
Closing as duplicate of #355 :)

**Closed by bovine3dom** 2019-05-29 21:54 UTC
Labels: P4, bug, site specific
