### ISSUE TITLE
Hint mode @ web.whatsapp.com does not work properly

### ISSUE THREAD

**Issue by cadr10** [tridactyl/tridactyl#1567] opened 2019-05-22 07:09 UTC
Tridactyl version: 1.14.10-270-g938b71d
Firefox version: Mozilla Firefox 67.0
Operating system: linux

***   Brief description of the problem:**
Hint mode does not open conversations on Whatsapp Web. It clicks on it, 'zooms white' and conversation doesn't open.
In other extensions (if the info is useful for developers): 
Vim Vixen: shows hints in conversations but it seems the website doesn't even registrates the click.
Vimium: same as Vixen.

***   Steps to reproduce:**

Open web.whatsapp.com

Press ´F´ for hint mode.

Press a hint that's above chat with somebody.

***   URL of the website the bug happens on:**
https://web.whatsapp.com/

***	Considerable notes (maybe?):**

Hint works on other parts of the web app. In the settings menu which js event is onMouseDown. Tridactyl makes the zoom effect (but opens) on these while Vixen and Vimium open them normally.

While in chat tabs js events are: OnBlur; OnDragEnter; OnDragLeave; OnDrop; OnFocus; onKeyDown and onKeyPress.

The profile page can be edited clicking on the profile pic which event is click and onClick and doesn't seem to work either.

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/cadr10/787783f8e6bbb11847a5fa82ff3bf82c

**Comment by Rummskartoffel** [comment] 2020-12-08 15:55
I've taken a look at this and noticed there's a big div (`.app-wrapper-web`) containing the whole web app, which has capturing `mousedown` and `click` handlers. I think they might be responsible for actually handling pretty much every user interaction instead of the individual elements' handlers, but I haven't been able to confirm that yet, because the compiled JS code of a React.js app such as this isn't exactly readable. I've tried simulating clicks on conversations using 
```js
document.querySelector('.app-wrapper-web').dispatchEvent(
    new MouseEvent("click", {
        screenX: div.getBoundingClientRect().x,
        screenY: div.getBoundingClientRect().y
    })
)
```
where `div` is one of the divs comprising a conversation in the list of conversations on the left-hand side (which is where you'd click to go to that conversation), but I haven't had any success so far. I've tried the same with event type `mousedown`, also to no effect.

**Comment by bovine3dom** [comment] 2020-12-08 18:52
:/

In 238ba801 I added a couple to make it easier to craft an `xdotool` command that just moves the mouse and clicks on the elements.

`hint -F e => { const pos = tri.dom.getAbsolutePosition(e); tri.excmds.exclaim_quiet("xdotool mousemove --sync " + pos.x + " " + pos.y + "; xdotool click")}`

but I can't get it to actually click - the mouse moves just fine, but it doesn't seem to click. :(

If we can get it to work I'll probably add it as a default bind like we have for mpv on `;v`.

**Comment by Rummskartoffel** [comment] 2020-12-08 21:01
That would only be a partial solution, though, because not everyone uses the native messenger, has xdotool, or, in the case of Windows, *can* have xdotool. But I don't have any better ideas, either.
If you do add this, consider saving the previous mouse position and moving it back again, to prevent a then stray mouse pointer from triggering unwanted hover events or tooltips.

**Comment by bovine3dom** [comment] 2020-12-08 21:15
Windows has autohotkey : )

I wasn't suggesting that we give up, just that `xdotool` would be a nice plan B that would work on any site that has real elements.

Storing the position and then moving it back could be a bit involved as I think we'd need to use xdotool for that too. I'll try to see if I can get it to work at all before I worry about that.

**Comment by Rummskartoffel** [comment] 2020-12-08 22:54
I just managed to successfully "click" on a conversation after all, by using our own `dom.mouseEvent` manually through `:js`. The trick wasn't, as I'd thought, to "click" on the right position in the context of the big ancestor div, but to "click" on a child of the conversation div `:hint` normally finds. The structure is something like this:
```html
<div tabindex="0"><!-- This is what hint finds (because of tabindex). -->
    <div class="_3Pwfx"><!-- This is what we need to "click". -->
    </div>
</div>
```
So now all we need to do is to make `:hint` "click" on the first descendant of the div it detects instead of the div itself. We just have to figure out how to only do that for conversations and not for any other clickable things in the web app, and we should be prepared for having to fix this again if WhatsApp ever changes the structure of the web app and breaks our fix.

Interestingly, the strange "zooming" thing seems not to be caused by "clicking" on anything, but it happens whenever `:hint` exits. You can try it out by running `:hint -F` with no callback and either selecting something or cancelling.

**Comment by bovine3dom** [comment] 2020-12-08 23:33
`hint -c [tabindex] > div` perhaps?

**Comment by Rummskartoffel** [comment] 2020-12-09 15:13
I've tried it and arrived at `[tabindex]:not(.two) > div`, to prevent another all-encompassing div from creating one of those bright green hinting overlays which makes it so you can't see anything. Both conversations and, by chance, the search box are usable with this.
I've noticed one further thing our default hints can't catch, the box asking the user to enable desktop notifications, which we can select with `[data-testid="chevron-right-text"]`, but that fix feels rather brittle.
Finally, the weird zooming doesn't happen with either of these workaround hint selectors, for some reason.

**Closed** 2020-12-09 16:46 UTC
Labels: P4, bug, site specific
