### ISSUE TITLE
`about:preferences` never remember history breaks `:find`

### ISSUE THREAD

**Issue by 1seven** [tridactyl/tridactyl#2516] opened 2020-06-21 11:44 UTC
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 68.9.0
Operating system: linux

When trying to search using `:find mykeyword` on _any_ website I receive the following error from Tridactyl:
`# controller in excmd: TypeError: proxy set handler returned false for property '"lastSearchQuery"'`

Does anybody else observe this behaviour?

I posted my config in the following gist: https://gist.github.com/1seven/0e882b248f1433841f0e4dd82cdacd82

Regards,
1seven.

**Comment by glacambre** [comment] 2020-06-21 11:48
It looks like you're using an old beta, could you try upgrading to a 
more recent Tridactyl version?

**Comment by 1seven** [comment] 2020-06-21 11:49
Oh, my bad, I will do an update then. :)

**Comment by 1seven** [comment] 2020-06-21 12:01
Ok, so apparently 1.19.1pre3928-53d0d18 is the latest stable version available on the Mozilla AddOns website. I tried  using the latest beta release 1.19.1pre4077-bbf656c, but the problem persists. Any ideas?

**Comment by glacambre** [comment] 2020-06-21 12:08
Oh, sorry, I forgot that stable version numbers looked like beta version numbers. I'm not sure about what could be going on here. Do you have a stack trace if you open firefox's console? (`<C-S-I>`)

**Comment by 1seven** [comment] 2020-06-21 12:14
This is, what I get (using the latest Beta now):

`TypeError: proxy set handler returned false for property '"last_ex_str"' 2 content.js:45153:21
controller in excmd:  <unavailable> content.js:47762:33
  log moz-extension://760207c9-1caa-4166-8d1c-bf8f1fc33fdd/content.js:47762
  acceptExCmd moz-extension://760207c9-1caa-4166-8d1c-bf8f1fc33fdd/content.js:45161
TypeError: proxy set handler returned false for property '"last_ex_str"' background.js:51074:21
TypeError: proxy set handler returned false for property '"prevInputs"' content.js:45702:73
TypeError: proxy set handler returned false for property '"prevInputs"' 2 content.js:45702:73`

**Comment by bovine3dom** [comment] 2020-06-21 12:24
My go-to for weird problems is this: Do you have "privacy.resistFingerprinting" set to true in about:config? That breaks lots of things.

Could you see if it works in a fresh Firefox profile?

**Comment by 1seven** [comment] 2020-06-21 12:34
"privacy.resistFingerprinting" is false, but it works with a fresh profile. Weird. I close this issue now.

Thanks for the support!

**Comment by bovine3dom** [comment] 2020-06-21 12:41
The fact that it works in a new profile but not with the Beta version in your current profile is odd (Tridactyl Beta would have a fresh configuration). Perhaps it could be a conflict with another extension? Have you changed much in about:config?

I understand if you don't want to bother debugging it further and are happy that it works in a fresh profile :)

**Comment by 1seven** [comment] 2020-06-21 12:55
I'm happy to assist,

**Comment by 1seven** [comment] 2020-06-21 12:57
I'm happy to assist in debugging this, if possible. I've just reinstalled all my plugins (NoScript, AdBlock for Firefox, Kiwix, MerriamWebster) and so far it still seems to work. I had some special keybindings for the `:find` command, I just have to lookup, where I configured them. Maybe it's related to that.

**Comment by 1seven** [comment] 2020-06-21 13:08
I think I didn't change anything in my about:config in my old profile. Also applying the keybindings doesn't break it in the new profile:
`:bind / fillcmdline find`
`:bind n findnext 1`
`:bind N findnext -1`

**Comment by bovine3dom** [comment] 2020-06-21 21:15
I suppose the next thing to do is to examine the browser storage to see if there's anything weird in there that's breaking it.

In your old profile, please ensure that on `about:addons` only one version of Tridactyl is enabled, then:

1. Visit `about:debugging`, click "This Firefox", click "Inspect" next to Tridactyl, click the console tab.
2. Run `browser.storage.local.get("state").then(console.log)`, check that for any sensitive information - probably just leave out the `cmdHistory` part.
3. Copy that object and paste it somewhere, e.g. `gist.github.com` and give us the link.


You could also wipe the data and see if that fixes it. First, make a backup of your Firefox profile - you can find the location of it on `about:support`. Then, follow step 1 above again to get to the console.

2. Run `browser.storage.local.clear()`
3. Wait a few seconds, restart Firefox
4. See if find mode is fixed

**Comment by 1seven** [comment] 2020-06-22 21:48
It was quite a busy day, so I wasn't able to follow the steps you suggested above yet, but I have some good news anyway.
When adjusting some preferences I realised that setting the history keeping behaviour to "Never remember history" reproduces the error. Setting it back to "Remember history" fixes it.
Considering this, I would say this is indeed a bug - or is this behaviour intended (or at least expected)?

Knowing this, would you still be interested in the debugging information?

**Comment by bovine3dom** [comment] 2020-06-22 22:11
Those are both really useful. I suspect don't-remember-history isn't a bug we can fix but it might be one for Mozilla to look at - we keep track of those in #760 - but I'll look into it some more before closing this issue.

I've made a separate issue for private mode which is 100% my fault.

**Comment by 1seven** [comment] 2020-06-23 08:20
I think they are both essentially the same bug as "Don't remember history" makes Firefox operate in private-mode only, so I suggest closing this issue.

**Comment by bovine3dom** [comment] 2020-06-23 08:22
Are you sure? We use https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/inIncognitoContext to check. I'd like to double check that that's really the case.

**Comment by 1seven** [comment] 2020-06-23 09:02
I'm not entirely sure, but here (https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history) they write 
> Alternatively, you can select Never remember history from the drop-down menu, which is equivalent to always being in Private Browsing mode.

**Comment by bovine3dom** [comment] 2020-06-23 11:12
Ah, yeah, you're right. Closing as duplicate of #2520. Thanks for the help debugging this!

**Closed by bovine3dom** 2020-06-23 11:12 UTC
