### ISSUE TITLE
Very slow command line

### ISSUE THREAD

**Issue by nvkrishna77** [tridactyl/tridactyl#1022] opened 2018-09-22 10:53 UTC
# Reporting a bug / getting help

Please use the following steps:

1. Press :open 

2. Start typing a long sentence (to be searched in google). Something like:

I want to use tridactyl

3. You will see that while the first few characters show up right away. The latter ones show up very slowly. As if you are typing on a remote shell.

*   Tridactyl version (`:version`): 1.14.0-1.14.0

*   Firefox version (Top right menu > Help > About Firefox): 62

* OS: Mac OS X.

**Comment by bovine3dom** [comment] 2018-09-22 11:00
Almost certainly a duplicate issue. I'm on my phone right now so I can't look them up.

Usually the cause is a very large profile (and our bad code). If you're not too attached to it you can make a new one to make it quicker.

**Comment by glacambre** [comment] 2018-09-24 20:50
I think this is the issue in question: https://github.com/tridactyl/tridactyl/issues/454

**Comment by bovine3dom** [comment] 2018-09-24 21:51
Closed in favour of #454. Thanks, glacambre.

**Closed by bovine3dom** 2018-09-24 21:51 UTC
