### ISSUE TITLE
Ignore keybindings functionality

### ISSUE THREAD

**Issue by suic86** [tridactyl/tridactyl#57] opened 2017-11-14 23:24 UTC
First of all a big thank you for creating this extension. I've been a vimperator user for a long time.

The vimperator feature I'm missing the most in tridactyl is the ability to temporarily suppress vim key bindings with `Insert` or `Shift-Esc` keybinding. This is very usefull on sites with own shortcuts (e.g. gmail, github, JIRA). The solution provided by Vimium for Chrome isn't an option for me.

Thanks,

suic

**Comment by bovine3dom** [comment] 2017-11-15 00:08
I've added a basic implementation in 49bbcb7.

Press I to enter it and Shift-Esc to exit. There's no feedback at the moment and we don't yet support special keys in normal mode, hence it not just being on Insert.

It should appear in the beta branch soon.

I'll leave this issue open because I'm not happy with the lack of feedback, the exact bindings, and want to add support for a blacklist per site.

**Comment by cmcaine** [comment] 2017-11-20 03:38
Ignore mode now works a bit better. Still no notification, autocmds, etc.

**Comment by terminalmage** [comment] 2017-11-23 23:59
The killer feature that Vimperator and Pentadactyl both had was the ability to pass through certain keys in insert mode. Vimperator's version of this was called `ignorekeys`, while Pentadactyl's was `passkeys`. For example:

```
set passkeys=.+:<space><up><down><left><right><pgup><pgdown>,mail.google.com:jkoxe#giuastln*,music.google.com:+-,.+.newsblur.com:jkorA,myteamname.slack.com:HJKL
```

The basic format would be `<url_regex>:<keys>`, allowing for individual sites to have their own passthrough.

Pentadactyl's implementation in particular was fantastic in that it also implemented a "passthrough" feature (by default mapped to `C-v`) which mimicked Vim's passthrough feature, allowing the next keystroke to be ignored by Pentadactyl and passed through to the browser.

The brilliant thing about how it was implemented though was that it would reverse the passthrough behavior if that key was configured in `passkeys`. So, for example, say you had passed through `j` and `k` on a given website, because it had its own keyboard shortcuts that you wanted to use. Using `C-v` you could (for the next single keystroke) make Pentadactyl use `j` for scrolling. In addition to `C-v`, `C-z` could be used to ignore all keys until `C-z` was pressed again (similar to how ignore mode presently works in tridactyl with `I` and `Shift + Esc`).

As a bit of feedback, I find `Shift + Esc` a bit cumbersome, but from what I grok of the code this seems to be hard-coded. It would be nice if this were eventually configurable so that I could replicate the `C-z` behavior for both entering and leaving ignore mode.

All in all, I'm loving this project, it's saved Firefox for me. Thanks for all of your work!

**Comment by terminalmage** [comment] 2017-11-24 00:29
One other thing about the current implementation of ignore mode, I noticed that it gets reset when the tab switches. Was that by design? I'm honestly not sure what the optimal behavior would be:

1. Keep ignore mode in effect globally until `Shift + Esc` pressed
2. Remember mode for each individual tab
3. Keep behavior as currently implemeted
4. ???

**Comment by yegle** [comment] 2017-11-26 17:52
Link to pentadactyl's doc on this topic: http://5digits.org/help/pentadactyl/browsing.xhtml

Would really want to see ctrl+z support

**Comment by stevenbell** [comment] 2017-11-27 17:10
The basic use case for me is using Gmail (where I want to use the Gmail keyboard shortcuts) and Google docs (where it's easy to accidentally do all kinds of things when you start typing a sentence), along with a bunch of other tabs.
A per-site blacklist is what I used with Vimperator, and would probably be the best eventual setup for me.  But I think @terminalmage's suggestion 2 is the "right" behavior, at least for my use case.  If I went into ignore mode, it's probably because I'm using some page shortcut keys that I want to keep working even when I come back to the tab.

**Comment by cmcaine** [comment] 2017-12-11 14:26
Thanks for describing how pentadactyl does it - I think we want to replicate that.

Mode is currently set globally, but we'd like to change that to be per-tab. One difficulty with implementing that is that it's not obvious what tabId a content script lives in.

**Comment by cprn** [comment] 2018-05-11 08:54
It doesn't seem to work any more. I press `shift+i` on this website (when no input field is active) and pressing `t` afterwards initiates `:tabopen` dialogue.

I know it worked because I used it before on website where `t` and `n` a very useful shortcuts and now only `n` works.

**Comment by bovine3dom** [comment] 2018-05-11 08:57
@cprn see #478 :)

**Comment by willsALMANJ** [comment] 2018-05-11 10:28
I didn't realize how it important it was, but the mode indicator makes this a lot more usable.

Which features is this issue being left open for now? Features referenced here that I would to have are:

1. Per site passkeys (passthrough specified keys to sites matching a regex while in normal mode)
2. Ability to configure the keybinding for exiting ignore mode

**Comment by bovine3dom** [comment] 2018-05-11 10:40
It's open for `passkeys`, which is blocked by #434 as we need per-tab state.

> Ability to configure the keybinding for exiting ignore mode

is totally covered by #304 and should come as part of #434.

**Comment by terminalmage** [comment] 2018-05-16 05:29
The indicator actually partially obscures the input box for an active Hangouts chat within Gmail (which appears in the lower-right of the Gmail window). Since I use this to chat with my wife, it is a little annoying, but nothing I can't deal with. It only covers up the button within the input box that you click when you want to upload an image, which I only do occasionally.

![indicator](https://user-images.githubusercontent.com/328598/40098227-07b9a5fc-58a0-11e8-87ac-e20043bc979d.png)

**Comment by bovine3dom** [comment] 2018-05-16 09:27
Unfortunately we were always going to cover something up. I guess we could do `display: none` on hover?

**Comment by terminalmage** [comment] 2018-05-16 13:26
Yeah, that could work.

**Comment by DennisSchwartz** [comment] 2018-05-21 21:06
Any info for Mac users? I can't seem to make it work. The `Insert` key is not really natively available in OSX and none of the key combinations I can find works.

**Comment by bovine3dom** [comment] 2018-05-21 21:10
@DennisSchwartz see #505 :)

In general you can bind any sequence of keys to any ex command, see `help bind`.

**Comment by bovine3dom** [comment] 2018-05-21 21:13
We should definitely add that to the documentation though.

**Comment by DennisSchwartz** [comment] 2018-05-22 08:04
Thanks a lot :)

**Comment by GianniGi** [comment] 2018-05-30 12:48
I keep getting a strange behaviour when writing in fields like this. Sometimes a new tab suddenly opens out of nowhere, while I'm writing. I suppose that this arises from tridactyl??? I got this behaviour on gmail and on github, that randomly opened an empty tab while writing the first row of this comment.

I'd really like to disable tridactyl on some websites, like gmail. I hope that this option comes soon.

**Comment by bovine3dom** [comment] 2018-05-30 13:10
@GianniGi `autocmd DocStart mail.google.com mode ignore`, but you'll need to enter ignore mode again every time you change tab.

> Sometimes a new tab suddenly opens out of nowhere, while I'm writing. I suppose that this arises from tridactyl??? I got this behaviour on gmail and on github, that randomly opened an empty tab while writing the first row of this comment.

Please check that Tridactyl is the only vim-like add-on running under about:addons.

Other possibilities:
- if you have a laptop, your palm could be moving the pointer and clicking outside of the text box, sending Tridactyl into normal mode
- it could be a real bug in Tridactyl

**Comment by cprn** [comment] 2018-05-30 13:11
When a text input field is focused triadactyl is in `insert` mode and passes all keys to the browser. Also, I don't know about any triadactyl command that'd just open a new tab. You need to confirm it with Enter, I think. Any chance any of the following happens during typing?

1. modes:
 - you press Escape (that'd switch you back to `normal` mode)
 - then `t` (triadactyl key for new tab)
 - then Enter (to confirm triadactyl command)
2. your browser does that
 - you accidentally press `ctrl` (resting your wrist on it or maybe it's sticky?)
 - then tap `t` (ctrl+t is usually browser's new tab shortcut)
3. you touch your touchpad clicking outside of the box

**Comment by bovine3dom** [comment] 2018-05-30 13:13
If you really need a per site blacklist you could try [Vim Vixen](https://addons.mozilla.org/en-US/firefox/addon/vim-vixen/) instead which seems to be less keen on obscurantism than we are :)

**Comment by GianniGi** [comment] 2018-05-31 16:31
thanks, after disabling tridactyl and doing extensive tests, I've verified that trydactil is innocent. 

Still I think that disabling this addon is absolutely vital. On gmail, for example, I prefer to have the gmail shortcuts enabled. I don't see any use for tridactyl on gmail. When you click F, a forest of links and red labels suddenly appears. It's unusable on gmail!! Please add an option to permanently disable it.

**Comment by bovine3dom** [comment] 2018-06-01 08:59
`blacklistadd mail.google.com/mail` in the latest betas : )

Thanks to @glacambre and @IsaacKhor.

**Comment by GianniGi** [comment] 2018-06-01 17:44
thank you very much, I can't wait to try it :+1:

**Comment by glacambre** [comment] 2018-06-28 15:45
`:blacklistadd` is now available in stable versions, is there anything left to do before closing this issue?

**Comment by bovine3dom** [comment] 2018-06-28 16:08
Yeah, it is really annoying working across two windows with one on a site on the blacklist as you'll enter ignore mode and then stay in it when you focus the other window. We need DocFocus / DocBlur events.

**Comment by willsALMANJ** [comment] 2018-06-28 18:02
@bovine3dom said above (responding to my previous comment) that this issue was being held open for passkeys.

**Comment by bovine3dom** [comment] 2018-07-25 12:16
Now that #304 is half-done, you can roll your own passkeys with

`autocmd DocStart [website] composite set ignoremaps.[key sequence] [ex string]; set [ad infinitum]` and `autocmd DocEnd [website] composite unset ignoremaps.[key sequence]; unset [ad infinitum]`. All caveats that went with `blacklistadd` apply.

Or maybe that's ignorekeys? I can't remember which is which.

Ignore bind isn't hard-coded either, just do

`bind [blah] mode ignore`
`set imaps.[blah] mode normal`.

**Comment by Druidefix** [comment] 2018-10-05 17:18
@bovine3dom: I recently started using tridactyl and so far I'm trying to get my configuration from the past Vimperator days to work. Concerning your last post here, it seems that the feature to allow on specific sites some tridactyl commands seems working? However, the help you wrote does not help me much on getting it to run.

If I understood it correctly, could you give me an example of how to allow only 't', 'gn', 'u', ':', '/' on a specific site, e.g. 'site.com'?

**Comment by glacambre** [comment] 2018-10-05 19:45
@Druidefix I'd recommend using the site in ignore mode, so
```
autocmd DocStart site.com mode ignore
```
Then unbinding every [key bound in ignore mode](https://github.com/tridactyl/tridactyl/blob/86ddc368e10825e7d2534ad1ea7080295e2a0502/src/lib/config.ts#L76-L83), so
```
unbindurl site.com <S-Insert>
unbindurl site.com <CA-Escape>
unbindurl site.com <CA-`>
unbindurl site.com <S-Escape>
unbindurl site.com <C-^>
unbindurl site.com I
```
And then rebinding the keys you want in ignore mode:
```
bindurl site.com t fillcmdline tabopen
bindurl site.com u undo
bindurl site.com : filldmdline_notrail
```
`gn` and `/` are a bit special, you have one `gn*` binding per quickmark so you'll need to bind each of them manually (e.g. `bindurl site.com gna tabopen https://site.net`) and `/` is a firefox binding rather than a Tridactyl one so it'll work everywhere.

Note that `bindurl` is only available in Tridactyl's betas. `:h seturl`, `:h bindurl`, `:h unbindurl` and `:h reseturl` should help you understand how these functions work. Plzase let us know if the doc is not clear enough.

**Comment by bovine3dom** [comment] 2018-10-05 23:03
They'll be remembered forever unless you have `sanitise tridactyllocal tridactylsync` at the top of your .tridactylrc.

**Comment by Druidefix** [comment] 2018-10-07 12:14
@glacambre: I am using version `1.14.0-141-g98fca08` and native is also running (`# Native messenger is correctly installed, version 0.1.9`). I copied your lines and only replaced

    bindurl --mode=ignore site.com : filldmdline_notrail

to

    bindurl --mode=ignore site.com : fillcmdline_notrail

but I must admit it is not working at all. The only thing that indeed works is that the site (I want it for feedly.com, but tested it also with another sie) is in ignore mode. Are there any ways to debug why it is not working?

**Comment by glacambre** [comment] 2018-10-07 12:34
That's because it's actually `bindurl site.com --mode=ingore : fillcmdline_notrail`, I mixed up the order of the arguments when writing my answer, sorry :(
The documentation mentions the right order: `bindurl $pattern [--mode=$mode] $key $command`.

**Comment by Druidefix** [comment] 2018-10-07 12:46
Thank you very much, now it works perfectly!

Would it be possible to add this information with an example to the default Readme? Or another reasonable place?

**Comment by glacambre** [comment] 2018-10-25 07:09
Things asked for in this issue:
- [Ignore mode](https://github.com/5digits/dactyl/blob/0043f8dbb629a8e8836241c4c53411afc8cba8de/common/locale/en-US/map.xml#L474)
- [{ignore,pass}keys](https://github.com/5digits/dactyl/blob/0043f8dbb629a8e8836241c4c53411afc8cba8de/common/locale/en-US/map.xml#L474)
- [Ignore mode shouldn't be reset on tab change](https://github.com/tridactyl/tridactyl/issues/57#issuecomment-346712609)
- [Pentadactyl's](https://github.com/tridactyl/tridactyl/issues/57#issuecomment-347026146) [`<C-z>`](https://github.com/5digits/dactyl/blob/0043f8dbb629a8e8836241c4c53411afc8cba8de/common/locale/en-US/map.xml#L474)
- [Per-site passkeys](https://github.com/tridactyl/tridactyl/issues/57#issuecomment-388325872)
- [Ability to configure ignore-mode bindings](https://github.com/tridactyl/tridactyl/issues/57#issuecomment-388325872)
All of these have been implemented in some way or another.

What's left:
- Update the doc (done in https://github.com/tridactyl/tridactyl/pull/1108)
- Implement DocFocus/DocBlur events (issue for this: https://github.com/tridactyl/tridactyl/issues/1109)

**Comment by bovine3dom** [comment] 2018-10-25 10:40
I think Ctrl-Z and passkeys could do with more explicit support.

**Comment by bovine3dom** [comment] 2018-10-26 09:20
I'm not sure re. passkeys - I want to avoid the situation we have with quickmarks and blacklistadd where the operation is hard to undo or observe. So it potentially needs to be its own special setting.

I thought ctrl-z just put you in ignore mode or normal mode for a single keypress/keyseq.

**Comment by glacambre** [comment] 2018-10-26 18:42
>I thought ctrl-z  just put you in ignore mode or normal mode for a single keypress

No, this is [`<C-v>`](https://github.com/5digits/dactyl/blob/0043f8dbb629a8e8836241c4c53411afc8cba8de/common/locale/en-US/map.xml#L464). I think they took inspiration from the shell, `<C-z>` suspends and `<C-v>` inserts the character literally.

> I want to avoid the situation we have with quickmarks and blacklistadd where the operation is hard to undo or observe

We could have the following corresponding excmds:
```ts
function unpasskeys(domain: string, ...keys: string[]) {
    let filter = k => keys.includes(k)
    if (keys.length == 0)
        filter = _ => true
    Object.keys(config.getUrl(domain, "nmaps")).filter(filter).forEach(key => reseturl(domain, key))
}
function showpasskeys(domain: string) {
    let nmaps = config.getUrl(domain, "nmaps")
    fillcmdline(`passkeys for ${domain}: ${Object.keys(nmaps).filter(k => nmaps[k] === "").join(" ")}`)
}
```

We can probably also put the same thing in place for quickmarks/blacklistadd, although I think it'd be better to have a proper quickmarks implementation that would let users rebind their quickmarks shortcuts.

**Comment by laoyang945** [comment] 2019-05-24 02:32
Hi any suggestions of how to bind/unbind a key sequence? like gi in gmail, gh in twitter?

**Comment by glacambre** [comment] 2019-05-24 05:10
@laoyang945: Does `:unbindurl gmail.com --mode=normal gi` do what you want?

**Comment by laoyang945** [comment] 2019-06-17 14:03
@glacambre no, once you unbindurl gi from mail.google.com, nothing happens after pressing gi

**Comment by bovine3dom** [comment] 2020-05-10 07:42
`<C-v>` bind to send a single key combination to the page added in #2364 - also adds `<C-o>` ignore mode bind to perform a single normal mode action.

I think that's everything on this issue covered now :)

**Closed by bovine3dom** 2020-05-10 07:42 UTC
Labels: enhancement
