### ISSUE TITLE
p / P broken?

### ISSUE THREAD

**Issue by Noexpert** [tridactyl/tridactyl#3115] opened 2020-12-16 18:38 UTC
Tridactyl version: 1.20.3
Firefox version: Mozilla Firefox 84.0
Operating system: win

Is `p` / `P` somehow broken in the last version?
On three different Firefox installations, it no longer seems to work.
I haven't made any changes to any settings or config.

I'm still able to copy with `;p`.

Sorry, if this is not an issue.

Thanks

**Comment by bovine3dom** [comment] 2020-12-16 19:11
I haven't checked FF84 but it was working fine in FF83 a few days ago on Linux.

Is `:viewconfig --user` really empty except for a couple of obviously machine generated things?

**Comment by Noexpert** [comment] 2020-12-16 19:25
Hi, no it's not empty.

In fact, I can see:
```
p	"clipboard open"
P	"clipboard tabopen"
```

but they don't seem to do anything.
Other shortcuts work.

**Comment by bovine3dom** [comment] 2020-12-16 19:32
I'd try `reset p` and `reset P`

**Comment by Noexpert** [comment] 2020-12-17 14:44
Hi,

tried that with a couple of different installations, but the issue persists.

Thanks

**Comment by bovine3dom** [comment] 2020-12-18 10:19
I can't reproduce this - it works fine for me on FF84 on Linux.

Could you open a Tridactyl new tab, open the web console (right click anything, click "inspect element", then click console). Then, copy any text, and in the Tridactyl command line, run `:js window.navigator.clipboard.readText().then(console.log)` and tell us if you get any errors + if the copied text appears in the console.

**Comment by duguyipiao** [comment] 2020-12-18 11:39
> I can't reproduce this - it works fine for me on FF84 on Linux.
> 
> Could you open a Tridactyl new tab, open the web console (right click anything, click "inspect element", then click console). Then, copy any text, and in the Tridactyl command line, run `:js window.navigator.clipboard.readText().then(console.log)` and tell us if you get any errors + if the copied text appears in the console.

I tried, but didn't get any error and the copied text appears in the console.
Still p/P doesn't work.

Reproduced in firefox 84 on linux with a fresh firefox profile.

**Comment by bovine3dom** [comment] 2020-12-18 12:03
Weird. Thanks for trying it out.

How about:

1. Go to about: debugging, click this Firefox, click Inspect next to Tridactyl, click Console
2. Click the bin icon in the top left to clear it (it will be full of errors)
3. Run `:jsb window.navigator.clipboard.readText().then(console.log)` in the Tridactyl command line on any page, see if you get any errors
4. Try p / P too

**Comment by bovine3dom** [comment] 2020-12-18 12:09
Oh, which Tridactyl version are you using? Could you try Stable (from AMO) & Beta (from readme.md here)?

We changed how it works in Beta recently, so we might have fixed a bug that didn't exist at the time we made the change : )

**Comment by duguyipiao** [comment] 2020-12-18 12:20
You are right. The beta version works!
For the AMO version, still no errors appear in the console, but p/P doesn't work.

Do you have any idea what caused this problem? Because I have a similar problem for Surfingkeys.

**Comment by bovine3dom** [comment] 2020-12-18 12:51
ee295a212fa03066358668ae0c01e9beea1d8cdc perhaps FF84 disabled the old API? We used to use `document.execCommand`.

**Comment by bovine3dom** [comment] 2020-12-18 12:52
Closing as fixed in ee295a212fa03066358668ae0c01e9beea1d8cdc

Well done to @Rummskartoffel for fixing bugs before they existed.

I'll do a new release today if I can find the time.

**Closed by bovine3dom** 2020-12-18 12:52 UTC

**Comment by bovine3dom** [comment] 2020-12-21 12:46
I've just released 1.20.4 which contains this bug fix : )
