### ISSUE TITLE
Config file tridactylrc only partially loaded

### ISSUE THREAD

**Issue by madduck** [tridactyl/tridactyl#1633] opened 2019-05-30 22:36 UTC
Tridactyl version: 1.14.10-186-gae6deb0
Firefox version: Mozilla Firefox 66.0.4
Operating system: linux

The configuration file included below is only partially loaded when starting Firefox. It gets fully loaded when I run `source` manually. This seems related to #1409 / #1197, but it's a separate issue I think.

For a start, I use `storageloc==sync`, i.e. the default. Here is the [full config](https://scratch.madduck.net/tridactyl_config.json), and this is `tradactylrc`:

```
sanitize tridactylsync tridactyllocal

set editorcmd x-terminal-emulator -name tridactyl-edit -e vim -c "autocmd BufWritePost <buffer> exe 'write ' . fnameescape((exists('$TMPDIR') ? expand('$TMPDIR') : '/tmp') . '/tridactyl.backup.' . strftime('%Y-%m-%d-%H%M%S'))" +start

set searchengine duckduckgo
set searchurls.pad https://pad.riseup.net/p/%s

set theme dark

set modeindicator false

" autocmd TabEnter .* unfocus

bind <C-1> tabnext_gt 1
bind <C-2> tabnext_gt 2
bind <C-3> tabnext_gt 3
bind <C-4> tabnext_gt 4
bind <C-5> tabnext_gt 5
bind <C-6> tabnext_gt 6
bind <C-7> tabnext_gt 7
bind <C-8> tabnext_gt 8
bind <C-9> tabnext_gt 9

" #639 will fix this
seturl in.xero.com noiframe true
seturl trademe.co.nz noiframe true
```

This only gets read to the first comment, i.e. the `bind` and `seturl` calls won't have been made. Removing the comment has no effect.

**Comment by madduck** [comment] 2019-06-11 01:41
@glacambre Yes, that seems to fix it. At least in 3 starts, I didn't see the problem again. But boy does FF now take forever to load. ;)

**Comment by madduck** [comment] 2019-08-09 01:26
@glacambre I've had the sleep in there for a while now, but all of a sudden, the same problem has come back. So no, not fixed.

**Comment by bovine3dom** [comment] 2020-02-02 16:44
Closing as a duplicate of #1409.

**Closed by bovine3dom** 2020-02-02 16:44 UTC
