### ISSUE TITLE
Keymap only works in normal mode

### ISSUE THREAD

**Issue by aleks-m** [tridactyl/tridactyl#976] opened 2018-09-04 11:42 UTC
*   Brief description of the problem:
Currently Tridactyl standard key bindings don't work with input languages other than English. And it is very annoying to switch back to English every time.
 
*   Steps to reproduce:

    1.  Switch to any input language other that English. 
    2.  Try to press any of standard Tridactyl hotkeys (d,s,S,t,T,o, etc). They don't work.

*   Tridactyl version (`:version`):
1.13.3-1.13.3

*   Firefox version (Top right menu > Help > About Firefox):
61.0.1 (64-bit), Linux.

*   URL of the website the bug happens on:
any.

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
https://gist.github.com/aleks-m/fa0a65c61d487f0144c8b3c8394a977d

----------------

I've had same issue with Vimperator and solved it by the following config snippet with key bindings:
```
" Russian language keyboard mappings (UTF-8)
map ё `
map й q
map ц w
map у e
map к r
map е t
map н y
map г u
map ш i
map щ o
map з p
map х [
map ъ ]
map ф a
map ы s
map в d
map а f
map п g
map р h
map о j
map л k
map д l
map ж;
map э '
map я z
map ч x
map с c
map м v
map и b
map т n
map ь m
map б ,
map ю .
map Ё ~
map Й Q
map Ц W
map У E
map К R
map Е T
map Н Y
map Г U
map Ш I
map Щ O
map З P
map Х {
map Ъ }
map Ф A
map Ы S
map В D
map А F
map П G
map Р H
map О J
map Л K
map Д L
map Ж :
map Э "
map Я Z
map Ч X
map С C
map М V
map И B
map Т N
map Ь M
map Б <
map Ю >

```
Is it possible (and how) to do such thing in Tridactyl?

**Comment by glacambre** [comment] 2018-09-04 11:53
Have you tried getting the name of the command you are interested in (e.g. `:bind r` to find out what's bound to `r`) and then binding the command yourself (e.g. `bind к reload` to have `к` behave like `r`)?
If it didn't work, could you open the firefox console (`<C-I>`), run `document.addEventListener("keydown", console.log)` and give us the output when you press `к`?

**Comment by aleks-m** [comment] 2018-09-04 12:15
>Have you tried getting the name of the command you are interested in (e.g. :bind r to find out what's bound to r) and then binding the command yourself (e.g. bind к reload to have к behave like r)?

Well, this approach works, it is very-very time consuming. I would need to find all necessary key combinations I am using every day, e.g. for key "g" - g,gg,gt,gx,gU,gF, etc. And bind them all. As I see I have near 120 key combinations in `nmaps` and almost all of them contain letters.
Also is hard to support - I need to add new binding for any new standard key binding added to Tridactyl.
In contrast Vimperator `map` allowed me to just map letter-to-letter and forget about it forever.

**Comment by bovine3dom** [comment] 2018-09-04 12:35
Potentially a duplicate of #790?

**Comment by saulrh** [comment] 2018-09-05 07:56
I think that this is less "ignore keymaps entirely" and more "be able to bind keys to keys as well as to other excmds". The point about wanting to be able to e.g. `map п g` and then get both `;п` and `пп` and `пi`/`пш` for free is a very good one for users on non-en_us keyboards.

I think there are two ways to implement this feature request:

### Dedicated key translation map
Set up a separate map, something like `keytransmap`, that maps characters to characters, almost exactly as described above. Every key coming in would be run through this map before being fed to the parser.

### Recursive command resolution
If the value (rhs) of a map entry is not an excmd but there *is* a matching key in the map (lhs), replace your input with that other key and retry parsing (repeating until you either don't have a replacement, terminate in an actual excmd, or hit some max depth limit). For example, if you have the following map:
```javascript
nmaps = {
    aa: excmda withargs
    bb: aa
    c: a
}
```
You would be able to invoke `excmda withargs` with all of the following inputs:
* Input `a`, keyEvents is now `a`. Is a prefix so it isn't stripped, but nothing to do so it stays `a`. Input `a`, keyEvents is now `aa`. This matches a key and resolves to `excmda withargs`. No entry in nmaps has that key so it's evaluated as an excmd.
* Input `b`, keyEvents is now `b`. Is a prefix so it isn't stripped, but nothing to do so it stays `b`. Input `b`, keyEvents is now `bb`. This matches a key in nmaps and resolves to `aa`. An entry in nmaps exists matching that that string, so `aa` resolves to `excmda withargs`. No entry in nmaps has that key so it's evaluated as an excmd.
* Input `c`, keyevents is now `c`. This matches a key in nmaps and resolves to 

You know what, this second option is trash, especially compared to the first option which should actually be pretty easy. And I figure that the death of extended support firefox might get us proportionately more international users, so I'm going to see if I can hack it out before bed. :P

**Comment by bovine3dom** [comment] 2018-09-05 08:15
Yes, I prefer the extra parser option.

**Comment by bovine3dom** [comment] 2018-09-05 13:41
@aleks-m, just put `keymap Ю >` etc in your tridactylrc in the latest betas. Thanks to @saulrh : )

**Comment by dydascal** [comment] 2018-10-02 05:40
I put:
keymap , ?
keymap . /
keymap / |
keymap \ \
keymap а f
keymap А F
keymap б ,
keymap Б <
keymap в d
keymap В D
keymap г u
keymap Г U
keymap д l
keymap Д L
keymap е t
keymap Е T
keymap є '
keymap Є “
keymap ж ;
keymap Ж :
keymap з p
keymap З P
keymap и b
keymap И B
keymap і s
keymap І S
keymap ї ]
keymap Ї }
keymap й q
keymap Й Q
keymap к r
keymap К R
keymap л k
keymap Л K
keymap м v
keymap М V
keymap н y
keymap Н Y
keymap о j
keymap О J
keymap п g
keymap П G
keymap р h
keymap Р H
keymap с c
keymap С C
keymap т n
keymap Т N
keymap у e
keymap У E
keymap ф a
keymap Ф A
keymap х [
keymap Х {
keymap ц w
keymap Ц W
keymap ч x
keymap Ч X
keymap ш i
keymap Ш I
keymap щ o
keymap Щ O
keymap ъ ]
keymap Ъ }
keymap ы s
keymap Ы S
keymap ь m
keymap Ь M
keymap э '
keymap Э “
keymap ю .
keymap Ю >
keymap я z
keymap Я Z
  
and it works, but only in normal mode. It doesn't work in  hint and ignore modes.

**Comment by bovine3dom** [comment] 2018-10-02 11:58
Hint mode is probably to be expected as it has a separate parser. Ignore mode etc should work though (I haven't looked at the implementation though).

**Comment by bovine3dom** [comment] 2019-05-29 17:09
`set keytranslatemodes.ignoremaps true` etc :)

**Closed by bovine3dom** 2019-05-29 17:09 UTC
Labels: P4, bug, i18n

**Comment by polinom11** [comment] 2022-03-11 19:18
> I put: keymap , ? keymap . / keymap / | keymap \ keymap а f keymap А F keymap б , keymap Б < keymap в d keymap В D keymap г u keymap Г U keymap д l keymap Д L keymap е t keymap Е T keymap є ' keymap Є “ keymap ж ; keymap Ж : keymap з p keymap З P keymap и b keymap И B keymap і s keymap І S keymap ї ] keymap Ї } keymap й q keymap Й Q keymap к r keymap К R keymap л k keymap Л K keymap м v keymap М V keymap н y keymap Н Y keymap о j keymap О J keymap п g keymap П G keymap р h keymap Р H keymap с c keymap С C keymap т n keymap Т N keymap у e keymap У E keymap ф a keymap Ф A keymap х [ keymap Х { keymap ц w keymap Ц W keymap ч x keymap Ч X keymap ш i keymap Ш I keymap щ o keymap Щ O keymap ъ ] keymap Ъ } keymap ы s keymap Ы S keymap ь m keymap Ь M keymap э ' keymap Э “ keymap ю . keymap Ю > keymap я z keymap Я Z
> 
> and it works, but only in normal mode. It doesn't work in hint and ignore modes.

Good evening! Where should this text be inserted?

**Comment by bovine3dom** [comment] 2022-03-12 11:26
@polinom11 you can install the native messenger (see :native) and then place a text file with the keymap commands at ~/.config/tridactyl/tridactylrc

or you can make a GitHub gist of the keymaps and source them using `:source --url [URL to raw GitHub gist]`

**Comment by polinom11** [comment] 2022-03-13 05:58
> @polinom11 you can install the native messenger (see :native) and then place a text file with the keymap commands at ~/.config/tridactyl/tridactylrc
> 
> or you can make a GitHub gist of the keymaps and source them using `:source --url [URL to raw GitHub gist]`

I enter the command `:nativeinstall`, paste the resulting text into cmd.exe and this is what it gives me: 

Исключение при вызове "DownloadFile" с "2" аргументами: "Базовое соединение закрыто: Непредвиденная ошибка при передаче."
строка:1 знак:176
+ [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12;(New-Object System.Net.WebClient).DownloadFile <<<< ('https://raw.githubusercontent.com/tridactyl/native_messenger/master/installers/windows.ps1', 'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1');& 'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1' -Tag 1.22.0;Remove-Item 'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1'
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Имя "C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1" не распознано как имя командлета, функции, файла скрипта или выполняемой программы. Проверьте правильность написания имени, а также наличие и правильность пути, послечего повторите попытку.
строка:1 знак:339
+ [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12;(New-ObjectSystem.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/tridactyl/native_messenger/master/installers/windows.ps1', 'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1');& <<<<  'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1' -Tag 1.22.0;Remove-Item 'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1'
    + CategoryInfo          : ObjectNotFound: (C:\Users\polino...stallnative.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Remove-Item : Не удается найти путь "C:\Users\polinom\AppData\Local\Temp\tridactyl_installnative.ps1", так как он не существует.
строка:1 знак:429
+ [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12;(New-Object System.Net.WebClient).DownloadFile('https://raw.githubusercontent.com/tridactyl/native_messenger/master/installers/windows.ps1', 'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1');& 'C:\Users\polinom\AppData\Local\Temp/tridactyl_install native.ps1' -Tag 1.22.0;Remove-Item <<<<  'C:\Users\polinom\AppData\Local\Temp/tridactyl_installnative.ps1'
    + CategoryInfo          : ObjectNotFound: (C:\Users\polino...stallnative.ps1:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
