### ISSUE TITLE
Provide count to `js` commands.

### ISSUE THREAD

**Issue by kevincox** [tridactyl/tridactyl#1001] opened 2018-09-11 11:47 UTC
*   Brief description of the problem: `js` commands can not utilize the count parameter.
*   Steps to reproduce:
  * Type 15mybind
  * Try to use the 15 insode of mybind.

It would be nice if the snippet could access and use this value.

**Comment by bovine3dom** [comment] 2018-09-11 11:56
Duplicate of #466 : )

Thanks for reporting.

**Closed by bovine3dom** 2018-09-11 11:56 UTC
