### ISSUE TITLE
Overlapped non clickable hints

### ISSUE THREAD

**Issue by caputchinefrobles** [tridactyl/tridactyl#506] opened 2018-05-10 04:32 UTC
It is showing hints on non clickable areas in some pages:

- https://www.mozilla.org/en-US/privacy/firefox/
- https://developer.mozilla.org/pt-BR/Add-ons/WebExtensions
- https://www.globo.com/
- ...

1.11.0-72-gd0bde43

**Comment by glacambre** [comment] 2018-05-10 05:18
Probably a duplicate of https://github.com/cmcaine/tridactyl/issues/367
With a possible improvement mentioned in https://github.com/cmcaine/tridactyl/issues/497

**Comment by bovine3dom** [comment] 2019-05-26 21:54
I think this is pretty much fixed in #1219, with any remaining jank covered by #367.

**Closed by bovine3dom** 2019-05-26 21:54 UTC
