### ISSUE TITLE
exstr not defined in completions if command line iframe is not defined

### ISSUE THREAD

**Issue by EJEP** [tridactyl/tridactyl#580] opened 2018-05-20 13:53 UTC
As a symptom all commands to tridactyl get eaten

**Comment by glacambre** [comment] 2018-06-08 13:39
Hi. What were you trying to do when you encountered this issue? I'm not very familiar with how the completion and iframe stuff works so I don't know how exactly how to reproduce this bug.

**Comment by EJEP** [comment] 2018-06-08 19:28
So far as I recall, on loading a webpage Firefox stopped responding to all keypresses, both tridactyl and built-in. I think this was only the case on that tab. @cmcaine might be able to provide some help as he actually figured out what the issue was.

**Comment by glacambre** [comment] 2018-10-03 10:30
The description of the problem sounds a little bit like something that could have been fixed by https://github.com/tridactyl/tridactyl/pull/1044 . Since we don't know how to reproduce this I think it's reasonable to close this issue. Feel free to come back here to reopen it/open a new issue if you hit this bug again.

**Closed by glacambre** 2018-10-03 10:30 UTC
