### ISSUE TITLE
nmaps empty after invoking "bind"

### ISSUE THREAD

**Issue by mdobric** [tridactyl/tridactyl#991] opened 2018-09-07 16:42 UTC
I used the "bind" command to set change the "o:" operation and then used "unbind" to reset it. After invoking "bind", "viewconfig" showed nmaps only containing the "o:" operation, and after invoking "unbind", nmaps was empty. I tried reinstalling the extension without success. All commands still seem to work correctly. I am using Firefox ESR 60.2.0esr (64-bit) on macOS 10.13.3 and Tridactyl 1.14.0pre1821.

viewconfig output here: 
https://gist.github.com/mdobric/a4f75e4d3c120a1eac1ca6cda010bc16

**Comment by bovine3dom** [comment] 2018-09-07 17:29
Duplicate of issue #390 - this has been around for a while and I've not yet gotten around to looking into it.

Sorry that it confused you. `viewconfig nmaps` will get you all binds.

**Closed by bovine3dom** 2018-09-07 17:29 UTC
