### ISSUE TITLE
Website doesn't load

### ISSUE THREAD

**Issue by Figuera** [tridactyl/tridactyl#4057] opened 2022-01-05 23:36 UTC
-   Some websites, specially government's websites refuses to load if tridactyl is enable. But load normally when it is disable

-   To reproduce try to open: https://psada.psa.gov.ph/index.php/catalog/145

-   Tridactyl version (`:version`): 1.22.0

-   Firefox version (Top right menu > Help > About Firefox): 95.0

-   user config: https://gist.github.com/Figuera/4a1893d4ac0180d070e09b2ff3b99ab8 (I am not sure if this is what you want)

- .tridactylrc: https://gist.github.com/Figuera/96494894c39d3c9e83bd354cc8c1c5dc

- I am using Arch Linux, native version 1.1

**Comment by bovine3dom** [comment] 2022-01-10 21:25
Duplicate of #639 :)

**Closed by bovine3dom** 2022-01-10 21:25 UTC

**Comment by bovine3dom** [comment] 2022-01-10 21:26
(In the meantime you can use `:seturl [url regex] noiframe true` to fix it, but Tridactyl's commandline won't be available on that page)
