### ISSUE TITLE
Midnight theme has weird changelog on new tab page

### ISSUE THREAD

**Issue by bovine3dom** [tridactyl/tridactyl#3979] opened 2021-10-26 12:05 UTC
As reported by Lexi on Matrix: https://matrix.to/#/!xmubtggllUtLrQiGyn:matrix.org/$163524883184265GfZqz:matrix.org?via=matrix.org&via=libera.chat&via=t2bot.io

**Comment by davidscotson** [comment] 2022-02-27 20:26
See #4005, a dupe of this I created a fix for.

**Closed** 2022-02-27 22:24 UTC
Labels: bug, P4
