### ISSUE TITLE
tridactyl 1.22.0 makes meet.jit.si hang

### ISSUE THREAD

**Issue by m1027** [tridactyl/tridactyl#4020] opened 2021-12-09 08:14 UTC
Tridactyl version: 1.22.0
Firefox version: Mozilla Firefox 94.0.2
Operating system: linux

I've been able to open meet.jit.si (video conferencing) before 1.22.0 successfully.

Since 1.22.0 the site opens but then immedately gets stuck.
Same for firefox 95.x.

Workaround: :seturl ^https?://meet.jit.si superignore true

**Comment by Brixy** [comment] 2021-12-09 13:18
```
Tridactyl version: 1.22.0
Firefox version: 95.0
Operating system: Void Linux
```

I can second this. For me meet.jit.si does not open at all if Tridactyl is active.

**Comment by wavexx** [comment] 2022-01-10 14:37
Tridactyl version: 1.22.0
Firefox version: Mozilla Firefox 95.0.1
Operating system: linux

- Load  https://meet.jit.si/test on a fresh firefox 95 profile, fresh trydactyl 1.22.0 installation using the latest build directly. All settings are default.
- You get a grey screen before any prompt and/or pre-meet screen.

If you disable tridacyl and/or have the developer tools open though, it loads just fine.
What I've seen to far is FF complaining that the charset is set too late in the page:

    The character encoding declaration of document was found too late for it to take effect. The encoding declaration needs to be moved to be within the first 1024 bytes of the file.

However, when devtools are open and/or when tridacyl is disabled, the following is shown:

    The page was reloaded, because the character encoding declaration of the HTML document was not found when prescanning the first 1024 bytes of the file. The encoding declaration needs to be moved to be within the first 1024 bytes of the file.

I have another local instance of jitsi that doesn't have the charset issue and it loads fine also with trydactyl, so I think that's at least related.

**Comment by bovine3dom** [comment] 2022-01-11 11:40
Duplicate of #639 :)

`:seturl [url regex] noiframe true` to work around it until we fix it. NB: the Tridactyl command line won't work on the page.

**Closed by bovine3dom** 2022-01-11 11:40 UTC
