### ISSUE TITLE
colon command is not working on ChatGPT

### ISSUE THREAD

**Issue by Shad0wKilleer** [tridactyl/tridactyl#5068] opened 2024-10-19 09:40 UTC
I am working on chatgpt. The problem I am having is that the [ChatGPT](chatgpt.com) is not working properly with tridactyl. The problem  I am having is as follows:
1. When I press ":", nothing happens
2. Even though modeindicator is set to true, only on [ChatGPT](chatgpt.com) is does not show the mode

When I initially load the website (or reloads it), it shows the mode "normal" for a brief second before hiding it completely even though modeindicator is set to true and there are modes displayed as indented on all other websites. Then I can use commands like "gi" to insert text, "f" for hints etc. Also the keys like "J" or "K" to move to other tabs also works as intended. But the problem comes when I try "t", "b" etc. or try to use ":", it won't respond. The strangest thing is that now the site won't respond to commands that were previously working i.e., "J", "K", "gi", "f" etc. Even strange the site won't respond to shortcuts like <C-r> or <C-Shift-r> for reloading that is browser shortcut. At this stage, my keyboard is useless but I can still use shortcuts that are bind to my OS. I have to use mouse and reload the site manually. After reloading, it starts from where I began this paragraph and again stops if I try to use any of mentioned commands. 

System details:
OS: **Arch LInux**
Browser: **ZenBrowser** (Though I have same issue on Firefox on the same OS)
Tridactyl ":version" gives: **1.24.1**
Tridactyl ":native" give: **0.4.1**

PS: I tried to clear cache/browser data. I tried to go to a different container. I also tried to go to a different profile but the issue persist. I also tried to create a profile with only tridactyl as extension to make sure no other extension is messing up, but no luck.

**Comment by bovine3dom** [comment] 2024-10-19 10:10
Duplicate of #5050 which is fixed on the master branch and will appear in a beta when I get round to doing a release :)

**Closed by bovine3dom** 2024-10-19 10:10 UTC
