### ISSUE TITLE
"Couldn't deduce which profile you want" when have only one profile

### ISSUE THREAD

**Issue by Carl-Robert** [tridactyl/tridactyl#3881] opened 2021-08-05 03:35 UTC
-   Brief description of the problem:
Trying to use the native for anything results in `controller in excmd: Error: Couldn't deduce which profile you want.` I have only one folder in the profile directory and about:profiles show only one profile as well. New firefox esr install, no other add-ons installed.

-   Steps to reproduce:

    1. Use a native command like :restart
    
-   Tridactyl version (`:version`): 1.21.1pre5980-0b47bd70

-   Firefox version (Top right menu > Help > About Firefox): 78.12.0esr (64-bit)

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): https://paste.ee/d/jInTQ

-   Operating system: Windows 10 Enterprise x64 20H2
-   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl: C:\Program Files\Mozilla Firefox;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\ZeroTier\One\;C:\Users\User\Programs;C:\Users\User\AppData\Roaming\Python\Python39\Scripts;C:\Program Files\nodejs\;C:\Users\User\scoop\shims;C:\Users\User\Programs\mpv;C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\User\AppData\Local\Programs\Python\Python39\;C:\Users\User\AppData\Local\Microsoft\WindowsApps;C:\Users\User\Programs\MoonEdit;C:\Users\User\Programs\;C:\Users\User\AppData\Roaming\npm

**Comment by bovine3dom** [comment] 2021-08-06 18:36
I can't find it now but I'm sure we used to warn that profile detection didn't work on Windows. Maybe we tried to fix it but didn't manage to? @Rummskartoffel I think might have played with it.

Have you tried using `:set profiledir` to specify it explicitly?

**Comment by Rummskartoffel** [comment] 2021-08-06 21:55
I think I figured out why it's broken at some point. Should be in the comments to some older issue. I'm not sure I ever tried to actually make a fix, though.

**Comment by Rummskartoffel** [comment] 2021-08-07 06:59
See #3135, #3064, #1627

**Comment by Carl-Robert** [comment] 2021-08-13 00:31
Confirmed that setting profile-dir manually works.

Hopefully get the automatic profile detection to work on Windows soon or at least make the error message clearer for Windows users.

**Comment by bovine3dom** [comment] 2021-08-13 12:49
Closing as a dupe of #1627 then. Thanks for checking :)

**Closed by bovine3dom** 2021-08-13 12:49 UTC
