### ISSUE TITLE
firedragon "Couldn't deduce which profile you want."

### ISSUE THREAD

**Issue by bryangeplant** [tridactyl/tridactyl#4117] opened 2022-02-21 10:06 UTC
Installed trydactyl for some time now, just installed the native messenger thing. Haven't changed much of my configuration. Tried running `guiset gui none` and the message "controller in excmd: Error: Couldn't deduce which profile you want. See ':help profiledir'". Since I have garuda linux, it comes with firedragon installed, so i'm using that. If it changes stuff that much, it's okay if you guys don't have the time to work on this. One thing that I noticed is that the profile directory is in "~/.firedragon/", not firefox, so could that be a potential issue?

Here is the data for my firefox stuff: 
<details>
<summary> Here is the data for my firefox stuff: </summary>

Name | FireDragon
-- | --
97.0
20220212132809
garudalinux
Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0
Linux 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000
Sweet-Dark / Sweet
1/1
1/1               Enabled by default
5
Active
Missing
Missing
Missing
false

    Application Basics
------------------

Name: FireDragon
Version: 97.0
Build ID: 20220212132809
Distribution ID: garudalinux
User Agent: Mozilla/[5](https://github.com/tridactyl/tridactyl/issues/new#remote-processes).0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0
OS: Linux 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000
OS Theme: Sweet-Dark / Sweet
Multiprocess Windows: 1/1
Fission Windows: 1/1 Enabled by default
Remote Processes: 5
Enterprise Policies: [Active](about:policies#active)
Google Location Service Key: Missing
Google Safebrowsing Key: Missing
Mozilla Location Service Key: Missing
Safe Mode: false

FireDragon Features
-------------------

Name: Firefox Screenshots
Version: 39.0.1
ID: screenshots@mozilla.org

Name: Form Autofill
Version: 1.0.1
ID: formautofill@mozilla.org

Name: Picture-In-Picture
Version: 1.0.0
ID: pictureinpicture@mozilla.org

Name: Web Compatibility Interventions
Version: 29.7.0
ID: webcompat@mozilla.org

Remote Processes
----------------

Type: Privileged About
Count: 1

Type: Extension
Count: 1

Type: Isolated Web Content
Count: 1

Type: Preallocated
Count: 2

Add-ons
-------

Name: Brazilian Portuguese Checker (New Spelling)
Type: dictionary
Version: 65.2018.12.8
Enabled: true
ID: pt-BR@dictionaries.addons.mozilla.org

Name: Add-ons Search Detection
Type: extension
Version: 2.0.0
Enabled: true
ID: addons-search-detection@mozilla.com

Name: Dark Reader
Type: extension
Version: 4.9.45
Enabled: true
ID: addon@darkreader.org

Name: DuckDuckGo
Type: extension
Version: 1.1
Enabled: true
ID: ddg@search.mozilla.org

Name: Enhancer for YouTube™
Type: extension
Version: 2.0.112
Enabled: true
ID: enhancerforyoutube@maximerf.addons.mozilla.org

Name: Honey
Type: extension
Version: 12.8.4
Enabled: true
ID: jid1-93CWPmRbVPjRQA@jetpack

Name: Tridactyl
Type: extension
Version: 1.22.0
Enabled: true
ID: tridactyl.vim@cmcaine.co.uk

Name: uBlock Origin
Type: extension
Version: 1.41.6
Enabled: true
ID: uBlock0@raymondhill.net

Name: Wikipedia (en)
Type: extension
Version: 1.1
Enabled: true
ID: wikipedia@search.mozilla.org

Name: Português (pt-BR) Language Pack
Type: locale
Version: 97.0.1buildid20220216.172458
Enabled: true
ID: langpack-pt-BR@firefox.mozilla.org

Environment Variables
---------------------

DISPLAY: :0
MOZ_ASSUME_USER_NS: 1
MOZ_LAUNCHED_CHILD:
MOZ_APP_SILENT_START:
XRE_PROFILE_PATH:
XRE_PROFILE_LOCAL_PATH:
XRE_START_OFFLINE:
XRE_BINARY_PATH:
XRE_RESTARTED_BY_PROFILE_MANAGER:

Experimental Features
---------------------

about:home startup cache (browser.startup.homepage.abouthome_cache.enabled): false
Cookies: SameSite=Lax by default (network.cookie.sameSite.laxByDefault): false
Cookies: SameSite=None requires secure attribute (network.cookie.sameSite.noneRequiresSecure): false
Cookies: Schemeful SameSite (network.cookie.sameSite.schemeful): false
CSS: Constructable Stylesheets (layout.css.constructable-stylesheets.enabled): false
CSS: Masonry Layout (layout.css.grid-template-masonry-value.enabled): false
Developer Tools: Compatibility Panel (devtools.inspector.compatibility.enabled): false
Developer Tools: Execution Context Selector (devtools.webconsole.input.context): true
Developer Tools: Service Worker debugging (devtools.debugger.features.windowless-service-workers): false
Media: JPEG XL (image.jxl.enabled): false
Address Bar: show results during IME composition (browser.urlbar.keepPanelOpenDuringImeComposition): false
Web API: WebGPU (dom.webgpu.enabled): false
WebRTC Global Mute Toggles (privacy.webrtc.globalMuteToggles): false
Win32k Lockdown (security.sandbox.content.win32k-disable): false

Important Modified Preferences
------------------------------

accessibility.typeaheadfind.flashBar: 0
browser.contentblocking.category: custom
browser.sessionstore.upgradeBackup.latestBuildID: 20220212132809
browser.urlbar.placeholderName: DuckDuckGo
browser.urlbar.placeholderName.private: DuckDuckGo
dom.security.https_only_mode_ever_enabled: true
extensions.lastAppVersion: 97.0
gfx.blacklist.webrender: 4
gfx.blacklist.webrender.failureid: FEATURE_FAILURE_DDX_INTEL
idle.lastDailyNotification: 1645433780
javascript.use_us_english_locale: true
media.decoder-doctor.MediaPlatformDecoderNotFound.formats: video/mp4
media.eme.enabled: true
media.gmp-gmpopenh264.abi: x86_64-gcc3
media.gmp-gmpopenh264.lastUpdate: 1644177652
media.gmp-gmpopenh264.version: 1.8.1.1
media.gmp-manager.buildID: 20220212132809
media.gmp-manager.lastCheck: 1645432854
media.gmp-widevinecdm.abi: x86_64-gcc3
media.gmp-widevinecdm.lastUpdate: 1645096202
media.gmp-widevinecdm.version: 4.10.2391.0
media.gmp.storage.version.observed: 1
media.videocontrols.picture-in-picture.video-toggle.has-used: true
network.dns.disableIPv6: false
network.http.referer.disallowCrossSiteRelaxingDefault: true
places.database.lastMaintenance: 1644838338
privacy.annotate_channels.strict_list.enabled: true
privacy.history.custom: true
privacy.partition.network_state.ocsp_cache: true
privacy.purge_trackers.date_in_cookie_database: 0
privacy.purge_trackers.last_purge: 1645433780273
privacy.sanitize.pending: [{"id":"newtab-container","itemsToClear":[],"options":{}}]
privacy.trackingprotection.socialtracking.enabled: true
privacy.userContext.enabled: true
privacy.userContext.extension: tridactyl.vim@cmcaine.co.uk
security.sandbox.content.tempDirSuffix: 80786321-0811-4206-95b8-1dcf2e7c70e6
services.sync.declinedEngines:
storage.vacuum.last.index: 1
storage.vacuum.last.places.sqlite: 1644178090

Important Locked Preferences
----------------------------

browser.fixup.alternate.enabled: false
browser.tabs.crashReporting.sendReport: false
browser.urlbar.quicksuggest.dataCollection.enabled: false
browser.urlbar.quicksuggest.enabled: false
browser.urlbar.quicksuggest.scenario: history
browser.urlbar.suggest.quicksuggest.nonsponsored: false
browser.urlbar.suggest.quicksuggest.sponsored: false
fission.autostart.session: true
network.captive-portal-service.enabled: false
network.http.speculative-parallel-limit: 0
network.predictor.enabled: false
network.prefetch-next: false
privacy.trackingprotection.cryptomining.enabled: true
privacy.trackingprotection.enabled: true
privacy.trackingprotection.fingerprinting.enabled: true
privacy.trackingprotection.pbmode.enabled: true
security.csp.enable: true
security.protectionspopup.recordEventTelemetry: false
security.tls.enable_0rtt_data: false

Startup Cache
-------------

Disk Cache Path: /home/elysium/.cache/firedragon/yfxabv6c.default-release/startupCache/startupCache.8.little
Ignore Disk Cache: false
Found Disk Cache on Init: true
Wrote to Disk Cache: false

</details>

**Comment by bovine3dom** [comment] 2022-04-21 12:36
Sorry this took so long to reply to, I don't know how I missed this issue :)

I think this is a duplicate of #3965 - please see if the symlink trick works for you!

**Closed by bovine3dom** 2022-04-21 12:36 UTC
