### ISSUE TITLE
Add excmd :modeclear (and :moderemove?) to clear&remove an entire mode

### ISSUE THREAD

**Issue by bew** [tridactyl/tridactyl#3099] opened 2020-12-13 19:02 UTC
Tridactyl version: 1.20.3
Firefox version: Mozilla Firefox 83.0
Operating system: linux

`:modeclear`: I would like to remove all the default keys from normal mode, I don't like surprises when I type keys on my keyboard where I could hit one of the default Tridactyl binding :smiley:

`:moderemove`: I saw we can create custom modes with `bind --mode=mymode ...`, but didn't see a way to remove a mode, does it remove itself if it is empty? (if so `:modeclear` is enough)

**Comment by bovine3dom** [comment] 2020-12-13 20:17
Empty modes are the same as deleted modes, I think, sort of. There's a caveat that Tridactyl always starts in `normal` mode.

I think essentially this issue is "`:setnull` should work on objects" like searchurls or in this case nmaps.

**Comment by Rummskartoffel** [comment] 2021-02-15 18:00
I can do `:setnull nmaps` just fine, but that just makes the binds fall through to the default config.

**Comment by bovine3dom** [comment] 2021-02-15 21:49
Yeah, the problem isn't in `:setnull`, it's in `mergeDeepCull`:

https://github.com/tridactyl/tridactyl/blob/ef4dd014cf8141a0e7dbbeb10441361bd3502077/src/lib/config.ts#L1163

We need to make `null` always win when objects are merged. Honestly this function - https://github.com/tridactyl/tridactyl/blob/ef4dd014cf8141a0e7dbbeb10441361bd3502077/src/lib/config.ts#L1218

looks a bit messier than I would have expected it to be.

**Comment by bovine3dom** [comment] 2021-03-01 07:16
Duplicate of #1774

**Closed by bovine3dom** 2021-03-01 07:16 UTC
Labels: P4, enhancement
