### ISSUE TITLE
bindurl bindings are leaking between sites

### ISSUE THREAD

**Issue by buckley-w-david** [tridactyl/tridactyl#1798] opened 2019-08-12 00:17 UTC
Tridactyl version: 1.16.2pre3053-132e385
Firefox version: Mozilla Firefox 68.0.1
Operating system: linux

*   Brief description of the problem: bindurl settings are leaking between sites after some time

*   Steps to reproduce:
1: Run `:sanitise tridactyllocal tridactylsync` to clear existing settings (To remove noise and prevent potential interference)
2: Run `:bindurl reddit.com gu urlparent 3` to give `reddit.com` a new binding
3: Run `:bindurl news.ycombinator.com f hint -Jc a` to give `news.ycombinator.com` a new binding
4: Quickly run `:viewconfig` to observe each sites bindings as they should be
![tri-before](https://user-images.githubusercontent.com/1952571/62841303-88459300-bc74-11e9-977d-6f83fdf33c6f.png)
(Note this screenshot was slightly edited to remove all the other default bindings that tridactyl added to reddit's nmaps, they were kept in the second screenshot since they did not get in the way)
5: Wait some time (I find it happens within a few seconds)
6: Run `:viewconfig` again, and observe that `news.ycombinator.com` has gained the binding from `reddit.com`
![tri-after](https://user-images.githubusercontent.com/1952571/62841208-19b40580-bc73-11e9-8dde-27ab57384b11.png)

It seems that the binding is added the same time that all the default bindings are inserted (you can see from the first screenshot that  `news.ycombinator.com` had yet to receive them)

**Comment by StormPooper** [comment] 2019-08-16 22:18
I was seeing this earlier today and actually ended up recreating my config from scratch, but I actually think it's a bug with `:viewconfig`, since it only seems to display like that sometimes - if you open it up later without changing anything then they will sometimes appear to be correct.

**Comment by bovine3dom** [comment] 2023-06-01 17:02
I can't reproduce this, so I'm going to close the issue and assume we fixed it somehow :)

Feel free to re-open if it persists for you.

**Closed by bovine3dom** 2023-06-01 17:02 UTC
