### ISSUE TITLE
Make tridactyl not focus on the url bar when opening a new tab

### ISSUE THREAD

**Issue by BobSpams** [tridactyl/tridactyl#2986] opened 2020-11-09 05:05 UTC
Is there a way I can make tridactyl not focus on the url bar when opening a new tab? If i either click on the "+" or Ctrl+T, it focuses on the url bar and shows "Extension: Trida..."

**Comment by bovine3dom** [comment] 2020-11-09 07:45
Duplicate of #2840 - unfortunately it's a Firefox bug. We don't think we can do anything about it. You can use a build without a new tab page, as linked in that issue, or you could downgrade to Firefox ESR (I think the bug was introduced in FF80).

**Closed by bovine3dom** 2020-11-09 07:45 UTC
