### ISSUE TITLE
ZZ fails to save opened windows

### ISSUE THREAD

**Issue by Massimo-B** [tridactyl/tridactyl#4147] opened 2022-03-17 12:06 UTC
firefox-91.7.0
Tridactyl: Beta 1.22.0pre6186

ZZ is closing Firefox immediately without any dialog. When restarting, only the last single window is restored.
When closing Firefox via File->Quit, then I'm ask to close X windows with Y tabs. After that restarting, all windows with all tabs are restored. How can I close Firefox via Tridactyl that way saving the whole session with all windows?

**Comment by bovine3dom** [comment] 2022-03-17 13:39
Duplicate of issue #350 - see that issue for workarounds :)

**Closed by bovine3dom** 2022-03-17 13:39 UTC

**Comment by Massimo-B** [comment] 2022-03-17 14:55
Is the killall binding still the only workaround? Why is ZZ behaving different from the usual Quit in the Firefox menu?

**Comment by hejops** [comment] 2023-03-20 17:44
`killall firefox` still produces the expected behaviour, but the workaround no longer seems to be effective on Firefox 111.0 / tridactyl 1.23.0 / native 0.3.6.

**Comment by bovine3dom** [comment] 2023-03-21 23:58
> Why is ZZ behaving different from the usual Quit in the Firefox menu?

Mozilla refused to give us a quit Firefox API so we just close all the windows really quickly and hope for the best.

Thanks for the update hejops, I haven't noticed it not working yet. I'll keep an eye out.
