### ISSUE TITLE
Open hint in background tab not working on Android

### ISSUE THREAD

**Issue by robsmith11** [tridactyl/tridactyl#854] opened 2018-07-25 08:30 UTC
I thought this was working in the past, but could be wrong.  When I select a hint from `F`, the link is  not loaded (in either a new tab or current tab), and the mode just goes back to "normal".

All other tab related functions like `tabopen` and `gt/gT` seem to be working, so I think it should be possible to make `F` work on Android.

I'm using 1.13.1 on Firefox Beta for Android 8.1.

**Comment by glacambre** [comment] 2018-07-25 09:09
This might be caused by [cookieStoreId](https://github.com/cmcaine/tridactyl/blob/70e1e35228a700506e8c895a64f5b8542df127a3/src/excmds.ts#L2854) which is [not supported on Android](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create).

**Comment by bovine3dom** [comment] 2018-07-25 09:55
Before we get around to fixing this, `bind F hint -W tabopen -b` might work for you @robsmith11.

**Comment by robsmith11** [comment] 2018-07-25 12:02
@bovine3dom 
Thanks, that does open the link in a new tab, but it leaves the original tab in a corrupted state.. any key presses result in Tridactyl showing an error:
```
# Error processing pushKey([object Object]) TypeError: modeState is undefined 
```

**Comment by bovine3dom** [comment] 2018-07-25 12:19
Sounds like a different bug... :(

**Comment by bovine3dom** [comment] 2018-07-31 13:52
Waterfox has the same issue.

**Comment by glacambre** [comment] 2018-07-31 17:26
I think the `# Error processing pushKey([object Object]) TypeError: modeState is undefined ` bug could be fixed by https://github.com/cmcaine/tridactyl/pull/668/files.

**Comment by bovine3dom** [comment] 2019-05-29 17:21
Closing like #1282 - I don't see us having the manpower to test on Android. Hopefully `strict_min_version` will help, even though Android doesn't have full parity with desktop.

**Closed by bovine3dom** 2019-05-29 17:21 UTC
Labels: Android :robot:, P4, bug
