### ISSUE TITLE
How to set transparent hint background

### ISSUE THREAD

**Issue by noib3** [tridactyl/tridactyl#3041] opened 2020-11-29 15:18 UTC
Tridactyl version: 1.20.3pre4852-ebc222e0
Firefox version: Mozilla Firefox 83.0
Operating system: mac

Tridactyl version: 1.20.3pre4852-ebc222e0
Firefox version: Mozilla Firefox 83.0
Operating system: mac

I'm trying to set the hint's background to always be transparent. I tried setting `--tridactyl-hint-bg: none;`, which works most of the time but not always.

An example of this is GitHub's New issue button, which gets washed away:
![2020-Nov-29@16:12:10](https://user-images.githubusercontent.com/59321248/100545743-ab2afa80-325d-11eb-8a6d-c0fe8882874c.png)
comparison with qutebrowser:
![2020-Nov-29@16:12:47](https://user-images.githubusercontent.com/59321248/100545759-bda53400-325d-11eb-9ba6-b237c169962c.png)

I tried changing `none` to `unset`, `initial`, `inherit` and `transparent`, but none of them worked.

**Comment by bovine3dom** [comment] 2020-11-29 15:39
Closing as a duplicate of #2996 - at the moment I don't think it is possible.

**Closed by bovine3dom** 2020-11-29 15:39 UTC
