### ISSUE TITLE
latest Firefox displays highlight element overlayed onto command line 

### ISSUE THREAD

**Issue by protrolium** [tridactyl/tridactyl#2644] opened 2020-07-19 19:47 UTC
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 78.0.2
Operating system: mac

Here is a screenshot of `t` for newtab:
<img width="1440" alt="Screen Shot 2020-07-19 at 12 41 30 PM" src="https://user-images.githubusercontent.com/4933883/87883690-df440400-c9bd-11ea-887c-d7f20aacf175.png">

There seems to be a Firefox GUI element intruding into Tridactyl's interface.

**Comment by bovine3dom** [comment] 2020-07-19 23:25
I've also noticed this on Windows but not Linux. It might be showing that the input box is selected.

**Comment by purgat0ri** [comment] 2020-08-09 02:18
Can confirm that this happens for Mac as well.

**Comment by bovine3dom** [comment] 2020-08-20 21:28
I think this might have been fixed in FF79 - I can't reproduce it on Windows any more.

**Closed by bovine3dom** 2020-08-20 21:28 UTC
Labels: P3, bug, probably-not-our-fault

**Comment by ebith** [comment] 2020-10-23 13:18
I have the same problem on Windows.
This can be fixed by adding `input:focus#tridactyl-input { outline: none; }` to userContent.css.
ref: [Fix #2873: improve colours docs · tridactyl/tridactyl@f6b8ce0](https://github.com/tridactyl/tridactyl/commit/f6b8ce04f7cc6876baa8e5279179fb37a5d2ec98)
