### ISSUE TITLE
Saving gui related properties creates new Firefox profile folder

### ISSUE THREAD

**Issue by C0rWin** [tridactyl/tridactyl#3135] opened 2020-12-27 18:11 UTC
Tridactyl version: 1.20.4
Firefox version: Mozilla Firefox 84.0.1
Operating system: mac

*   Saving gui related properties creates new Firefox profile folder without taking any effect on default profile

*   Steps to reproduce:

Working on `Mozilla Firefox 84.0.1` after installing `Tridactyl` trying to update gui options with running 

```
guiset gui none
```

restarting Firefox have not effect, while new profile folder being created, switching profile to newly created one seems to take effect, while I think expected behavior would be to take effect on default profile without creating a new one.

**Comment by bovine3dom** [comment] 2020-12-27 20:43
That's strange. What were the names of the folders, the correct one and the created one? What's the value of `:get profiledir`?

**Comment by C0rWin** [comment] 2020-12-27 23:50
> That's strange. What were the names of the folders, the correct one and the created one? What's the value of `:get profiledir`?

The output for `:get profiledir` is 

```
profiledir = auto
```

the folder names are:

1. The one I'm actually using is - `xhr0k59e.default-release`
2. The one Tridactyl writes into is - `m8kg5ivz.default`

I've also tried to copy the content of the former into the first one, while didn't have any apparent effect.

**Comment by bovine3dom** [comment] 2020-12-28 13:47
Tridactyl doesn't have the imagination to come up with that name on its own so I guess what has happened is that it found a reference to an old deleted profile in profiles.ini - https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/lib/native.ts#L496 - and decided to resurrect it (which is a bug).

Could you post the contents of profiles.ini? I don't think there's anything sensitive there but it might be worth looking at it before you post it.

While you wait for us to fix the bug, if you `:set profiledir /path/to/xhr0k...` everything should work if you rerun the command.

**Comment by C0rWin** [comment] 2020-12-28 14:19
Where can I locate `profiles.ini`?

**Comment by bovine3dom** [comment] 2020-12-28 14:21
For Mac: 

`$HOME/Library/Application Support/Firefox`


https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/lib/native.ts#L487

**Comment by Rummskartoffel** [comment] 2020-12-28 14:27
I'm not sure this is an issue with deleted profiles. On a pretty much completely fresh install of Firefox on a win10 VM (definitely no changes to any profiles), I've got two profiles – "default" and "default-release", with the latter being the actual default profile, but `:guiset` reliably writes to "default".

**Comment by C0rWin** [comment] 2020-12-28 14:30
> For Mac:
> 
> `$HOME/Library/Application Support/Firefox`
> 
> https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/lib/native.ts#L487

```
[Profile1]
Name=default
IsRelative=1
Path=Profiles/m8kg5ivz.default
Default=1

[Profile0]
Name=default-release
IsRelative=1
Path=Profiles/xhr0k59e.default-release

[General]
StartWithLastProfile=1
Version=2

[Install2656FF1E876E9973]
Default=Profiles/xhr0k59e.default-release
Locked=1```

**Comment by C0rWin** [comment] 2020-12-28 14:31
> I'm not sure this is an issue with deleted profiles. On a pretty much completely fresh install of Firefox on a win10 VM (definitely no changes to any profiles), I've got two profiles – "default" and "default-release", with the latter being the actual default profile, but `:guiset` reliably writes to "default".

I would expect that should be the case, but obviously, work differently than expected.

**Comment by C0rWin** [comment] 2020-12-28 14:40
And I know it's has been discussed here in several issues, while I seem to have issues with `:guiset gui none` not having any effect after I restart my FF. Trying to understand what is going on lead me to the discovery of `Tridactyl` creating a new profile folder.

**Comment by Rummskartoffel** [comment] 2020-12-28 15:09
After a bit of digging, I think I've found the problem. We're checking whether the *profile's* entry has `Default=1`, https://github.com/tridactyl/tridactyl/blob/73ef32497d6b1fc7975d703753eca63de69e8af6/src/lib/native.ts#L603 but Firefox uses the path set under `[Install<gobbledygook>]`'s `Default` key as the *actual* default profile. So we need to check that and not the profiles' own entries to find the default, it seems.

**Comment by C0rWin** [comment] 2020-12-28 16:42
> After a bit of digging, I think I've found the problem.

Is there a way or workaround that makes `:guiset gui none` to work and save changes into the correct profile?

**Comment by bovine3dom** [comment] 2020-12-28 16:47
@C0rWin

> While you wait for us to fix the bug, if you :set profiledir /path/to/xhr0k... everything should work if you rerun the command.

If you go to about:support in Firefox it will give you the exact path you need.

**Comment by Rummskartoffel** [comment] 2020-12-28 21:44
This is probably the same problem as #3064, by the way.

**Comment by bovine3dom** [comment] 2020-12-28 21:52
Closing as duplicate of #3064 : )

Feel free to ask for more help here, C0rWin, if `:set profiledir` doesn't work for you.

**Closed by bovine3dom** 2020-12-28 21:52 UTC
Labels: P4, bug

**Comment by C0rWin** [comment] 2020-12-28 22:14
> Feel free to ask for more help here, C0rWin, if `:set profiledir` doesn't work for you.

It's actually worked, thanks for guidance and yes, seems like duplicate. Now, I'm trying to make `:guiset ...` to work as expected. Do I understand correctly there is no support for PDF viewer?

**Comment by bovine3dom** [comment] 2020-12-28 22:19
`guiset` should affect the whole browser. Tridactyl can't run on the PDF viewer but you can press ctrl-, to get back to Tridactyl when you want to. You can track #541 for progress on that if you want.

**Comment by glacambre** [comment] 2020-12-29 06:56
>We're checking whether the profile's entry has Default=1, but Firefox uses the path set under [Install<gobbledygook>]'s Default key as the actual default profile. So we need to check that and not the profiles' own entries to find the default, it seems.

Ah yes, there's an issue for this: https://github.com/tridactyl/tridactyl/issues/1627 .
