### ISSUE TITLE
'go' for quickmarks set in rc file no longer seems to work, but 'gn', 'gw' are fine

### ISSUE THREAD

**Issue by PMarci** [tridactyl/tridactyl#3299] opened 2021-01-30 21:08 UTC
Tridactyl version: 1.20.4pre5167-c772c815
Firefox version: Mozilla Firefox 85.0
Operating system: win
-   Brief description of the problem:
    As described in the title, the `go` shorcut doesn't seem to be created anymore. Typing it activates the shortcut for `:open` everytime.
-   Steps to reproduce:

1. Type `g`
2. Type `o`
3. The commandline appears with `:open` filled in 

-   Tridactyl version (`:version`): 1.20.4pre5167-c772c815

-   Firefox version (Top right menu > Help > About Firefox): 85.0

-   URL of the website the bug happens on: Any and all websites.

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): https://gist.github.com/PMarci/cccb377e05b1c43484106ac86b7829cb

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
sanitise tridactyllocal tridactylsync
" Ctrl-F should use the browser's native 'find' functionality.
unbind <C-f>

set hintfiltermode vimperator
set hintchars 5432167890
colors dark
set modeindicatorshowkeys true

" But also support Tridactyl search too.
bind / fillcmdline find
bind ? fillcmdline find -?
bind n findnext 1
bind N findnext -1
set incsearch true

" Ctrl C for copying in the command line
unbind --mode=ex <C-c>

" x as prev tab, unbind default
bind --mode=normal x tab #
unbind --mode=normal <C-6>
unbind --mode=normal <C-^>

" Hint only titles and menu options on yt
bindurl youtube.com/feed f hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)
bindurl youtube.com/feed F hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)
bindurl youtube.com/channel f hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)
bindurl youtube.com/channel F hint -Jc .yt-simple-endpoint:not(.ytd-thumbnail)

unbindurl youtube.com/watch --mode=normal f
unbindurl youtube.com/watch --mode=normal F
unbindurl escapistmagazine.com/v2/20 --mode=normal f
unbindurl escapistmagazine.com/v2/20 --mode=normal F

quickmark h youtube.com/feed/history
quickmark y youtube.com/feed/subscriptions
quickmark s github.com/synoa
quickmark z escapistmagazine.com/v2/series/zero-punctuation/
quickmark t github.com/tridactyl/tridactyl

set searchengine duckduckgo

```

From the config it seems that no `go<letter>` nmaps are created for the `quickmark` commands in the rc file. If I change the quickmark letter to something else, and `:source` the file, `gn<new letter>` and `gw<new letter>` work, so it seems the file is sourced properly.
Manually inputting `:quickmark <letter>` on the desired URL does seem to generate these nmap entries though.

**Comment by bovine3dom** [comment] 2021-01-30 21:39
https://github.com/tridactyl/tridactyl/blob/c772c815652e557aac47b95b77f8e08b8cdae463/src/excmds.ts#L4019

I managed to reproduce this once and then never again.

It must just be a race condition in the storage - so it would be fixed by #2368.

I've added a sleep between the binds which might fix it for you.

**Comment by PMarci** [comment] 2021-01-30 21:49
As always, thanks for the quick response. Now that I think about it, I might have managed to _not_ reproduce it in the past few days a couple of times, on a different laptop. It was only today that it seemed to never work.

**Comment by bovine3dom** [comment] 2021-01-30 21:54
You're welcome : )

> sanitise tridactyllocal tridactylsync

I strongly recommend you don't do this in your RC file because it in itself can cause problems - see #1409

**Comment by Rummskartoffel** [comment] 2021-01-30 21:57
I think this should go in the backlog for "deserves a more robust implementation", since there's still the possibility of this racing in spite of the sleeps. Maybe we could repurpose `:gobble` for this?

**Comment by bovine3dom** [comment] 2021-01-30 22:00
The race condition is in `:set`, I think. #1409 is a horrible issue. I started writing a replacement for it a while ago - https://github.com/tridactyl/webext-storage-buffer - but I can't remember why I stopped.

I don't understand what you mean by `gobble`. `M` is already bound to using it to make a quickmark by default

**Comment by Rummskartoffel** [comment] 2021-01-30 22:58
Well, currently `:quickmark g google.com` effectively runs `:bind gog open google.com` for you (and the other two). What I'm thinking of would instead run something along the lines of `:set quickmarks.<key> google.com`, with the default bind `go` putting you into gobble mode for one character and feeding that into, say, `:openquickmark`. In addition to the race condition problem – which, you're right, isn't `:quickmark`'s fault –, this would make it easier to delete quickmarks (`:unset quickmarks.<key>`), which – unless I'm missing something – you currently have to do by manually unbinding the three binds it generates.

**Comment by bovine3dom** [comment] 2021-01-31 08:57
Hmm, I hadn't thought of that. The difficulty in removing quickmarks is frustrating.

The main thing I'd be worried about with that is migration - we'd have to look at all `g{o,w,t}.` binds and try to turn them into quickmarks (because the new `g{o,w,t}` binds would shadow them). If anyone has made their own `g{o,w,t}.` bind for something else (admittedly unlikely?) we'd shadow it.

I don't think those problems are insurmountable but we should think about it carefully : )

**Comment by PMarci** [comment] 2021-02-05 00:07
Issue seems to be gone now on both machines. I hope this is due to the update and not me imagining things...

**Closed** 2023-06-07 17:07 UTC
Labels: bug, P3
