### ISSUE TITLE
Completely disable tridactyl for a domain

### ISSUE THREAD

**Issue by ddevault** [tridactyl/tridactyl#3718] opened 2021-05-27 17:01 UTC
Hi! I would like an option stronger than blacklist which will cause tridactyl to not touch a page at all, rather than automatically setting ignore mode. For web development, having all of tridactyl's bits added to the page is a serious nuisance.

**Comment by bovine3dom** [comment] 2021-05-27 17:15
Hey, thanks for filing this issue. I opened https://github.com/tridactyl/tridactyl/pull/3497 recently which would go some way to solving it. I think I just need to review it more carefully.

As far as I can tell, there's no easy way of preventing Tridactyl's CSS from loading into each page, but Mozilla is considering making it so that add-ons can be disabled in containers - https://docs.google.com/document/d/1EK6cTRTY2TmKHzj7aLFcqmH2wg7FVFeq9ATzmnSklE4/edit - although that could be a while off.

This issue is probably a duplicate of #822 unless there's some subtlety that I've missed :)

**Comment by ddevault** [comment] 2021-05-27 17:18
Hm, no, not a dupe of #822. A global toggle would be nice, but I want to have a configurable setting where I can say, for example, to never enable tridactyl on localhost:*.

**Comment by bovine3dom** [comment] 2021-05-27 17:24
I guess then it's a duplicate of #2004 which I closed as a duplicate of #822. I could be persuaded to reopen it 

With #3497 you'd do `seturl [RegEx] disable true` (disclaimer: I might change the setting name because I don't like it)

**Comment by bovine3dom** [comment] 2021-07-20 14:55
`:seturl [regex] superignore true` in the latest betas (`1.21.1pre5969-2c72ca85` onwards) prevents almost all of Tridactyl from being loaded into pages matching the regex. It seems also to prevent our CSS from being loaded, which I wasn't expecting.

NB: the help text for the setting is broken in the current betas. It's fixed on `master` so it'll appear in the betas whenever I next make a release.

**Closed by bovine3dom** 2021-07-20 14:55 UTC
