### ISSUE TITLE
Is there any way to blacklist sites in the .tridactylrc file?

### ISSUE THREAD

**Issue by fncll** [tridactyl/tridactyl#2621] opened 2020-07-15 03:16 UTC
Tridactyl version: 1.19.1pre4273-640c942
Firefox version: Mozilla Firefox 78.0.2
Operating system: mac

*   Brief description of the problem:

Neither of the syntaxes I know of for blacklisting sites from the .tridactylrc file work. I have tried both of the following:

```
autocmd DocStart mail.google.com mode ignore
blacklistadd calendar.google.com
```

Blacklisting from the command line inside Firefox works, but this is tedious since I work from multiple different changing machines.

*   Steps to reproduce:

Add either of the above lines to .tridactylrc. Reload or restart (I've tried both) in Gmail. No effect.

*   URL of the website the bug happens on:

https://mail.google.com/mail/u/0/#inbox

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/fncll/7c4a29c207f831ce7bd397ff19f06ce1

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
" -*- vimrc-generic -*-

" Don't run on Google Mail (old syntax?)

" autocmd DocStart mail.google.com mode ignore

blacklistadd mail.google.com

quickmark g https://mail.google.com/mail/u/0/#inbox
set hintnames numeric
```

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:
*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

Not sure what this means, but here is my path:

```
/usr/bin:/bin:/usr/sbin:/sbin 
```

**Comment by bovine3dom** [comment] 2020-07-15 07:07
Could be a duplicate of #1409. What happens if you run `:source` manually? Do the other lines in your RC file work?

**Comment by fncll** [comment] 2020-07-15 13:42
I must have accidentally removed that note, but yes, other commands work there (which is why I left the `set hintnames numeric` in my example/current .trydactylrc ... that works)

The file does work if sourced manually.

**Comment by bovine3dom** [comment] 2020-07-15 14:30
Going to close as a duplicate of #1409 then, I don't see anything special about blacklistadd that sets it apart from that issue :)

Thanks for reporting it!

**Closed by bovine3dom** 2020-07-15 14:30 UTC
