### ISSUE TITLE
Hint mode mixes 1 and 2-letter shortcuts on certain websites

### ISSUE THREAD

**Issue by magnus-ISU** [tridactyl/tridactyl#3222] opened 2021-01-14 02:35 UTC
Tridactyl version: 1.20.4
Firefox version: Waterfox Ltd. Waterfox 78.6.0
Operating system: linux

What the title says. It happens most notably on youtube.com, where there are about 7 or 8 single-letter shortcuts (including the search bar, which has been annoying) and then everything else works normally. This behaviour does not seem to exist almost anywhere else, which leads me to believe it is some bug in how it is parsing the possible input values? Not really sure, but I couldn't find an issue for this so I figure I should at least ask

EDIT: though this inspired me to create a keybinding `fillcmdline_notrail open www.youtube.com/results?search_query=` so maybe this is a feature, not a bug?

**Comment by bovine3dom** [comment] 2021-01-14 07:29
Closing as probably a duplicate of #2935.

The bind you added could have just been `fillcmdline open youtube` as we already have a search engine for it in Tridactyl : )

https://github.com/tridactyl/tridactyl/blob/1522f0900cabfd8d95dfa223231772fee61938b7/src/lib/config.ts#L657

**Closed by bovine3dom** 2021-01-14 07:29 UTC
