### ISSUE TITLE
Bookmark keyword search

### ISSUE THREAD

**Issue by Massimo-B** [tridactyl/tridactyl#4138] opened 2022-03-11 09:59 UTC
Hi,
I'm migrating from Pentadactyl/Palemoon back to Tridactyl/Firefox.
I have many old bookmarks imported from Palemoon using keyword search such as:

http://www.discogs.com/search?q=%s&type=all
with Keyword="do".

Doing a "do foobar" works in the Firefox command line. But ':winopen do foobar' is pasting the whole string to default search engine google. How can I change that? It was working like that in Pentadactyl.

**Comment by bovine3dom** [comment] 2022-03-11 10:10
Closing as duplicate of #73

TL;DR: Mozilla considers bookmark keywords legacy and won't support them in WebExtensions (and therefore Tridactyl). A workaround is to import them using this user's script: https://github.com/tridactyl/tridactyl/wiki/Import-bookmarks-with-keyword-from-exported-firefox-bookmarks

**Closed by bovine3dom** 2022-03-11 10:10 UTC

**Comment by Massimo-B** [comment] 2022-03-21 09:33
I followed https://github.com/tridactyl/tridactyl#frequently-asked-questions-faq
and did
:set searchurls.do http://www.discogs.com/search?q=%s&type=all

That works. Is that a Tridactyl-only feature? It also works from Firefox address bar, however I can't see that new search engine in the Firefox preferences.
That set searchurls is a big one-line string? Where is it stored? I can't find it in .tridactylrc nor in about:config.

**Comment by bovine3dom** [comment] 2022-03-30 14:12
> Is that a Tridactyl-only feature?

Yes

> It also works from Firefox address bar

It is not working due to Tridactyl unless you're using the `tri` prefix to run Tridactyl commands

> That set searchurls is a big one-line string? Where is it stored? I can't find it in .tridactylrc nor in about:config.

`:viewconfig searchurls`

It is stored in the Firefox storage. `tridactylrc`s are read only unless you force a write to them with `:mkt!` :)

**Comment by Massimo-B** [comment] 2022-03-31 08:51
> :viewconfig searchurls

This is a read-only view of the settings? The JSON model is better to read compared to the 1-line JSON string.
How can I edit the settings in that view? There is a Save button, but I can't edit the lines.

There are some default searchurls which I like to remove.

> It is stored in the Firefox storage - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage. `tridactylrc`s are read only unless you force a write to them with `:mkt!` :)

Doing so, I got my ~/.tridactylrc overwritten. When starting FF how are Tridactyl settings applied? First from API storage, then from ~/.tridactylrc? The rc file would overwrite the storage settings?

**Comment by bovine3dom** [comment] 2022-03-31 10:40
It is read only, you can't edit them there.

Use `:setnull searchurls.[the one you want to remove]` to remove one

Settings are always read from Firefox storage. The RC file is just a set of commands that are run at startup, it is exactly the same as running the commands yourself. Things that change settings will write to the Firefox storage, so yes the RC file overwrites the storage.

**Comment by Massimo-B** [comment] 2022-04-01 05:43
That means, any setting in the RC are going to the storage anyway?
Does that apply to anything done in the RC file like key bindings?

Is there any reason to do a :mkt! for exporting the complete set of configuration to the file and reading that at startup? First I thought it's a good idea in order to have a better view and maintenance of the configuration, but if they are pushed to the storage anyway on reading the RC this is kind of duplication and double setting of each setting, no?

**Comment by bovine3dom** [comment] 2022-04-01 20:39
> That means, any setting in the RC are going to the storage anyway?

Yes

> Does that apply to anything done in the RC file like key bindings?

Yes :)

> Is there any reason to do a :mkt! for exporting the complete set of configuration to the file and reading that at startup? 

This is slightly terrifying to me because you'll be writing to the file while you're trying to read from it

I would not recommend trying to do it at all. You could conceivably instead rebind ZZ so that it ran `mkt!` just before quitting Firefox.

**Comment by Massimo-B** [comment] 2022-04-04 10:01
This is a misunderstanding. I'm not going to do any automatic `:mkt!` at startup nor shutdown. The question was, what is the reason to have a RC file at all, if all the commands there are stored into the storage anyway?

**Comment by Massimo-B** [comment] 2022-04-19 10:14
That is exactly the reason why I prefer the RC file.
But as far as I understand, having an RC file means it's read every startup, settings are applied and also stored to the storage again every time, which actually doesn't hurt but it kind of double storing every startup.
In my opinion I would not store every :set to the storage when read from RC file. Or providing an option to disable storage completely for a user deciding to work with RC file only.

Then for working with the Firefox storage (which has the advantage of using Firefox-sync over devices), I would make :viewconfig being able to edit and change, not only view.

**Comment by Massimo-B** [comment] 2022-06-10 14:11
It's still a bit confusing where settings are stored. Is there any way to disable the internal settings store and only using the RC file which is then readable and version-maintainable? As far as I understand, having a RC file with the same settings only applies all settings twice.

**Comment by bovine3dom** [comment] 2022-06-10 14:20
It isn't possible to disable the internal settings storage. You could potentially circumvent it with `:bind ZZ composite sanitise tridactyllocal ; qall` which would wipe your settings every time you quit with ZZ.

Yeah, having an RC with the same settings is a bit pointless unless you want to store it under version control or share it between machines without using Firefox sync. RC files don't have to be used just for settings though - I use mine to intercept and rewrite headers https://github.com/tridactyl/tridactyl/blob/623b05ba976f88c47323599fa747fbd231e0d636/.tridactylrc#L144
