### ISSUE TITLE
C-[ doesn't escape hint mode and breaks hints

### ISSUE THREAD

**Issue by vanzef** [tridactyl/tridactyl#968] opened 2018-09-03 09:54 UTC
*   Brief description of the problem:

I believe that `<C-[>` should work as `<Escape>` key with hints since it works that way in vim, but it seems to be broken: pressing `<C-[>` in "follow hint mode" (`f` by default) goes backwards in history and if you go forward (e.g. with `L`) hints will be visible but not active.

*   Steps to reproduce:

    1. Go to any site  
    2. Follow any link on the site
    3.  Invoke "follow hint mode" (`f` by default)
    4. Press `<C-[>` to exit hint mode  
    5. Go forward in history (since you would be sent back)
    6. Hints are visible, but not active. You can even scroll the page

*   Tridactyl version (`:version`):
  1.13.3-1.13.3
*   Firefox version (Top right menu > Help > About Firefox):
  Mozilla Firefox 60.1.0 (ESR)                                                                                                                                            
*   URL of the website the bug happens on:
  Any, definitely reproducible on HN: https://news.ycombinator.org

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):
  https://gist.github.com/vanzef/ebed49be44149285f5079232b87decfd

P.S. `<Escape>` works correctly in such use case.

**Comment by bovine3dom** [comment] 2018-09-03 10:51
It's simply not bound yet. It isn't bound in command mode either. Related: #304 - I wanted to fix that before I added any more hard-coded binds.

**Comment by vanzef** [comment] 2018-09-03 12:11
I see, somehow I've decided that `nmap` bindings will work in hint mode.

However, is this behavior intended? I mean keeping hints visible, but not active.

**Comment by bovine3dom** [comment] 2018-09-03 12:51
Ah. No, that's a bug. Thanks for reporting : )

**Comment by saulrh** [comment] 2018-09-07 08:47
This probably has a similar root cause as #988 (page state is saved, including our changes to the classes and possibly the hint elements as well, but tridactyl's content script is reinited and leaves the changes dangling) but with a different route (browser does the snapshotting to make history navigation faster, tridactyl doesn't have a chance to clean up after itself when navigation happens). I doubt that it'll be fixed by that patch. Maybe an `onBeforeUnload` in hinting?

**Comment by bovine3dom** [comment] 2019-05-27 12:03
Can't reproduce. Closing in favour of #304.

**Closed by bovine3dom** 2019-05-27 12:03 UTC
Labels: P4, enhancement

**Comment by bovine3dom** [comment] 2019-05-28 12:15
Hint-mode binds added in latest betas - just do `bind --mode=hint <C-[> hint.reset` :)
