### ISSUE TITLE
Command to manually move tab to container or window

### ISSUE THREAD

**Issue by notJerl** [tridactyl/tridactyl#985] opened 2018-09-06 16:25 UTC
In Vimperator, if you had the Tab Groups extension installed, you could manually move a tab to a specific tab group using this command:

``:tabgroups pushtab``

to enable changing a tab's group using the keyboard.  I had a key combination bound to fill the command line with that so I could quickly type a number and have it moved.

The original Tab Groups extension is dead, and implementing compatibility with all the WebExtensions implementations that have come up would probably be exhausting, but there's a better way: most of the WebExtensions implementations of tab groups support automatically putting tabs in a particular container into a particular group.

For many users, autocontainer would do a good enough job.  However, I use pages from the same domain across multiple groups, so autocontainer wouldn't be helpful in this case.  A command to manually push a tab into a container, say ``containerpush`` (to match Vimperator) or ``containerattach`` (to be congruent with ``tabdetach``) would be useful.

Similarly, Vimperator allowed you to manually move a tab to a specific window using the ``tabattach`` command.  I actually didn't realize Tridactyl didn't have this until I started writing this request, but this would definitely be helpful for people who use multiple windows, e.g. for people who have separate Firefox windows open across multiple monitors.  I also had a key combination bound to this to quickly send a tab to a different window.

**Comment by bovine3dom** [comment] 2018-09-06 16:32
You can kinda do this with `T` which fills the command line with tabopen current_url. Then just add -c your container.

If you're feeling brave you could try `js tri.controller.acceptExCmd("tabopen -c YourContainer " + document.location.href")` or some thing along those lines.

**Comment by notJerl** [comment] 2018-09-06 17:16
I guess that kinda works, but with Vimperator it listed out the available groups to send the tab to, so I could just hit the key combo and tab a couple times and it was done rather than having to type out the container name each time.  I have too many tab groups to reasonably assign each of them a unique binding.

**Comment by bovine3dom** [comment] 2018-09-06 18:41
I agree. We want this kind of functionality but it's a bit useless without auto-completions, and we're holding off on those until we get #932 done.

**Comment by glacambre** [comment] 2019-02-14 06:43
Related issue: #404

**Comment by antonva** [comment] 2019-02-17 12:22
It's worth noting that the concept of 'moving' a tab to a container is impossible. You can only really close a tab and open a new one in a container pointing to the same url. The tab state (history) will be obliterated and other state such as logins or other cookies won't be passed around. 

If this is not an issue 'moving' a tab to a container isn't really a problem. We even had a command for it at one point iirc.

**Comment by nfvs** [comment] 2019-02-19 09:26
To open a link in a new tab in a different container:
```
bind ;Fp composite hint -pipe a href | tabopen -c Personal
```

**Comment by bovine3dom** [comment] 2020-06-27 12:37
`:recontain` added in e935477c03c1f40378bfe11b85d6a5ed1dfe4cd2 handles container switching.

Closing as "move tab to window" is a duplicate of #2398 and will be fixed in #2540.

**Closed by bovine3dom** 2020-06-27 12:37 UTC
Labels: P4, blocked, enhancement
