### ISSUE TITLE
First couple of keypresses are lost after opening a new tab

### ISSUE THREAD

**Issue by brechtm** [tridactyl/tridactyl#2977] opened 2020-11-05 09:14 UTC
Lately I am noticing some annoying behavior in Firefox that I believe is due to Tridactyl. Steps to reproduce:
1. open a new tab using the keyboard shortcut Cmd-Tab
2. immediately after start typing in a search term or URL

Typically the first or first two characters are removed from the address bar input. This may be because Tridactyl is only loaded after I've managed to input those characters, at which point clears the address bar.

I'm pretty sure I didn't have this issue before, but that must have been over 1-2 months ago.

Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 82.0.2
Operating system: mac

**Comment by bovine3dom** [comment] 2020-11-05 09:25
Closing as duplicate of #2840. We think this is a Firefox bug introduced in FF80/81.

We can't really do anything about it other than ask you to vote on the bugzilla issue linked in that thread or suggest you use the no-new-tab builds also linked in that thread.

Sorry about this - I imagine it's very frustrating : )

**Closed by bovine3dom** 2020-11-05 09:25 UTC

**Comment by brechtm** [comment] 2020-11-05 09:47
Thanks. I didn't find that issue.

I'll start making a habit of using the _S_ shortcut then :-)
