### ISSUE TITLE
Always show status bar

### ISSUE THREAD

**Issue by bepo-keyboard** [tridactyl/tridactyl#4157] opened 2022-03-26 16:40 UTC
So, I alredy saw [this issue](https://github.com/tridactyl/tridactyl/issues/210) but it became a little bit old now, and the code suggested is not working in current versions of Firefox (I am using 91.6).

So, is their a way to make the statusbar persistant? It’s usefull to see current url, if the url is booked or not, etc.

**Comment by award0707** [comment] 2024-06-19 18:26
I wonder this too. Tridactyl has a sort of statusline, but it shows only the current mode (insert, hint, normal, etc.)
To make an analogy, I don't know many Vim users who don't keep the current filename persistent in the statusline. Surely, keeping the web equivalent (the current URL, or at least the domain) persistent is not outside the scope of the project.

**Comment by bovine3dom** [comment] 2024-06-20 09:14
This issue flew under my radar but I think it's an exact duplicate of #210 so I'll close it in favour of that.

@award0707 currently there aren't many settings for it. I would be happy to expose it so that people can add whatever code they want to it. #210 is still something I personally want, but it's a very low priority for me.

**Closed by bovine3dom** 2024-06-20 09:14 UTC
