### ISSUE TITLE
Option to disable any hijacking of new tabs

### ISSUE THREAD

**Issue by skrat** [tridactyl/tridactyl#2933] opened 2020-10-21 17:55 UTC
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 81.0.2
Operating system: linux

*   Brief description of the problem:

I want to disable tridactyl from messing in any way with the new tab. I want to open a new tab with FF shortcut (C-T) and immediately start typing address. Tridactyl is preventing me from doing this, even when set newtab=about:blank. I start typing, then tridactyl hijacks the new tab, erases anything I typed into the address bar.

**Comment by bovine3dom** [comment] 2020-10-21 20:11
Duplicate of #2840 - as I said there I'm not convinced this is our fault. Probably a Mozilla bug.

If you can do without the new tab page at all, we offer builds without it - see readme.md on this repository for a link.

**Closed by bovine3dom** 2020-10-21 20:11 UTC
