### ISSUE TITLE
Temporary disable tridactyl on a page

### ISSUE THREAD

**Issue by zevv** [tridactyl/tridactyl#339] opened 2018-03-11 14:01 UTC
While debugging my web app the JS console is cluttered by tridactyl output and firefox CSS warnings. It would be nice if I would be able to temporary disable tridactyl for a given page without having to go through the firefox menus to disable the extension.

**Comment by IsaacKhor** [comment] 2018-03-12 04:15
What warnings and errors are you getting? On default logging settings, there should only be the aucmds, the `tridactyl content script loaded`, and something from config. CSP errors if the site has one of those. Please report if there are additional errors.

That being said, implementing a switch to temporarily disable on current page shouldn't be too hard; however, knowing when to re-enable will require some tricky logic. I can add a master toggle to the settings page I'm working on (#314), which can be accessed through `:settings`, so you can toggle a checkbox on the page when you need to temporarily disable loading the content script.

**Comment by zevv** [comment] 2018-03-12 06:48
Quoting Isaac Khor (2018-03-12 05:15:44)
> What warnings and errors are you getting? On default logging settings,
> there should only be the aucmds, the `tridactyl content script
> loaded`, and something from config. CSP errors if the site has one of
> those. Please report if there are additional errors.

Verbatim copy of the debug console, all other extensions disabled:

```
GET http://127.0.0.1/ [HTTP/1.1 304 Not Modified 0ms]
AUCMDS TRIED TO RUN content.js:2817:5
Tridactyl content script loaded, boss!  content.js:3466:1
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.  127.0.0.1 Object { "addons.mozilla.org": "mode ignore" } content.js:2820:5
Error in parsing value for ‘outline’.  Declaration dropped.  cleanslate.css:65:13
Unknown property ‘-moz-background-size’.  Declaration dropped.  cleanslate.css:93:29
Unknown property ‘-moz-border-radius’.  Declaration dropped.  cleanslate.css:100:27
Unknown property ‘-moz-column-span’.  Declaration dropped.  cleanslate.css:117:25
Unknown property ‘column-span’.  Declaration dropped.  cleanslate.css:118:25
Unknown property ‘s ’.  Declaration dropped.  cleanslate.css:266:1
Error in parsing value for ‘background’.  Declaration dropped.  cleanslate.css:289:17
Error in parsing value for ‘background’.  Declaration dropped.  cleanslate.css:290:17
Expected ‘none’, URL, or filter function but found ‘progid’.  Error in parsing value for ‘filter’.  Declaration dropped.  cleanslate.css:292:13
Unknown property ‘-moz-box-shadow’.  Declaration dropped.  cleanslate.css:294:24
Error in parsing value for ‘outline’.  Declaration dropped.  cleanslate.css:328:22
Error in parsing value for ‘outline’.  Declaration dropped.  cleanslate.css:342:14
Error in parsing value for ‘background’.  Declaration dropped.  cleanslate.css:352:17
Error in parsing value for ‘background’.  Declaration dropped.  cleanslate.css:353:17
Error in parsing value for ‘border-bottom’.  Declaration dropped.  commandline.css:97:29
TypeError: can't convert undefined to object config.ts:302:34
```

> That being said, implementing a switch to temporarily disable on
> current page shouldn't be too hard; however, knowing when to re-enable
> will require some tricky logic.

Maybe something as simple as switching tabs would do?

> I can add a master toggle to the settings page I'm working on (#314),
> which can be accessed through `:settings`, so you can toggle a
> checkbox on the page when you need to temporarily disable loading the
> content script.

That would be nice. Are these settings also available through tridactyl
commands so I can map this to a key?

--
:wq
^X^Cy^K^X^C^C^C^C

**Comment by lazysoundsystem** [comment] 2018-03-12 08:22
Can I suggest removing all tridactyl entries in the JS console by default (where possible), with perhaps a 'debug' mode that shows them?

I should be used to them already, but still get distracted while using the console to debug javascript in other pages.

**Comment by cmcaine** [comment] 2018-03-12 08:36
That's reasonable. We moved most logging to another system, but a few bits
stayed on console.log

**Comment by glacambre** [comment] 2018-06-08 12:52
The majority of these errors seem to be caused by cleanslate.css. I don't know what we can do besides forking cleanslate and removing bad rules ourselves.

@cmcaine I remember you mentioning that you wouldn't have bothered adding an npm dependency for cleanslate and would instead have directly copied the file to Tridactyl's `static` repository. Should I do that?

**Comment by seltzy** [comment] 2018-07-25 15:22
I would also like to be able to temporarily disable it via a binding, but for me it's doing HTML5 game development. Tridactyl makes testing/playing impossible since pressing keys like Space or WASD could control the page unintentionally and steals input from the game. Having something like `:disable` seems pretty essential for those cases. VimFx had something like that built in, where you could either disable for only the next input or disable until you press a key-combo to indicate otherwise.

**Comment by glacambre** [comment] 2018-07-25 15:41
@seltzy: Have you tried `:mode ignore`?

**Comment by seltzy** [comment] 2018-07-25 15:49
@glacambre I did not know that was a thing. `ignore` is not the word I'd expect it to be called. I see now that it's right on the help page under highlighted features, but there's so much content to sift through that I usually just `/` and type what I think something would be called, which was originally `disable` in my mind. Thanks for the tip!

**Comment by bovine3dom** [comment] 2018-07-25 15:54
@seltzy You should read through `tutor` if you find the time. It's much more user-friendly than the help page for finding things you aren't expecting to find.

To me, `disable` suggests a more permanent thing, which is what this issue is for. `ignore` describes it better: Tridactyl is still running on the page, it just isn't listening to you.

**Comment by seltzy** [comment] 2018-07-25 16:09
@bovine3dom I see that now. I agree that disable sounds more permanent in this context. Maybe `:tutor` could be more obvious at the top of `:help` as a kind reminder of what you've just pointed out to me. I'm sure I went through the tutorial before, but that was some time ago. I haven't needed `ignore` mode until recently, so I must have forgotten it. As an advanced user in command prompts my instinct is always to go to `--help`, so it seemed natural to use `:help` as the one reference to rule them all. I guess my assumption was that the content of `:tutor` would be at the top of `:help`. I also think my perception may have been skewed as `ignore` seems like it would be a relatively niche feature for most users, so I'm not sure I'd have thought to look in `:tutor` even if I'd remembered it existed for such things.

I can open a new issue if you think any of those thoughts are worth exploring further as a usability concern.

**Comment by bovine3dom** [comment] 2018-07-25 16:15
> I also think my perception may have been skewed as ignore seems like it would be a relatively niche feature for most users

I wish. Tridactyl breaks too many sites / too many sites break Tridactyl for that to be true.

The `tutor` page pops up the first time you install Tridactyl, but I'd be happy to add a link to the top of help.

Please do open another issue if you have any thoughts. There's already #710 for improvements to tutor.

It's sometimes hard to know what is obvious or not when you've been using add-ons like this for as long as we have...

**Comment by bovine3dom** [comment] 2018-07-25 16:21
Link to tutor added to help in 5e7b1db. Thanks : )

**Comment by glacambre** [comment] 2018-07-25 16:48
We could perhaps add a small sentence like "this is the closest thing to a 'disable' command available for now" or "this temporarily disables Tridactyl on a page" to the `mode ignore` help example to help people looking for the word 'disable' find it?

**Comment by seltzy** [comment] 2018-07-25 17:01
@glacambre The latter would have helped a lot in my case, even if it's not *technically* true to say "disable" given the way it is defined here. Then again, help pages are written for humans, so using the term "disable" a bit more loosely there doesn't seem inappropriate for the sake of helping people find the feature they're looking for.

**Comment by glacambre** [comment] 2019-02-14 07:00
Not seeing error messages in the console anymore and "disable" has been added to a few places in the help pages so I'm closing this. Let me know if there's something left unaddressed in this issue.

**Closed by glacambre** 2019-02-14 07:00 UTC

**Comment by Hahlh** [comment] 2021-03-20 08:30
Is there a better way to completely disable Tridactyl on specific pages? (e.g. localhost)

Blacklisting a site still adds a lot and I find myself having to deactivate the extension manually for web development constantly.

The one thing is the css that is still being introduced and is cluttering my devtools:
https://user-images.githubusercontent.com/45669613/111863949-b1ed9280-895e-11eb-953f-b75faf015867.mp4



 The other thing is the indicator that still changes the html on a page. 

An example:
![image](https://user-images.githubusercontent.com/45669613/111862922-a0a18780-8958-11eb-9713-12573efbdcf4.png)



Having Tridactyl enabled prevents having a clean slate and I can not fully trust my environment.
Or is there something that I am missing?

A first workaround for the indicator changing the html could be to alter the gui settings, correct?

This is quite an old issue. If preferred, I can open up a new one.

**Comment by bovine3dom** [comment] 2021-03-20 11:18
#822 is closer to what you're asking for : )

**Comment by bovine3dom** [comment] 2021-03-20 11:24
@Hahlh  `:seturl ^https?://localhost modeindicator false` will get rid of the mode indicator at least.

**Comment by Hahlh** [comment] 2021-03-20 11:46
@bovine3dom 
Thank you for the super fast input!

I will subscribe to the issue you mentioned as see how things develop.
