### ISSUE TITLE
Invidious Question -- Re: Picture-In-Picture Button Selection

### ISSUE THREAD

**Issue by daffydock** [tridactyl/tridactyl#5032] opened 2024-08-19 21:00 UTC
Hi, 

Maybe I just have to enable an option but I am not sure what exactly I have to do. I just want to ascertain if it can be done or not. I would assume that it can be done and that I am unaware as to what to activate. Maybe others may have the same issue. 

I have noticed, while using Invidious --a front-end for Youtube-- that pressing `F` does not highlight the small button on the middle-right hand side of the video meant to activate the PiP pop up. It simply does not even show it. However, a mouse hover will show the button, and a left click on it, would activate it. 

I tested Vimium C before and noticed that on using the same `F` functionality out-of-the-box, with no other settings changed, that the PiP is tagged/highlighted for selection and was wondering if the same could be achieved with Tridactyl. 

For reference, here is a link on an Invidious instance where `F` works fine, except for the PiP button. You need to use to mouse and hover over the area to see it.  

https://yewtu.be/watch?v=kIjmsgBPbC8

Here is another instance of the same video, same issue.

https://iv.melmac.space/watch?v=kIjmsgBPbC8

**Comment by bovine3dom** [comment] 2024-08-29 10:38
Thanks for filing this issue. It's a long standing issue with Tridactyl - see #412.

I think it might be the kind of thing that's easiest to fix when rewriting Tridactyl for manifest v3 which we'll be forced to do in the next 2-3 years, so not soon :)

As workaround you might find that there is a javascript command you can invoke to trigger full screen/PiP for invidious if you do enough digging around in the inspector/console.

Closing as duplicate of #412

**Closed by bovine3dom** 2024-08-29 10:38 UTC
