### ISSUE TITLE
too many hints

### ISSUE THREAD

**Issue by nobodyatandnothing** [tridactyl/tridactyl#4056] opened 2022-01-05 15:00 UTC
f shows more hints than necessary.
downsides:
1. many hints that would be 1 key are 2 keys
2. sometimes hints are pushed to the wrong place / it is confusing to find the hint you want
3. sometimes groups of hints cover elements

**Comment by bovine3dom** [comment] 2022-01-10 15:07
Closing as duplicate of #367

I agree with your assessment of all the problems that it causes :)

**Closed by bovine3dom** 2022-01-10 15:07 UTC
