### ISSUE TITLE
Tridactyl not working with a website on Firefox

### ISSUE THREAD

**Issue by wisdomlight** [tridactyl/tridactyl#3032] opened 2020-11-26 19:45 UTC
*   Brief description of the problem:
Looks like Tridactyl prevents access to this typing game
When disabling both my Tridactyl Beta and normal Tridactyl - the game works

*   Tridactyl version (`:version`):1.20.2

*   Firefox version 83.0 64 bit

*   URL of the website the bug happens on:
https://zty.pe/

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere likf
I didn't paste the url as it is very very very very very very long

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):
they don't exist
```
Insert tridactylrc contents between the backticks
```

*   Operating system: Linux Debian Bullsey With GNOME 38.1.0

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl: **not sure what you want me to type here**

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal: 
```
sherab@sherab-librem13v4:~$ printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py
bash: /home/sherab/.local/share/tridactyl/native_main.py: No such file or directory
sherab@sherab-librem13v4:~$ 
```

**Comment by bovine3dom** [comment] 2020-11-26 19:53
Have you tried `seturl ^https://zty\.pe noiframe true`?

If that fixes it this is a dupe of #639 : )

**Comment by wisdomlight** [comment] 2020-11-26 20:29
I typed your suggestion 
:seturl ^https://zty\.pe noiframe true
it did not work
no I cannot even get into the tridactyl comand line on that page. 
hmm

**Comment by bovine3dom** [comment] 2020-11-26 20:48
Sorry, you need to type the seturl command on a different page where Tridactyl works and then refresh the ztype page.

`noiframe` will mean that you can't use the command line on that page (and it was broken anyway) but it should let you play the game, provided you put Tridactyl in ignore mode.

**Comment by wisdomlight** [comment] 2020-11-26 20:53
Thanks for speedy reply.
It seems to work only for the first typed letter - then it stops.
hmm strange.

**Comment by bovine3dom** [comment] 2020-11-26 21:04
Shift-Insert puts you in ignore mode.

**Comment by wisdomlight** [comment] 2020-11-26 21:22
> Shift-Insert puts you in ignore mode.
many thanks
it works now.

**Comment by bovine3dom** [comment] 2020-11-26 21:35
If you visit the site a lot you can do `:blacklistadd ^https://zty\.pe` which will put you in ignore mode as soon as the site loads.

Closing this issue as a duplicate of #639 - thanks for reporting it.

**Closed by bovine3dom** 2020-11-26 21:35 UTC
Labels: needs review
