### ISSUE TITLE
No actions on ArsTechnica after clicking in comment section

### ISSUE THREAD

**Issue by littlecoce** [tridactyl/tridactyl#5033] opened 2024-08-23 07:39 UTC
-   Brief description of the problem:
    
    On the Site [ArsTechnica](https://arstechnica.com/) after clicking anywhere in the comment section navigation and site actions aren't working anymore. Reload or `C-;` fixes the problem until next click in comment section.  
 
-   Steps to reproduce:

    Visit an article on the site and click somewhere in the comment section

-   Tridactyl version (`:version`):
    
    1.24.1

-   Firefox version (Top right menu > Help > About Firefox):

    127.0 x64

-   URL of the website the bug happens on:

    https://arstechnica.com/

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com):

    https://gist.github.com/littlecoce/4a1781391921a555fabbf1235d260a4e
    (searchurls and autocontain removed for privacy reasons)

**Comment by bovine3dom** [comment] 2024-08-29 10:39
Probably a duplicate of #122 

Personally I use ctrl+, reflexively when I get stuck on sites like that

**Comment by littlecoce** [comment] 2024-09-06 06:59
Ctrl-, is working fine, just reporting. If this is a dup, should I close?

**Comment by bovine3dom** [comment] 2024-09-06 21:58
I wanted to make sure it really was an iframe first, which I have now done. Closing as a duplicate of #122, thanks for filing it :)

**Closed by bovine3dom** 2024-09-06 21:58 UTC
Labels: site specific, needs review
