### ISSUE TITLE
Texts containing non-Latin-1 characters can't be opened in an external editor on Windows

### ISSUE THREAD

**Issue by clange** [tridactyl/tridactyl#878] opened 2018-07-30 14:03 UTC
*   Brief description of the problem: Texts containing non-Latin-1 characters result in an empty temporary file on Windows; external editor is not opened (related to #876)

*   Steps to reproduce:

    1.  I tested this on Windows with `native_main.bat` and `native_main.exe`.
    2.  I'm using `<C-i>`, i.e., `:editor`, in a text input box, which contains non-Latin-1 characters, e.g., `ш`.
    3.  An empty file `tmp_...` is being created, i.e., its size is 0 bytes.
    4.  The external editor is not started (I tried with several ones).

*   Tridactyl version (`:version`): says `:REPLACE_ME_WITH_THE_VERSION_USING_SED` – the latest non-experimental release of today or yesterday.

*   Firefox version (Top right menu > Help > About Firefox): 60.1.0esr (64-bit Windows)

*   URL of the website the bug happens on: doesn't matter

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): seems irrelevant to me (but will be happy to provide more details) – in particular choosing, via `:set editorcmd`, a different external editor doesn't solve the problem.

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): I think it doesn't contain anything specific to my problem but will be happy to provide more details.

*   Operating system: Windows 10 64-bit 15063.1155

*   Result of running `:! echo $PATH` in tridactyl: (BTW this should be `:! echo %PATH%` on Windows) – really nothing special. Starts with `C:\Program Files\Mozilla Firefox`, contains all directories containing external editor executables (I tried primarily `emacsclientw` but also `gvim` and `notepad`.)

**Comment by nicoroeser** [comment] 2019-03-22 07:47
Does not occur on Linux (even tested with an Unicode emoji character, U+1F600, 😀).

But can easily be triggered on macOS, and is not limited to characters outside _ISO-8859-1_ there. On macOS, I see a behavior that I would describe as “Texts containing non-ASCII characters can't be opened in an external editor on macOS”. I have tested with character U+00F6 (LATIN SMALL LETTER O WITH DIAERESIS, ö). Texts which purely consist of US-ASCII work fine on macOS.

The cause is likely to be a conflict in encodings used/expected by JavaScript code and Python code.

**Comment by bovine3dom** [comment] 2019-03-22 09:25
See #896 if you're interested in helping to fix it :)

**Comment by bovine3dom** [comment] 2021-01-23 12:41
Apparently fixed in native 0.2.0 (currently not recommended for Windows due to a lack of `:restart` support) - https://github.com/tridactyl/native_messenger/issues/16

**Closed by bovine3dom** 2021-01-23 12:41 UTC
Labels: P2, bug, windows
