### ISSUE TITLE
Improper letter combinations in hint mode

### ISSUE THREAD

**Issue by Asocia** [tridactyl/tridactyl#3789] opened 2021-06-20 14:20 UTC
Sometimes when I enter hint mode by pressing "F", links are highlighted with improper letters. In hint mode, if something is highlighted with "KK", there should not be a link with just "K". Here is an example from a random question in StackOverflow.
![image](https://user-images.githubusercontent.com/32161460/122677428-d9b4f680-d1ea-11eb-85e6-41fcd6833559.png)

In the above page, when I wanted to go home page by pressing "K", here is what happens:
![image](https://user-images.githubusercontent.com/32161460/122677520-4c25d680-d1eb-11eb-964f-71e8a173cbaa.png)

I think this is a bug. Sorry if it is reported before but I couldn't find anything similar.

Tridactyl version: 1.21.1pre5849-d28e5f12
Firefox version: 89.0.1

**Comment by bovine3dom** [comment] 2021-06-20 14:25
Could be a duplicate of #2798. 

Thanks for reporting. You should be able to use tab and enter to select the one you want

**Comment by GHolk** [comment] 2022-03-30 15:07
bovine3dom said `:hint -J` will get rid of this bug. I read the code, but can't understand it. According to help page, `-J` will skip clickable javascript action.

**Comment by bovine3dom** [comment] 2022-04-04 18:32
Yeah, `:hint -J` will remove the hints that are there for elements that have JavaScript mouse events on them. Those are the hints in grey. On most pages you don't need them :)

The bug is caused because somehow the JavaScript hints aren't checking to make sure that there aren't any normal hints with the same prefixes.

**Comment by pataquets** [comment] 2022-08-23 16:23
@Asocia still an issue on its own or duplicate? If the latter, please close to help maintainers keeping the issue queue tidy.

**Comment by Asocia** [comment] 2022-08-23 16:29
Yep, this is a duplicate.

**Closed** 2022-08-23 16:29 UTC
Labels: bug, P3

**Comment by pataquets** [comment] 2022-08-23 17:56
Thanks, @Asocia!
