### ISSUE TITLE
Setting 'newtab' to "about:newtab" gives Error: Illegal URL: about:newtab

### ISSUE THREAD

**Issue by prati0100** [tridactyl/tridactyl#2718] opened 2020-08-07 09:12 UTC
Tridactyl version: 1.20.0pre4432-f5670ace
Firefox version: Mozilla Firefox 79.0
Operating system: linux

Hi,

I am running the No new tab beta found from the readme. It has worked fine for a long time but I think a recent update broke it. Now when I do `:tabopen`, I get the following error message:
```
Error: Illegal URL: about:newtab
```

I have set my `newtab` option to `about:newtab`. Unsetting it takes me to the tridactyl newtab page (which shouldn't be there in the first place given I'm using the no new tab xpi).

I don't have much other config apart from a couple of key bindings.

Is there any way I can just go to the Firefox default newtab page?

**Comment by bovine3dom** [comment] 2020-08-07 09:41
"`tabopen` opens Tridactyl new tab" is a duplicate of #1571.

It's very possible that I broke `set newtab about:newtab` in #2698 - I'll have a look. Thanks for reporting : )

**Comment by bovine3dom** [comment] 2020-08-07 11:36
```
ac54cb8149791c40ca2722dd51fa8dc08af32482 is the first bad commit
commit ac54cb8149791c40ca2722dd51fa8dc08af32482
Author: Oliver Blanthorn <freedom4cows@gmail.com>
Date:   Mon Aug 3 13:37:54 2020 +0100

    Ameliorate #2695 while preserving current behaviour

    (I think). I was a big refactor so I probably broke something.

 src/excmds.ts     | 38 +++++++++++++++++++++------------
 src/lib/webext.ts | 64 ++++++++++++++++++++++++-------------------------------
 2 files changed, 52 insertions(+), 50 deletions(-)
```

`git-bisect` should preferentially look at commits which contain the text "I probably broke something"

**Comment by bovine3dom** [comment] 2020-08-07 11:57
AFAICT the new logic is this:

`:tabopen` means we do https://github.com/tridactyl/tridactyl/blob/f5670ace79fb9a15488429be20af1b1bfa6223b8/src/lib/webext.ts#L166

which returns here https://github.com/tridactyl/tridactyl/blob/f5670ace79fb9a15488429be20af1b1bfa6223b8/src/lib/webext.ts#L181 and is used in a bare `tabs.create` call.

---

Previous, working behaviour was

https://github.com/tridactyl/tridactyl/blob/e5d3ca8addefab4a20e38036f1222aa1f5bec013/src/lib/webext.ts#L163

which lead to 

https://github.com/tridactyl/tridactyl/blob/e5d3ca8addefab4a20e38036f1222aa1f5bec013/src/lib/webext.ts#L183

which is just as illegal.

I _think_ the only problem here is that we've stopped silencing the error...

**Closed** 2020-08-07 12:38 UTC
Labels: P3, bug

**Comment by prati0100** [comment] 2020-08-07 12:47
Thanks for the quick fix. Looks like the beta build is not yet updated with this commit, I'll try it out an a couple hours.

**Comment by bovine3dom** [comment] 2020-08-07 12:51
It has just appeared now - https://tridactyl.cmcaine.co.uk/betas/nonewtab/tridactyl_no_new_tab_beta-1.20.0pre4434-an+fx.xpi - :)

**Comment by prati0100** [comment] 2020-08-07 13:05
The new tab now opens correctly. Thanks!
