### ISSUE TITLE
Broken site: regex101.com

### ISSUE THREAD

**Issue by Jab2870** [tridactyl/tridactyl#3919] opened 2021-09-27 09:13 UTC
Tridactyl version: 1.21.1pre6005-83b1f7c7
Firefox version: Mozilla Firefox 93.0

-   Brief description of the problem:

The text fields cannot be edited at the website <https://regex101.com>

-   Steps to reproduce:

1. Go to <https://regex101.com>
2. Try and use the text boxes

-   Tridactyl version (`:version`): 1.21.1pre6005-83b1f7c7

-   Firefox version (Top right menu > Help > About Firefox): Mozilla Firefox 93.0

-   URL of the website the bug happens on: <https://regex101.com>

-   Config (in a new tab, run `:viewconfig --user`, copy the url and paste it somewhere like gist.github.com): I tried with a blank config and still exists

**Comment by bovine3dom** [comment] 2021-09-27 10:51
It works fine for me on FF88 (I haven't updated in a while). FF93 is beta, right? Could you try on FF stable?

**Comment by Jab2870** [comment] 2021-09-27 11:14
It seems to work on FF 92 which is stable.

**Comment by Jab2870** [comment] 2021-09-27 11:15
I need to apologize, apparently my config didn't clear properly when I renamed my tridactylrc file. The issue seems to be that the line 

```vimrc
set allowautofocus false
```

was causing the issues

**Comment by Jab2870** [comment] 2021-09-27 11:44
I'm not sure if this would still be considered an issue? If not, I'm happy to close this.

**Comment by bovine3dom** [comment] 2021-09-27 14:26
I think we document that `set allowautofocus false` breaks some websites on the setting itself and on the troubleshooting guide. If you have any ideas on where else we could mention it I'd be glad to hear them.

For now, closing this as a duplicate of #393

**Closed by bovine3dom** 2021-09-27 14:26 UTC
