### ISSUE TITLE
Tridactyl freeze when Scroll  on top or end of page

### ISSUE THREAD

**Issue by Monirzadeh** [tridactyl/tridactyl#4758] opened 2023-09-01 08:42 UTC
Tridactyl version: 1.23.0
Firefox version: Mozilla Firefox 117.0
Operating system: linux

if you scroll up or down and arrive on top or end of the page and you keep press `j` or `k` a little longer, tridactyl can't get new input for a while.

## Step to repreduce:
1. open a long web page that you can scroll.
2. go to the middle of page
3. scroll up with `k` untill get to the top of page
4. when you arrive to the top of the page keep your finger on `k` a little more for 2 or 3 second.
5. press `j` key to scroll down
6. as you see tridactyl freeze and not get your input and your j affect after 2 or 3 second(it related to how much you keep your finger on k after reach to top of the page)

## What happen?
i think tridactyl  still done k press from for that 2 or 3 second and not cancel them

## Behaves expected
if it is not more accept more key press in top or end of page or it can get other key in that situation with more priority

current behave : `k` --> reach top of page --> more `k` keypress --> (freez until all `k` key press finish than accept new `j` --> scroll down now

what should it be:  `k` --> reach top of page --> more `k` keypress --> accept `j` and scroll down instead of after all `k` (on top of page)

side-note: it is not happen if you change scroll direction in middle of page. while it freezing none of keybinding accepted not just keys related to scroll.

**Comment by bovine3dom** [comment] 2023-09-03 15:35
Thanks for reporting this. I think it's an exact duplicate of #3955 so I'm closing your issue in favour of that :)

**Closed by bovine3dom** 2023-09-03 15:35 UTC
