### ISSUE TITLE
Randomize hints to mitigate overlap

### ISSUE THREAD

**Issue by jamesblau** [tridactyl/tridactyl#1027] opened 2018-09-25 19:16 UTC
Hello!

Sometimes there are a lot of links right next to each other, and the hints overlap. I think it would be nice to have the option to randomize the order of hints, so that after hitting the first character of the desired hint, the overlapping hints are likely to disappear.

**Comment by jamesblau** [comment] 2018-09-25 19:29
Ah, that's a good point.

I still think a hintrandom option would be nice, though. I'm not sure how difficult that would be, or whether it would making drawing the hints less efficient somehow.

Thanks!

**Comment by notJerl** [comment] 2018-09-25 19:39
One thing I forgot to mention above is that with `vimperator` or `vimperator-reflow`, you can hide all the unrelated hints by typing the first letter of the *link* (not the hint) you want to follow.

**Comment by bovine3dom** [comment] 2018-09-26 09:37
I think we already have an issue open for this or something similar. #367 is tangentially related. VimFx let you cycle the order of hints and people have asked for that.

**Comment by braham-snyder** [comment] 2019-02-09 17:49
Randomization could help, but that alone wouldn't handle full overlaps, where you cannot see even the first hint character of hidden hints.

I think z-index rotating, VimFX-style, might be the way to go. It's relatively simple and handles full overlaps. It has at least two cons though: 
* can be a bit slow to manually rotate between hints
* interface is not as obvious and intuitive as being able to see all hints (at the moment it's easy to overlook overlapped hints; plus it's an extra command for new users to learn)

Another way might be to try avoiding overlaps by pushing hints around so that you can always see all characters of every hint (or something along those lines).
some pros:
* if the locations found are "good" (decent chance that would be difficult), ought to enable both faster and more intuitive browsing than manually rotating z-indices
some cons:
* surely more involved to implement than rotating
* surely slows down hint generation more
* if the locations found are "bad", figuring out which hint matches which element could be too hard/slow for users

<hr>

Tangentially related (would this part be better off with its own issue?), VimFX's yank/copy hint generation had few overlaps — it looks like checking for text in direct children rather than all descendants might be the key: https://github.com/tridactyl/tridactyl/pull/116#issuecomment-347906043

<hr>

keywords to help searches: rotate rotation collision detection

**Comment by sangeet** [comment] 2021-07-31 23:59
Hi, just curious if anything ever happened to this. I browse old Reddit using this extension and I absolutely love the tts mode but at times it's nearly impossible to distinguish which block of text to select as you can see in this image
![image](https://user-images.githubusercontent.com/346858/127754933-9e9dd0a6-f0cc-4f40-b21c-4f8f7b230381.png)

Randomized links will help a lot as I can simply type 1-2 characters and it will guide me to the correct one by removing unnecessary ones and when I'm wrong I can always start again, but at least that would be predictable and over time I can develop enough pace for it to feel natural.

Currently I have to remember the order manually and that always doesn't work leading to a lot of mis-targeted attempts.

I understand that randomized links won't solve all the problems but it will drastically make the hints more usable.

**Comment by bovine3dom** [comment] 2021-08-01 07:26
I don't really understand what you're asking for, sangeet. Could you explain in a bit more detail what you mean by randomised hints?

This issue was filed because our hints used to cover each other up; the idea was that you would be able to shuffle the hints to change which ones you could see. Since our hints don't cover each other up any more I'll close this issue :)

**Closed by bovine3dom** 2021-08-01 07:26 UTC
Labels: P4, enhancement

**Comment by sangeet** [comment] 2021-08-02 14:20
Sorry for not explaining it correctly. As you can see in the above image, there are a lot of hints jumbled across and this makes it quite difficult for me to target a specific text block that I want to.

Currently if I start typing `y` then the UI starts removing hints not starting with `y` and hence I am able to narrow down closer to the area I want to target.

The problem is that with typing `y`, all the related elements are close to each other and hence removal of unrelated links is of no help as I am still clueless on which character to hit after `y`. `yl`, `yz` `yx`, `yc`, etc are all close enough that I still am unsure which one to use to target the first paragraph.

A possible solution to this is to not order the hints and have them as distinct as possible so that when I type the first character, the closer links are unrelated enough for me to be able to narrow down more clearly. 

# Example:

Current Order :`yl`, `yz` `yx`, `yc` all jumbled up close to each other. pressing `y` still leaves me confused which element to target as they're all close to each other.

Proposed Order (essentially no order): `ax`, `bx`, `cx`, `dx`, etc. pressing any of the first character will filter out the other nearly elements making it obvious which element I am trying to target.

This will go a long way to add more robustness to the hinting system since more and more sites are starting to use a lot of javascript based interactions all jumbled across and it tends to leave a cluster of extremely hard to target hints as demonstrated in the image above.

I understand that you have a lot of issues to deal with in this project, hence this is by no means a priority, but it always felt that something like this would seriously help make this amazing extension even better.

I hope this explanation made sense, a bit verbose but I hope it makes sense.

**Comment by sangeet** [comment] 2021-08-02 14:27
So this is essentially not an issue but more of an enhancement thing as the original request dealt with overlapping links and this proposal is to improve working with a cluster of links jumbled in a small area. Let me know if this is something you would be interested in and we can make a new thread and if you're busy then maybe I can try and pick it up if it suits my skill.

**Comment by bovine3dom** [comment] 2021-08-02 19:16
@sangeet yeah, I think I sort of see the utility of that : )

Are you sure it's better than just pressing tab/shift tab once you've filtered down to the general area?

**Comment by sangeet** [comment] 2021-08-03 08:34
Tabbing doesn't work since there are like 10-15+ links all starting with the same first character. It wouldn't quite do the job.
