### ISSUE TITLE
Mode anotations should not show up in print mode

### ISSUE THREAD

**Issue by jbayardo** [tridactyl/tridactyl#2598] opened 2020-07-08 20:35 UTC
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 79.0
Operating system: win

When printing, I see the string "normal" as part of the printed file. This corresponds to Tridactyl's mode annotation.

**Comment by bovine3dom** [comment] 2020-07-08 21:13
Duplicate of #453 - I'll try to remember to look at that soon-ish : )

**Closed by bovine3dom** 2020-07-08 21:13 UTC
