### ISSUE TITLE
unset searchurls.foo does not remove searchengine "foo"

### ISSUE THREAD

**Issue by lmoellendorf** [tridactyl/tridactyl#993] opened 2018-09-08 10:03 UTC
*   Brief description of the problem:

See topic

*   Steps to reproduce:

 1. `:unset searchurls.bing`
 2. `:viewconfig searchurls` -> bing and its URL is still there

*   Tridactyl version (`:version`): 1.14.0-2-g51fcf8a

*   Firefox version (Top right menu > Help > About Firefox): 61.0 (64-bit)

**Comment by glacambre** [comment] 2018-09-08 10:38
Hi, thanks for opening this issue. This is probably a duplicate of https://github.com/tridactyl/tridactyl/issues/929.

**Comment by glacambre** [comment] 2018-09-16 12:32
Hi, I found a temporary workaround to this issue, you can find it here: https://github.com/tridactyl/tridactyl/issues/929 .

**Comment by bovine3dom** [comment] 2018-09-16 14:14
Closing as duplicate of #929. Thanks for reporting.

**Closed by bovine3dom** 2018-09-16 14:14 UTC
