### ISSUE TITLE
new tab by link or typing (sporadically or randomly) spawns multiple unwanted tabs

### ISSUE THREAD

**Issue by thrisp** [tridactyl/tridactyl#1273] opened 2019-01-07 19:23 UTC
*   Brief description of the problem:

opening addresses in new tab causes unwanted other tabs to open, either the tridactyl 'new tab' or what I'm assuming is my top pinned page (for example clicking on a link on youtube spawns 3 new tabs containing my top pinned page underneath all other tabs) 

its sporadic and frustratingly impossible to reproduce, but it happens several times a day

*   Steps to reproduce:

    open a new tab by mouse click or by pressing 't' followed by address

*   Tridactyl version (`:version`):

1.14.6-51-gec8e2ce

*   Firefox version (Top right menu > Help > About Firefox):

64

*   URL of the website the bug happens on:

non specific, occurs when opening addresses

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
" tridactyl rc

"tmp workarounds
set csp clobber
fixamo_quiet

"window
set theme dark
guiset_quiet gui none
guiset_quiet hoverlink right
set allowautofocus false
""set newtab file:///home/\\\/\\\/index.html

"keybinds
bind ; fillcmdline_notrail
bind ArrowLeft tabprev
bind h tabprev
bind ArrowRight tabnext
bind l tabnext
bind j scrollline 10
bind J scrollline 20
bind k scrollline -10
bind K scrollline -20
```

**Comment by bovine3dom** [comment] 2019-01-07 20:12
Duplicate of #1237. Thanks for reporting : )

**Closed by bovine3dom** 2019-01-07 20:12 UTC

**Comment by bovine3dom** [comment] 2019-01-07 20:15
FWIW,
```
bind ArrowLeft tabprev
bind ArrowRight tabnext
```

binds things to the literal sequence of key presses `A` `r` `r` `o` `w` ... - you need to use `<ArrowLeft>` and `<ArrowRight>` instead.

**Comment by thrisp** [comment] 2019-01-07 20:55
@bovine3dom 

ok, thank you
