### ISSUE TITLE
js -p interpret code with semicolon wrong

### ISSUE THREAD

**Issue by alanche** [tridactyl/tridactyl#2183] opened 2020-02-23 02:34 UTC
Tridactyl version: 1.16.3pre3110-e1f91c4
Firefox version: Mozilla Firefox 73.0.1
Operating system: win

This code is executed fines:
js  (function(v) {console.log(v);console.log(v);})('hello')

However, this is not:

js  -p (function(v) {console.log(v);console.log(v);})('hello')

Console shows up:

controller in excmd:  SyntaxError: "missing { before function body"
    js .excmds_content.generated.ts:3629
    acceptExCmd controller.ts:21
    handler messaging.ts:44
    onMessage messaging.ts:147

**Comment by glacambre** [comment] 2020-02-23 05:28
`js -p` expects a parameter.

`js alert ("hello")` works.
`js -p alert ("hello")` doesn't and isn't supposed to.
`alias alert js -p alert (JS_ARG)` and then running `:alert hello` works.

I guess we should mention that using `-p` means you must pass an argument to JS in the doc pages.

**Comment by alanche** [comment] 2020-02-23 05:35
This works:

composite echo "hello" | js -p (function(v) { console.log(v) })(JS_ARG)


This Not:

composite echo "hello" | js -p (function(v) { console.log(v);console.log(v) })(JS_ARG)


I suppose there is a bug when processing '-p' and parsing the javascript expression.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ghjuvan Lacambre"<notifications@github.com&gt;; 
发送时间: 2020年2月23日(星期天) 中午1:28
收件人: "tridactyl/tridactyl"<tridactyl@noreply.github.com&gt;; 
抄送: "胜仔Alan"<alan-che@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [tridactyl/tridactyl] js -p interpret code with semicolon wrong (#2183)




js -p expects a parameter.
 
js alert ("hello") works.
 js -p alert ("hello") doesn't and isn't supposed to.
 alias alert js -p alert (JS_ARG) and then running :alert hello works.
 
I guess we should mention that using -p means you must pass an argument to JS in the doc pages.

**Comment by glacambre** [comment] 2020-02-23 05:46
No, the problem is that `composite` splits the line on semicolons and then tries to execute each piece separately. So it tries to execute this:

`echo "hello" | js -p (function(v) { console.log(v)`
`console.log(v) })(JS_ARG)`

You can circumvent this issue either by replacing semicolons with something else (e.g. `console.log(v) || console.log(v)`, programming without semicolons can be done by taking inspiration from here: https://github.com/tridactyl/tridactyl/issues/434#issuecomment-386811276) or by aliasing your js functions to a command and then piping to the command instead of to `js`.

**Comment by alanche** [comment] 2020-02-23 06:03
OK,Thanks for your kindly help and explaination.

**Comment by glacambre** [comment] 2020-02-23 06:08
You're welcome. I think you're not the first person to trip over this, we should probably mention it in the help pages. I'll reopen this issue until the docs are updated :).

**Comment by mozbugbox** [comment] 2020-02-25 04:05
No, the doc for `js -p` was incomplete and confusing. Nobody knows how to use it. It should specify that the argument you passed to `js -p` must be at the end of thecommand, 

NOT right after `-p`.
NOT right after `-p`.
NOT right after `-p`.

The following code works.
```
js -p (function(v) {console.log(v);console.log(v);})(JS_ARG) hello
```

You just have to put the "hello" to the end. And of cause no space was allowed in the arg. The parser doesn't handle quoted string.

**Comment by bovine3dom** [comment] 2020-02-25 17:40
The current help is this:

```
 * If you want to pipe an argument to `js`, you need to use the "-p" flag and then use the JS_ARG global variable, e.g:
 *
 * `composite get_current_url | js -p alert(JS_ARG)`
```

I think explicitly mentioning you need a space at the end would be a bit confusing - it's an implementation detail and not really relevant to the use of it (as you the only use for it is to create your own ex-commands, e.g. `alias alert js -p alert(JS_ARG)` and `:alert Boo!` or with composite `composite get_current_url | alert`.

I agree the fact that spaces don't work should be documented :)

**Comment by bovine3dom** [comment] 2021-01-27 21:40
I know `JS_ARGS` are broken at the moment but now that they exist (with the `-d` option) I think we can close this issue

**Closed by bovine3dom** 2021-01-27 21:40 UTC
