### ISSUE TITLE
":mode disable" yields an error

### ISSUE THREAD

**Issue by wavexx** [tridactyl/tridactyl#1051] opened 2018-10-03 13:21 UTC
I just tried ":mode disable", but as soon as I press any key I get the following:

````
# An error occurred in the content controller: TypeError: parsers[_state_content__WEBPACK_IMPORTED_MODULE_1__.contentState.mode] is not a function ¯\_(ツ)_/¯ 
````

I'm using FF 62.0.2, on linux, using the beta build.

**Comment by glacambre** [comment] 2018-10-03 13:37
Hi, thank you for reporting this issue. `disable` isn't a mode, does the recommendation recommend to use that somewhere? What you're probably looking for is `mode ignore`.

**Comment by wavexx** [comment] 2018-10-03 13:57
On Wed, Oct 03 2018, glacambre wrote:
> Hi, thank you for reporting this issue. disable isn't a mode, does the
> recommendation recommend to use that somewhere? What you're probably
> looking for is mode ignore.

I was looking at the blacklistadd documentation.

:mode ignore is not sufficient in my case, since it can switch back to
normal mode.

I really want to *completely* disable trydactyl for a certain
domain/url. And hopefully to remove the status bar at the bottom as
well.

**Comment by wavexx** [comment] 2018-10-03 14:12
On Wed, Oct 03 2018, Yuri D'Elia wrote:
> I was looking at the blacklistadd documentation.

Mh, I actually cannot find any reference to it in the current
documentation, I was perhaps looking online via google.

> :mode ignore is not sufficient in my case, since it can switch back to
> normal mode.

I can re-iterate this though. Ignore is not sufficient. Shift-I will
restore normal mode. Is this intended?

I currently have to disable the add-on completely.

**Comment by glacambre** [comment] 2018-10-03 14:12
I would recommend you try `seturl urlofthewebsite modeindicator false`, `noiframeon urlofthewebsite`, `autocmd DocStart urlofthewebsite mode ignore` and we currently don't have a way to unbind things on a per-url basis so you'll have to either `unbind --mode=ignore $key`, with keys being the keys you can find here: https://github.com/tridactyl/tridactyl/blob/master/src/config.ts#L76-L83

There's no way to completely disable Tridactyl for now.

**Comment by cmcaine** [comment] 2018-10-03 14:15
Completely disabling tridactyl for a tab is a valid desire. Here's a
workaround for now.

set noiframeon $url
Unbind the ignore mode default bind

Optional
Bind a new escape sequence that's longer/weirder?

**Comment by glacambre** [comment] 2018-10-03 14:27
> that wasn't enough for the site I was trying to use

Have you also tried `set allowautofocus true` and `set csp untouched`? We have a bunch of troubleshooting steps here: https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md , I'd be very surprised to discover that none of these would fix Tridactyl breaking the website you're trying to use.

`blacklistadd` should probably try to disable these settings.

**Comment by wavexx** [comment] 2018-10-03 14:34
On Wed, Oct 03 2018, glacambre wrote:
> https://github.com/tridactyl/tridactyl/blob/master/doc/troubleshooting.md
> , I'd be very surprised to discover that none of these would fix
> Tridactyl breaking the website you're trying to use.

I'm trying to use a "jupyter notebook". Jupyter has a vim-like dual-mode
state, with almost all keyboard keys mapped to some function. Like in
vim, you can enter/exit command/edit mode. Notably, Esc is used pretty
much like in vi.

You can imagine the two cannot work together.

**Comment by wavexx** [comment] 2018-10-03 14:41
On Wed, Oct 03 2018, Colin Caine wrote:
> set noiframeon $url
> Unbind the ignore mode default bind

If I could do that just for the current tab, I would be set (I guess
it's not possible?)

I'd rather do a :setlocal noiframe / :unbindlocal... from an autocmd.
Feels cleaner than using :set noiframeon [url] in two places.

I don't want to change the default ignore bind. This is definitely an
exception I'm trying to fix.

**Comment by glacambre** [comment] 2018-10-03 14:42
This is surprising to me because I tested Tridactyl on Jupyter multiple times and it worked quite nicely. Have you tried to disable the ignore-mode mappings? e.g.
```
unbind <S-Insert>
unbind <CA-Escape>
unbind <CA-`>
unbind <S-Escape>
unbind <C-^>
unbind I
```
This will prevent you from leaving ignore mode and then you could add a weird binding in order to go back to normal mode like `bind <C-\><C-n> mode normal`.
The only other thing I needed to do in order to make sure things worked was to `set allowautofocus false`. This made all possible conflicts disappear.

**Comment by wavexx** [comment] 2018-10-03 15:31
I apologize for abusing this issue, but several random issues I've found
while trying the various solutions:

With the following:

autocmd DocStart localhost mode ignore
seturl localhost modeindicator false

only the last command of the two work at the same time for me.
If I do seturl last, modeindicator is disabled.

If I do autocmd last, mode defaults to ignore, but the modeindicator
remains visible.

unbind doesn't mention "--mode" in the documentation.

Looking at seturl/autocmd, I'd clarify we just take regexes, and that
the searches are not anchored to avoid confusion. Especially for the
documentation of autocmd, it might look like you can use a bare "." in
the url, but it's not the case.

**Comment by wavexx** [comment] 2018-10-03 15:37
And also, "set modeindicator false/true" doesn't take effect until
there's an additional (manual) mode switch after the toggle.

**Comment by glacambre** [comment] 2018-10-03 16:35
>I apologize for abusing this issue

Don't worry about this, the important thing is that we're made aware of the problems, thank you for reporting them :)

I've opened a [PR](https://github.com/tridactyl/tridactyl/pull/1053) in order to implement `{bind,unbind,reset}url`, your ignore mode problems should be solved once it is merged.

I'm quite puzzled by your autocmd+seturl problems though, I can't seem to reproduce them  on my machine. Does this happen on every website or just your jupyter install?

**Comment by wavexx** [comment] 2018-10-03 17:00
On Wed, Oct 03 2018, glacambre wrote:
> I'm quite puzzled by your autocmd+seturl problems though, I can't seem
> to reproduce them on my machine. Does this happen on every website or
> just your jupyter install?

Everywhere. I tested it with ".*" as the url pattern.

**Comment by bovine3dom** [comment] 2018-10-03 17:06
> Jupyter has a vim-like dual-mode state

`mode ignore` works fine for me in Jupyter with the vim binding extension. I found I also needed `set allowautofocus true`.

**Comment by wavexx** [comment] 2018-10-04 10:13
On Wed, Oct 03 2018, Oliver Blanthorn wrote:
>     Jupyter has a vim-like dual-mode state
>
> mode ignore works fine for me in Jupyter with the vim binding extension. I found I also
> needed set allowautofocus true.

set allowautofocus was/is already true in my case.
Do I need to explicitly set it anyway?

I don't know what happens, but even in ignore mode after using jupyter
for a while tridactyl switches back to normal mode for some reason.

I've unbound all keys in ignore mode now, so I'm really puzzled.

But overall tridactyl has some overall glitches for me too.

For instance, when I open a new tab via Ctrl+T then focus the url bar
with Ctrl+L immediately, I can only type for half a second, then the
focus is stolen from me. Somehow this changed recently, and changing the
allowautofocus doesn't seem to work.

You might think that I should be using 'o' instead, and it's true,
except 'o' doesn't work everywhere, while Ctrl+T/Ctrl+L used to.

Also, if I type immediately after 'o' some keypresses are lost, while
Ctrl+T/Ctrl+L aren't. Also 'o' appears too slowly. Seems almost
animated (and if it is, I'd love to remove it).

The reason I use extensions like these is that I type fast. Having all
these glitching, slow and inconsistent behavior is maddening :/

(Still... better than plain FF)

**Comment by glacambre** [comment] 2018-10-04 10:21
> I can only type for half a second, then the focus is stolen from me. Somehow this changed recently

Yes, this has changed very recently (and it's my fault). A few users reported that they preferred using the url bar and so antonva implemented a setting to let them do that. It is named `newtabfocus` and you should set it to `urlbar` if you don't want to focus the page (so `set newtabfocus urlbar`).

>Also, if I type immediately after 'o' some keypresses are lost, while Ctrl+T/Ctrl+L aren't. Also 'o' appears too slowly. Seems almost animated (and if it is, I'd love to remove it).

Yes, we are aware of that, we have a few PRs to help with that, we're definitively going to improve that.

**Comment by bovine3dom** [comment] 2018-10-04 11:45
> Do I need to explicitly set it anyway?

Nope.

>  Seems almost animated (and if it is, I'd love to remove it).

We don't have any animations.


Thanks for reporting these issues : )

**Comment by bovine3dom** [comment] 2018-10-04 13:03
It's just slow and blocking on input : (

We'll fix it someday.

**Comment by glacambre** [comment] 2019-01-28 06:57
I believe the only problem left in this ticket is that the commandline is slow, which is mentionned in https://github.com/tridactyl/tridactyl/issues/1295, https://github.com/tridactyl/tridactyl/issues/1242, https://github.com/tridactyl/tridactyl/issues/1208, https://github.com/tridactyl/tridactyl/issues/1092 and https://github.com/tridactyl/tridactyl/issues/917 so I'll close this issue. Please let me know if there's something else mentioned here that I missed.

**Closed by glacambre** 2019-01-28 06:57 UTC
