### ISSUE TITLE
Completion for custom commands

### ISSUE THREAD

**Issue by Jab2870** [tridactyl/tridactyl#2921] opened 2020-10-19 12:32 UTC
Tridactyl version: 1.20.2pre4699-b3d77003
Firefox version: Mozilla Firefox 82.0
Operating system: linux

Is it possible to add custom completion for custom commands. For example, if I had:

```
command mybookmarks js <whatever>
```

Would I be able to configure custom completion for that?

I am sure there are many use cases for this, but mine is as follows:

I don't use firefox's bookmarks, I maintain a text file on my harddrive that contains a url and any keywords I associate with it. I would like to be able to make this file populate the completions.

Thanks

**Comment by bovine3dom** [comment] 2020-10-19 13:25
Sort of a dupe of #2865 - it's something I'd really like to add but will require us to rewrite a lot of our completion code. We could potentially add user completions before that though, and it might make migrating smoother.

We're adding the ability to use our existing completions with arbitrary commands in #2919 but that won't solve your problem unless you could make a pretend filesystem that contains each bookmark as a file (potentially easier than it sounds with Linux).

**Comment by Jab2870** [comment] 2020-10-19 14:32
#2865 looks like an excellent addition to trydactyl. I am happy to close this then until that becomes a reality. Thanks for your quick reply

**Closed** 2020-10-19 14:32 UTC
