### ISSUE TITLE
Scrolling on pages with scrollable nav bars scrolls the nav bars

### ISSUE THREAD

**Issue by dlobue** [tridactyl/tridactyl#2410] opened 2020-05-22 22:13 UTC
Tridactyl version: 1.19.0pre3823-ac82bf6
Firefox version: Mozilla Firefox 76.0.1
Operating system: linux

*   Brief description of the problem:

On websites with scrollable side navbars, trying to scroll the main content div
results in the navbar scrolling instead, and the main content only scrolling
once the navbar has reached the end of travel.

This has a funny and infuriating side-effect where if you scroll past what
you wanted to look at, in order to scroll back up even a single line, you
have to wait until the navbar finishes scrolling all the way back up to the
top.

*   Steps to reproduce:

1. Browse to website with the issue (below)
2. Expand nodes in nav sidebar to get it as long as possible, and resize browser window if necessary to ensure the nav sidebar overflows.
3. Use `j` to scroll down.
4. Notice only the nav sidebar scrolls.
5. Keep scrolling until the main div starts scrolling.
6. Stop when at some midpoint of the doc page.
7. Try scrolling back up with `k`.

*   URL of the website the bug happens on:

https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Introduction.html

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):

https://gist.github.com/dlobue/c3c789326da1a9ee3b36b0171267851f

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl:

/root/.cargo/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/opt/kde/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/qt/bin:/opt/staruml/ 

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:

        {"cmd": "run", "content": "/root/.zplug/bin:/root/.cargo/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/opt/kde/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/opt/qt/bin:/opt/staruml/:/usr/lib/go/site/bin:/usr/share/git/remote-helpers:/root/.go/bin:/root/.rvm/bin:/root/.jenv/bin:/root/.pyenv/bin:/root/bin:/root/.local/bin:/root/.node_modules/bin:/root/.npm/bin:/root/node_modules/.bin:./node_modules/.bin:/root/.gem/ruby/2.6.0/bin\n", "code": 0}

**Comment by bovine3dom** [comment] 2020-05-22 22:38
Yes, this is annoying. Amusingly, most websites that have this kind of interface of a sidebar and a viewport are developer documentation - i.e. the type of sites Tridactyl users are likely to visit.

Closing as a duplicate of #1805 (I think you're asking for better heuristics too, but I consider that covered by that issue).

**Closed by bovine3dom** 2020-05-22 22:38 UTC
