### ISSUE TITLE
Fully featured VIM text search implementation

### ISSUE THREAD

**Issue by Massimo-B** [tridactyl/tridactyl#4150] opened 2022-03-21 08:11 UTC
firefox-91.7.0 on Linux
Tridactyl: Beta 1.22.0pre6186

Hi, are there plans to implement a fully features vim search? Currently it seems that / just calls the simple Firefox search.
Coming from Pentadactyl, it had a more advanced own search implementation also supporting regular expression search within web pages: http://bug.5digits.org/help/pentadactyl/pattern.xhtml

**Comment by bovine3dom** [comment] 2022-03-22 20:12
Duplicate of #1612 :)

You can see `:help find` in the meantime

**Closed by bovine3dom** 2022-03-22 20:12 UTC
