### ISSUE TITLE
Calling mkt produces "controller in excmd: Error: getrcpath error: Path not found"

### ISSUE THREAD

**Issue by mb720** [tridactyl/tridactyl#2124] opened 2020-01-28 16:42 UTC
Hi!

[I've installed](https://github.com/tridactyl/tridactyl/issues/2123) the native messenger on Arch Linux and I can see that creating a tridactylrc doesn't work. Calling `mkt` in Firefox yields

>controller in excmd: Error: getrcpath error: Path not found

I'm not sure if there's something wrong with my setup, calling :native in Firefox works:

    Native messenger is correctly installed, version 0.1.11

Thanks for having a look!

---

Tridactyl version: 1.17.1pre3304-7dcf183
Firefox version: Mozilla Firefox 72.0.2
Operating system: linux

*   Result of running `:! echo $PATH`, or `! echo %PATH%` on Windows, in Tridactyl: `/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/mb/.local/bin`

*   Unix-like only: result of running `printf '%c\0\0\0{"cmd": "run", "command": "echo $PATH"}' 39 | ~/.local/share/tridactyl/native_main.py` in a terminal:
    bash: /home/mb/.local/share/tridactyl/native_main.py: No such file or directory

**Comment by bovine3dom** [comment] 2020-01-28 16:50
Hmm, it might be failing to make a directory. Could you try running `mkdir -p ~/.config/tridactyl`?

**Comment by mb720** [comment] 2020-01-28 17:51
I created the directory but the error stays the same.

**Comment by bovine3dom** [comment] 2020-01-28 18:05
The code that tries to find the path is quite simple - https://github.com/tridactyl/tridactyl/blob/b6e58c426ebbb564f99d23c0e95a3ab540fe81c2/native/native_main.py#L85 - perhaps you can work out what is wrong from that?

**Comment by bovine3dom** [comment] 2020-01-28 18:07
Oh, this is probably just a duplicate of #2023 - perhaps `touch ~/.config/tridactyl/tridactylrc` will do the trick.

If you fancy fixing #2023 it is probably quite straightforward :)

**Comment by mb720** [comment] 2020-01-29 10:24
Thanks for your help! After `touch ~/.config/tridactyl/tridactylrc` and calling `:mkt` in Firefox, there's no more error message, but the file `tridactylrc` is still empty

**Comment by bovine3dom** [comment] 2020-01-29 10:51
I think you need to call `mkt -f` or it won't overwrite your (empty) file

**Comment by mb720** [comment] 2020-01-29 11:38
`-f` did the trick, thanks! :-)

**Comment by mb720** [comment] 2020-01-29 12:44
I've modified `getUserConfig` in my local `native_main.py` to create an empty `tridactylrc` if it doesn't exist:

    def getUserConfig():
        # look it up freshly each time - the user could have moved or killed it
        cfg_file = findUserConfigFile()

        # none of the candidate config files exists → Create one
        if not cfg_file:
            home = os.path.expanduser("~")
            config_dir = getenv(
                "XDG_CONFIG_HOME", os.path.join(home, ".config")
            )
            tridactyl_config_dir = os.path.join(config_dir, "tridactyl")
            if not os.path.exists(tridactyl_config_dir):
                os.makedirs(tridactyl_config_dir)
            cfg_file = os.path.join(tridactyl_config_dir, "tridactylrc")
            # create an empty config file
            handle = open(cfg_file, "x")
            handle.close()

        # for now, this is a simple file read, but if the files can
        # include other files, that will need more work
        return open(cfg_file, "r", encoding="utf-8").read()

Running `mkt` in Firefox creates the necessary directories and the empty `tridactylrc`. But I don't know how `mkt` exactly works to make it write the current configuration to `tridactylrc`.

Also, when deleting `tridactylrc` after the first call to `mkt`, it seems that `getUserConfig` is not called again, since I get the error `controller in excmd: Error: getrcpath error: Path not found`.

**Comment by bovine3dom** [comment] 2020-01-29 13:16
Thanks. I think it makes more sense to catch the error here and default to a sensible path - https://github.com/tridactyl/tridactyl/blob/b6e58c426ebbb564f99d23c0e95a3ab540fe81c2/src/background/config_rc.ts#L38

**Comment by Tanath** [comment] 2020-04-26 21:06
I was just having this issue. `mkt` and `mkt -f` didn't work until I did `touch ~/.config/tridactyl/tridactylrc` and ran `mkt -f`.

Tridactyl version: 1.18.0pre3771-f0ec742
Firefox version: Mozilla Firefox 75.0
Operating system: linux

**Comment by bovine3dom** [comment] 2020-04-26 22:27
Sorry about that, looks like we closed the issue before we actually fixed it :)

**Comment by bs** [comment] 2020-04-28 07:19
Just chiming in to say that I was hitting the same and found this issue!

Is it not possible for the native binary to create and touch the file before writing?

**Comment by bovine3dom** [comment] 2020-04-28 08:13
It is, but I think it makes more sense for us to handle it in JavaScript. It really is just a couple of lines to fix it. The hardest part is coming up with a sensible default across all OSs.

**Closed** 2020-04-28 09:46 UTC
Labels: P2, bug, good first issue
