### ISSUE TITLE
After updating to Fx74, "composite tabopen <url> ; tabopen <url> now focuses on the URL bar on every opened tab besides the last open one

### ISSUE THREAD

**Issue by nnadd** [tridactyl/tridactyl#2249] opened 2020-03-23 11:52 UTC
Tridactyl version: 1.17.1pre3304-7dcf183 (AMO)
Firefox version: Mozilla Firefox 74.0
Operating system: linux

Pretty much what the title says, on Firefox 73 and before I had no problems, the multiple URLs I set on a bind.. example: `bind E5 composite tabopen https://techpowerup.com ; tabopen http://guru3d.com/news.html ; tabopen https://anandtech.com` used to open cleanly and I could easily navigate with the tridactyl through them, now every tab besides the last one in the composite chain is focused on the URL bar 
![Screencap_23-03-2020_12:50:42](https://user-images.githubusercontent.com/32570320/77313896-f5d69900-6d04-11ea-9c74-eef130bf28c5.jpeg)

making me unable to navigate the page until I hold TAB and the page focuses on where tridactyl can actually do its job, or just close the tab and undo close tab giving focus back to tridactyl. 

I have changed nothing in my tridactylrc, and I don't recall a recent tridactyl update, I tried this in multiple Firefox profiles and the issue remains, it's entirely due to the Firefox 73>74 update.

**Comment by glacambre** [comment] 2020-03-23 12:22
I've had this issue for a while (though I trigger it by using `js [...].forEach(url => tri.excmds.tabopen(url))`), so I don't think this is caused by a Firefox update.

Maybe this could be fixed by https://github.com/tridactyl/tridactyl/issues/1993?

>unable to navigate the page until I hold TAB and the page focuses

You can also use `<F6>` for that.

**Comment by bovine3dom** [comment] 2020-07-07 17:02
Fixed in #1993

**Closed by bovine3dom** 2020-07-07 17:02 UTC
Labels: P4, bug
