### ISSUE TITLE
Feature/compatibility issue: Full ignore mode for URLs

### ISSUE THREAD

**Issue by Cybolic** [tridactyl/tridactyl#2004] opened 2019-11-16 15:06 UTC
Currently, when setting a site to be ignored, the Tridactyl iframe will still be loaded unto the page.
It would be great to have a way to blacklist/ignore a site completely as the current method can mess with frame detection.

To experience this issue:
1. `:autocmd DocStart vesalia.de mode ignore`
2. go to https://www.vesalia.de
3. the page will continuously reload

That site checks for `top.frames.length > 0` in order to break out of frames but having the Tridactyl frame there on all ocassions could potentially mess with other sites as well.

Tridactyl version: 1.17.1pre3329-ca15582

**Comment by bovine3dom** [comment] 2019-11-16 15:21
I think we have another issue open about this.

In the meantime you might try `seturl [URL] noiframe true`.

**Comment by Cybolic** [comment] 2019-11-16 15:22
Oh, good call; missed that one in the documentation!

**Comment by bovine3dom** [comment] 2021-03-20 11:13
Duplicate of #822

**Closed by bovine3dom** 2021-03-20 11:13 UTC
Labels: P4, enhancement
