### ISSUE TITLE
Links in startpage are opened in window instead of tab

### ISSUE THREAD

**Issue by jamatute** [tridactyl/tridactyl#1030] opened 2018-09-27 09:31 UTC
*   Brief description of the problem: When opening new links in startpage instead of opening it in a new tab it opens them in a new window. The rest of webpages work as expected

*   Steps to reproduce:
1. :open startpage tridactyl rocks
2. Hit f or F and follow a link

*   Tridactyl version (`:version`): 1.14.0-43-g877b157

*   Firefox version (Top right menu > Help > About Firefox): 60.2.1esr (64-bit)

*   URL of the website the bug happens on: www.startpage.com

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com):  https://gist.github.com/jamatute/2083b59ebc9f2b9ff4d6ecee08e318bb

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): I tried both with and without config file with the same result

```
colours dark

" Navigation
set hintchars asdfjk
set hintuppercase false
set smoothscroll true
set scrollduration 50
set searchengine startpage

bind --mode=insert jk composite unfocus | mode normal
bind --mode=normal jk composite unfocus | mode normal
bind --mode=ignore jk composite unfocus | mode normal
bind --mode=input jk composite unfocus | mode normal
bind J tabprev
bind K tabnext_gt
bind $ tablast
bind 0 tabfirst

" Webjumps
unbind w
bind wg fillcmdline open gentoo_wiki
bind wy fillcmdline open youtube
bind wh fillcmdline open github

" Bindings

bind yl hint -y
bind yp hint -p
bind y# hint -#
```

**Comment by bovine3dom** [comment] 2018-09-27 10:47
Closing as duplicate of #506. Thanks for reporting.

**Closed by bovine3dom** 2018-09-27 10:47 UTC
Labels: P4, bug
