### ISSUE TITLE
Provide build without new tab page

### ISSUE THREAD

**Issue by oxysoft** [tridactyl/tridactyl#534] opened 2018-05-14 11:53 UTC
This is a big problem. I use momentum for my new tab page and Tridactyl overrides it. I know there's a setting in tridactyl to forward the page to something else, but it's not very fast and it means I can't start typing as soon as I have typed **CTRL-T** because the URL bar changes a second or two after.

**Comment by bovine3dom** [comment] 2018-05-14 11:55
Have you tried uninstalling Momentum and installing it after Tridactyl? Or just disabling/enabling it?

**Comment by bovine3dom** [comment] 2018-05-14 12:49
Duplicate of #384.

**Comment by oxysoft** [comment] 2018-05-14 19:11
Yes I have.

**Comment by bovine3dom** [comment] 2018-05-14 19:47
Magic, I guess. I think the only way of solving this is to offer an API to other add-ons to let Tridactyl run on their page, if that's even possible.

**Comment by oxysoft** [comment] 2018-05-14 21:01
Personally I don't care for Tridactyl to run on my new tab page, I just CTRL-T CTRL-L and start typing.

**Comment by bovine3dom** [comment] 2018-05-26 17:44
> A build of the extension without a new tab page override is offered.

You can do this yourself very easily by just removing this line: https://github.com/cmcaine/tridactyl/blob/master/src/manifest.json#L16

If you want a signed build, getting Mozilla API keys is pretty easy - just go to https://addons.mozilla.org/en-US/developers/addon/api/key/ while signed in with a Firefox account. Put these details in a file called `AMOKEYS` which looks like:
```
AMOKEY=youruser:id
AMOSECRET=abighashcodething
```

Then, you'll need to make a new addon listing on the Firefox site (it can be hidden) and change the ID everywhere to that.

Once this is all done, just run `scripts/sign stable` and you'll get an XPI in web-ext-artifacts/ that you can add to Firefox permanently.

I hope this helps :)

**Comment by bovine3dom** [comment] 2019-05-22 11:13
Thanks to @mphe and @cmcaine this now exists at https://tridactyl.cmcaine.co.uk/betas/nonewtab/.

It's a bit broken - see https://github.com/tridactyl/tridactyl/labels/nonewtab - but I'm closing this issue because it is "fixed" in spirit.

Anecdotally - I've been using the build for about 10 minutes, and it's _extraordinarily_ annoying to get stuck on a new tab page where Tridactyl isn't running, so I feel vindicated in my ambivalence towards dedicating any time to getting this working ;)

**Closed by bovine3dom** 2019-05-22 11:13 UTC
Labels: good first issue, help wanted

**Comment by oxysoft** [comment] 2019-05-22 15:17
Sorry for not updating, but I've been able to use both Tridactyl and a start page extension together with no issue for a while. I'm not sure if Mozilla has improved support to pick which new tab page to use or if by luck Firefox simply got stuck on my desired start page, but either way it's been working fine!

I use CTRL-T to open a new tab and the URL bar is already focused and ready to type so for me it's not a problem to be missing Tridactyl there.
