### ISSUE TITLE
tabopen opens some tabs net to current and some at the end

### ISSUE THREAD

**Issue by kecmen** [tridactyl/tridactyl#2985] opened 2020-11-07 21:24 UTC
Tridactyl version: 1.20.2
Firefox version: Mozilla Firefox 82.0.2
Operating system: linux

Hi,
first of all, thanks for this extension :+1: 
I would like the new tabs to be opened next to the current one. Here is what i have in the config file (relevant parts):
`set tabopenpos next`
`set relatedopenpos related`
When I'm on some tab and I press `t` (or just open command line and write `tabopen`) and then insert an url (for example nytimes.com) new tab with that page opens next to the current one.
But when I do the same thing but I just write nytimes (or nytimes com or pretty much anything that's not url and what triggers search) a new tab with google search results is opened at the end of the tab list. Is this intended behaviour? Is there any way how I can make the searches (which is what i do most of the time) open next to current tab?

Thanks

**Comment by bovine3dom** [comment] 2020-11-07 21:46
Looks like this is a known issue - https://github.com/tridactyl/tridactyl/blob/eca1e1614b8d0e51dcb7369a3b4026fed72ad209/src/excmds.ts#L2285 - but perhaps not one documented here. Thanks for reporting it - I'll try to look in to it tomorrow to work out what's going on.

**Comment by bovine3dom** [comment] 2020-11-08 21:13
Ah, OK, this is 100% my fault. `:tabopen` was completely broken in FF80 so I rushed out some code to fix it. At the time I didn't care that I had broken this minor feature. Given that it's taken this long for someone else to notice, I think I probably made the right call ;)

Closing as duplicate of #2700 - and I'll try to look at getting it fixed at some point.

**Closed by bovine3dom** 2020-11-08 21:13 UTC
Labels: P4, bug
