### ISSUE TITLE
Confused user

### ISSUE THREAD

**Issue by kasal** [tridactyl/tridactyl#1925] opened 2019-10-21 14:58 UTC
Tridactyl version: 1.17.0pre3239-6da1e02
Firefox version: Mozilla Firefox 69.0.3
Operating system: win

Hello,
sorry if this is not helpful enough, but I'm confused.  I have used vimperator and then pentadactyl and now I try to learn tridactyl.

I'd like to start configuring via .tridactylrc, but I cannot find out the right place for it (tried c:\Users\kasal\.tridactylrc, %HOME%\.tridactylrc and many variants, with "_", under .config/tridactyl, etc.)

I would appreciate some way to debug these issues.  I type ":source nothing" and get no error message.  Then I tried to type some garbage to a file under c:/Users/skasal/.tridactyl/ (created by native) and source it.  Nothing happened.

I also have problems with the auto completition switched on by default.  I'd like to have it under <Tab>, so that th screen is not moving so much just because I try to type a command.

Sorry for all the confusion; I'd be grateful for any hints.

(I write this issue as I was not able to find a support maillist and I wasn't able to join the irc room (no ssl).)

Thanks,  Stepan

**Comment by glacambre** [comment] 2019-10-21 20:12
`js tri.native.getrcpath().then(alert).catch(alert)` should tell you where tridactyl is looking for your rc file.

In order to see if your tridactylrc is correctly sourced or not, you can add `js alert()` at the very top. If the rc is sourced, you get a popup, if it isn't, you don't.

I'm not sure I understand what you mean about completions. Do you only want them to appear if you press a specific character (like in bash, for example)?

>Sorry for all the confusion; I'd be grateful for any hints.

Don't be sorry, we're volunteers, if we don't want to help, we don't :).

**Comment by kasal** [comment] 2019-10-22 07:39
> Do you only want them to appear if you press a specific character (like in bash, for example)?

Yes indeed.  I do not like to much movement on the screen as I type.  And the thing is worse when there is a delay, as I do not percept it as a reaction to my typing, so I tend to wary what happens, who is going to steal my focus.

About the customization:
Thanks for the advices!
The "js alert()" allowed me to verify that at least :source command works.
I'll learn basics of js eventually and try to read a fragment of tridactyl source.

About rc dir:
The msg window says "Error: getrcpath error: path not found"
My environment contains HOMEDRIVE=H: -- it is enough for my MSYS2 to set HOME=/h
But I also tried to run firefox.exe with variable HOME or XDG_CONFIG_DIR set and it did not help.
(Yeah, I have not tested all the combinations, like unset HOME and set XDG_CONFIG_DIR etc.)

Another confusion:
It seems that I sourced my .tridactylrc one.  The file contained redefinitions of fixamo and fixamo_quiet.
I'm surprised to see that these redefinitions are persistent: they survive firefox restart. Likewise, if I experiment with hintnames, the changed value survives restart of firefox. How comes? Where are these values saved? (This resembles smalltalk, where the whole "world" is persistent.)

Let me repeat that I'm grateful and will be grateful for your help.  (As I'm grateful for tridactyl itself.)

**Comment by kasal** [comment] 2019-10-22 12:37
I have found out several things; let me sum up for potential future readers:
- it's important to install native; before that, lot of things just don't work
- getrcpath() returns the pathname of the rc file; *if it exists* - no sense to experiment before touching the candidate pathnames.
- then things work as scribed in tridactyl/native/native_main.py - four places are checked:

      ${HOME}/{.,_}{config/tridactyl/,}tridactylrc

  (If XDG_CONFIG_HOME is set, it overrides HOME in the first of the alternatives.)
- env var HOMEDRIVE is ignored in firefox (unlike in Git for windows, for example, cf https://github.com/git/git/commit/e12a9556602f4d94254cc4eda25b5615ff07131a); in any case setting HOME is always sane
- The env var (HOME) has to be set in user profile. If you set it and then run firefox.exe, it is not enough. In that case, "! echo %HOME%" shows the right value, yet the variable is not accessible to the native messanger that is responsible for finding the rc file.

Remaining questions:
- could you give me some hint how could I get rid of the autocomplete? What place in the source? or could I achieve that by a crafted tridactylrc?
- could you explain me why the variables and function definitions seem to persist?

Thanks a lot for your help.

**Comment by notJerl** [comment] 2019-10-22 15:12
Variables and function definitions persist because they are not only stored in .tridactylrc, but also in your browser's local storage OR, by default, in Firefox Sync if it's set up.  A .tridactylrc is a useful way to make your configuration portable if you don't want to sync it, but I have a considerable amount of customization in my install and I don't even *have* a .tridactylrc.

**Comment by bovine3dom** [comment] 2019-10-22 21:53
> could you explain me why the variables and function definitions seem to persist?

If you add 

`sanitise tridactyllocal tridactylsync`

to the top of your RC file it will wipe the settings on launch, so it in effect stops settings from persisting.

As notJerl implies, it persists by design for the convenience of users who can't install the native messenger.

**Comment by bovine3dom** [comment] 2020-06-01 14:53
I think we've answered most of these questions. Closing :)

**Closed by bovine3dom** 2020-06-01 14:53 UTC
