### ISSUE TITLE
Clipboard yank is no longer working

### ISSUE THREAD

**Issue by enikar** [tridactyl/tridactyl#4429] opened 2022-10-20 08:44 UTC
Hi,
Since I update to tridactyl version 1.22.1pre6426-4ec0e5eb `clipboard yank` doesn't
work, while pasting an url with `P` works properly.

To reproduce, just type `yy` to yank the current page's url, that doesn't work with any site. 

OS: linux
Firefox version: 106.0
I have no tridactylrc.
Result of `:viewconfig --user` command:  https://gist.github.com/enikar/18630cbecb65364fd6c0e50523e7ff6b

Native messenger version: 0.3.6 (`:native` command says everything is OK)
OS: linux
Result of `:! echo $PATH`: https://gist.github.com/enikar/f267eaa6bf715538638b4d86d1e7c908
With native_main: https://gist.github.com/enikar/0a256bf8629f91b9cf45c67c35b097d6

Thanks for your awesome firefox extension. Without tridactyl firefox wil be boring :-)

**Comment by bovine3dom** [comment] 2022-10-20 11:51
I think this is a duplicate of #3616 - could you try updating to native 0.3.7 with `:updatenative` and checking again? `:updatenative` might tell you that 0.3.6 is installed but it should be installing 0.3.7 in the background, just check with `:native` again after a few minutes.

**Comment by enikar** [comment] 2022-10-20 16:18
Well, I try :updatenative. No error message are shown. I don't know if the command was trying to install something in background.
Anyway, the command `:native` responds `# Native messenger is correctly installed, version 0.3.6` after waiting few minutes.
Notice, I don't remember how I install this Native messaging.

**Comment by enikar** [comment] 2022-10-20 16:53
Well, I git clone https://github.com/tridactyl/native_messenger then I build it with nimble.
I install it at the proper place (under `~/.local/share/tridactyl`). Now clipboard yank is working again, nice!
And, hopefully `:native` responds ` # Native messenger is correctly installed, version 0.3.7`

**Comment by bovine3dom** [comment] 2022-10-20 21:40
I think we did have some problems with updatenative, maybe running `:installnative` again and running that command would have worked.

Closing as a duplicate of #3616 :)

**Closed by bovine3dom** 2022-10-20 21:40 UTC
