### ISSUE TITLE
Native messenger can't be detected

### ISSUE THREAD

**Issue by robertgzr** [tridactyl/tridactyl#544] opened 2018-05-16 15:46 UTC
- macOS 10.11.6
- Firefox 62.0a1 (2018-05-16)
- Tridactyl 1.12.0-27-ge4de65f

I run `:installnative`; paste the command into my terminal; it installs:
```
Successfully installed Tridactyl native messenger!
Run ':native' in Firefox to check.
```

When I check with `:native` I get:
```
# Native messenger not found. Please run `:installnative` and follow the instructions. 
```

Can I break the native messenger feature with `about:config` modifications?

**Comment by glacambre** [comment] 2018-05-16 15:51
>Can I break the native messenger feature with about:config modifications?

I don't think so. Could you try running `printf '3\0\0\0{"cmd": "run", "command": "printf hello Tridactyl"}' | $XDG_DATA_HOME/native_main.py` in a terminal and telling us what the output is?

**Comment by bovine3dom** [comment] 2018-05-16 17:34
I get the same output.

Could you try on a new Firefox profile? That's the easiest way of seeing whether it's something in about:config.

I suspect the problem lies in the tridactyl.json, though: is there a tridactyl.json in `$HOME/Library/Application Support/Mozilla/NativeMessagingHosts/`?

**Comment by OrcaXS** [comment] 2018-05-17 04:18
Same here, macOS 10.13.4 / Firefox 61.0b5 (64-bit) / Tridactyl 1.12.0-9-g82c4348

There is a `tridactyl.json` in my `~/Library/Application Support/Mozilla/NativeMessagingHosts/`.

I tried on a new Firefox profile and it didn't work either, just saying 
```
# Native messenger not found. Please run :installnative and follow the instructions.
```

**Comment by glacambre** [comment] 2018-05-17 05:29
Could you upload the content of tridactyl.json here? I wouldn't be surprised is something went wrong here since the code was changed about a week ago: https://github.com/cmcaine/tridactyl/blob/aed05c5e94129414bacf00f750afe266803d6a7f/native/install.sh#L50

**Comment by OrcaXS** [comment] 2018-05-17 06:35
Here it is:

```json
{
    "name": "tridactyl",
    "description": "Tridactyl native command handler",
    "path": "/Users/orcaxs/.local/share/tridactyl/native_main.py",
    "type": "stdio",
    "allowed_extensions": [ "tridactyl.vim@cmcaine.co.uk","tridactyl.vim.betas@cmcaine.co.uk" ]
}
```

**Comment by bovine3dom** [comment] 2018-05-17 09:17
That looks fine, @OrcaXS :S.

I can't reproduce this on Linux or OSX 10.12; Firefox 59, 60, 61; native messenger 0.1.1, 0.1.4, Tridactyl 1.12.0-35...

**Comment by bovine3dom** [comment] 2018-05-17 09:31
@OrcaXS, @robertgzr, could you do `set logging.native debug`, open the Browser Console under Web Developer in the Firefox hamburger menu, run `:native` and copy the output?

I get

```
Sending message: {"cmd":"version"}  background.js:1989:5
No such native application tridactyl  NativeMessaging.jsm:99
	NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:99:9
```

if I don't have the messenger installed, and 

```
Sending message: {"cmd":"version"}  background.js:1989:5
Received response: Object { version: "0.1.4" }  background.js:1992:9
Native version: 0.1.4  background.js:2020:9
```
if I do.

**Comment by OrcaXS** [comment] 2018-05-17 10:31
Got the following output:
```
Sending message: {"cmd":"version"}  background.js:1981:5
Failed to execute command "/Users/orcaxs/.local/share/tridactyl/native_main.py" NativeMessaging.jsm:99
NativeApp</this.startupPromise<
resource://gre/modules/NativeMessaging.jsm:99:9
```

**Comment by bovine3dom** [comment] 2018-05-17 10:52
Can you check to see if the file is marked executable or has other weird permissions on it, e.g. with `ls -l`?

**Comment by OrcaXS** [comment] 2018-05-17 11:35
That `native_main.py` is set to 755 and owned by myself.

**Comment by bovine3dom** [comment] 2018-05-17 11:56
I'm out of ideas, I'm afraid :(

**Comment by bovine3dom** [comment] 2018-05-17 12:28
The whole point of https://github.com/cmcaine/tridactyl/blob/9d2cc21b27d686f32330e337d1420b20284117c6/native/install.sh#L56 is that it ignores `env` because it's proper dodgy on OSX and bakes in the python location. I guess we've messed that up slightly.

**Comment by bovine3dom** [comment] 2018-05-17 12:33
Would someone who has a broken `native` mind just pasting the whole native_main.py here?

**Comment by sirn** [comment] 2018-05-17 12:47
My `native_main.py`:

```
#!/Users/sirn/.asdf/shims/python3
# -*- coding: utf-8 -*-

import sys
import os
import json
import re
import struct
import subprocess
import tempfile
import unicodedata

VERSION = "0.1.4"


class NoConnectionError(Exception):
    """ Exception thrown when stdin cannot be read """


def eprint(*args, **kwargs):
    """ Print to stderr, which gets echoed in the browser console when run
    by Firefox
    """
    print(*args, file=sys.stderr, flush=True, **kwargs)


def getenv(variable, default):
    """ Get an environment variable value, or use the default provided """
    return os.environ.get(variable) or default


def getMessage():
    """Read a message from stdin and decode it.

    "Each message is serialized using JSON, UTF-8 encoded and is preceded with
    a 32-bit value containing the message length in native byte order."

    https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging#App_side

    """
    rawLength = sys.stdin.buffer.read(4)
    if len(rawLength) == 0:
        sys.exit(0)
    messageLength = struct.unpack('@I', rawLength)[0]
    message = sys.stdin.buffer.read(messageLength).decode('utf-8')
    return json.loads(message)


# Encode a message for transmission,
# given its content.
def encodeMessage(messageContent):
    """ Encode a message for transmission, given its content."""
    encodedContent = json.dumps(messageContent).encode('utf-8')
    encodedLength = struct.pack('@I', len(encodedContent))
    return {'length': encodedLength, 'content': encodedContent}


# Send an encoded message to stdout
def sendMessage(encodedMessage):
    """ Send an encoded message to stdout."""
    sys.stdout.buffer.write(encodedMessage['length'])
    sys.stdout.buffer.write(encodedMessage['content'])
    try:
        sys.stdout.buffer.write(encodedMessage['code'])
    except KeyError:
        pass

    sys.stdout.buffer.flush()


def findUserConfigFile():
    """ Find a user config file, if it exists. Return the file path, or None
    if not found
    """
    home = os.path.expanduser('~')
    config_dir = getenv('XDG_CONFIG_HOME', os.path.expanduser('~/.config'))

    # Will search for files in this order
    candidate_files = [
        os.path.join(config_dir, "tridactyl", "tridactylrc"),
        os.path.join(home, '.tridactylrc')
    ]

    config_path = None

    # find the first path in the list that exists
    for path in candidate_files:
        if os.path.isfile(path):
            config_path = path
            break

    return config_path


def getUserConfig():
    # look it up freshly each time - the user could have moved or killed it
    cfg_file = findUserConfigFile()

    # no file, return
    if not cfg_file:
        return None

    # for now, this is a simple file read, but if the files can
    # include other files, that will need more work
    return open(cfg_file, 'r').read()


def sanitizeFilename(fn):
    """ Transform a string to make it suitable for use as a filename.

    From https://stackoverflow.com/a/295466/147356"""

    fn = unicodedata.normalize('NFKD', fn).encode(
        'ascii', 'ignore').decode('ascii')
    fn = re.sub('[^\w\s/.-]', '', fn).strip().lower()
    fn = re.sub('\.\.+', '', fn)
    fn = re.sub('[-/\s]+', '-', fn)
    return fn


def handleMessage(message):
    """ Generate reply from incoming message. """
    cmd = message["cmd"]
    reply = {'cmd': cmd}

    if cmd == 'version':
        reply = {'version': VERSION}

    elif cmd == 'getconfig':
        file_content = getUserConfig()
        if file_content:
            reply['content'] = file_content
        else:
            reply['code'] = 'File not found'

    elif cmd == 'run':
        commands = message["command"]

        try:
            p = subprocess.check_output(commands, shell=True)
            reply["content"] = p.decode("utf-8")
            reply["code"] = 0

        except subprocess.CalledProcessError as process:
            reply["code"] = process.returncode
            reply["content"] = process.output.decode("utf-8")

    elif cmd == 'eval':
        output = eval(message["command"])
        reply['content'] = output

    elif cmd == 'read':
        try:
            with open(os.path.expandvars(os.path.expanduser(message["file"])), "r") as file:
                reply['content'] = file.read()
                reply['code'] = 0
        except FileNotFoundError:
            reply['content'] = ""
            reply['code'] = 2

    elif cmd == 'mkdir':
        os.makedirs(
            os.path.relpath(message["dir"]), exist_ok=message["exist_ok"]
        )
        reply['content'] = ""
        reply['code'] = 0

    elif cmd == 'write':
        with open(message["file"], "w") as file:
            file.write(message["content"])

    elif cmd == 'temp':
        prefix = message.get('prefix')
        if prefix is not None:
            prefix = 'tmp_{}_'.format(sanitizeFilename(prefix))

        (handle, filepath) = tempfile.mkstemp(prefix=prefix)
        with os.fdopen(handle, "w") as file:
            file.write(message["content"])
        reply['content'] = filepath

    elif cmd == 'env':
        reply['content'] = getenv(message["var"], "")

    else:
        reply = {'cmd': 'error', 'error': 'Unhandled message'}
        eprint('Unhandled message: {}'.format(message))

    return reply


while True:
    message = getMessage()
    reply = handleMessage(message)
    sendMessage(encodeMessage(reply))
```

**Comment by sirn** [comment] 2018-05-17 12:49
@bovine3dom since you mentioned about `env`, I tried changing the shebang of `native_main.py` and prefix it with `/usr/bin/env` and native messaging is now working.

```
#!/usr/bin/env /Users/sirn/.asdf/shims/python3
```

**Comment by bovine3dom** [comment] 2018-05-17 12:55
@sirn would you run `installnative` again and see if it works? Thanks.

**Comment by sirn** [comment] 2018-05-17 12:57
@bovine3dom I could confirm it's now working. Thanks!

**Comment by bovine3dom** [comment] 2018-05-17 13:01
No, thank you, for figuring it out, and all who helped us debug it.

**Comment by bovine3dom** [comment] 2018-05-17 16:15
@robertgzr manually changing it might work for now, but if we ever get around to fixing #452, you'll need to change it every single time Tridactyl updates.

**Comment by robertgzr** [comment] 2018-05-17 16:17
@bovine3dom can I not just change `nativeinstallcmd` to my own gist?

**Comment by sirn** [comment] 2018-05-17 16:20
@robertgzr looks to me like you have multiple Python versions installed with pyenv; the pyenv shims only allowed executing currently active Python version, so I think running something like `pyenv global 3.6.5` (or if you have to use both 2/3, `pyenv global 2.7.14 3.6.5`) should fix it.

**Comment by sirn** [comment] 2018-05-17 16:35
@robertgzr I think it's a result of Firefox being run from launchd (and the `native_main.py` is being spawn by Firefox), which has different `PATH` than the shell (just `/usr/bin:/usr/sbin:/bin`), so pyenv couldn't found the one installed in `/usr/local/bin`.

AFAIK, pyenv uses `command -v` to detect where Python is installed, so basically it is trying to run the following command and couldn't found any binary:

```
$ env PATH=/usr/bin:/usr/sbin:/bin command -v python3
```

There's a way to hack around this (run on every boot), but I wouldn't recommend:

```
$ launchctl setenv PATH /usr/local/bin:/usr/bin:/usr/sbin:/bin
```

**Comment by notJerl** [comment] 2018-09-06 15:46
Experiencing the same thing, but got a completely different output in the dev console:

    Sending message: {"cmd":"version"} background.js:6754:5
    stderr output from native app tridactyl: Error loading Python DLL 'C:\Users\GEROSH~1\AppData\Local\Temp\_MEI46922\python35.dll'.
    stderr output from native app tridactyl: LoadLibrary: Invalid access to memory location.

**Comment by bovine3dom** [comment] 2018-09-06 16:00
Yeah, we have a different issue open for that I think. There's a PR open that will hopefully fix it by compiling the exe on Windows but we need to sort out some CI stuff.

**Comment by deftsp** [comment] 2019-02-01 14:56
I deleted `~/.python-version`, the probem gone.
```
stderr output from native app tridactyl: pyenv: python3: command not found
stderr output from native app tridactyl: 
stderr output from native app tridactyl: The `python3' command exists in these Python versions:
stderr output from native app tridactyl:   3.6.5
stderr output from native app tridactyl: 
```

**Comment by bovine3dom** [comment] 2021-05-01 15:27
Fixed with nim messenger, probably

**Closed by bovine3dom** 2021-05-01 15:27 UTC
Labels: help wanted, osx, workaround inside!

**Comment by rdrg109** [comment] 2023-12-14 05:42
@YodaEmbedding On Guix, the downloaded native_main doesn't work either. The file gets created and it can be read, but it can't be executed (please see output below)

```
$ wc -l ~/.local/share/tridactyl/native_main
903 /home/myusername/.local/share/tridactyl/native_main
$ du -b ~/.local/share/tridactyl/native_main
526352  /home/myusername/.local/share/tridactyl/native_main
$ file ~/.local/share/tridactyl/native_main
/home/myusername/.local/share/tridactyl/native_main: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4946e69160d097c03e6782e55569523649e20987, for GNU/Linux 3.2.0, not stripped
$ ~/.local/share/tridactyl/native_main
bash: /home/myusername/.local/share/tridactyl/native_main: No such file or directory
$ echo $?
127
```

This is the content of `~/.local/share/tridactyl/native_main` after executing `:nativeinstall`

```
~ $ find ~/.local/share/tridactyl/
/home/myusername/.local/share/tridactyl/
/home/myusername/.local/share/tridactyl/native_main
~ $ echo $?
0
~ $ 
```
