### ISSUE TITLE
Cant reset config & reinstalling doesn't help

### ISSUE THREAD

**Issue by leshow** [tridactyl/tridactyl#4670] opened 2023-04-13 21:41 UTC
-   Brief description of the problem:

I can't reset my tridactyl config, even using the "Reset tridactyl config" on the help page. uninstalling the extension and reinstalling doesn't help

I've been attempting to get my config working correctly, I used to use `keymap` but the behavior has changed, I basically just want to shift the home row functions from: hjkl; to jkl;' 
so that k/l go down/up K/L tabnext/tabprev etc and also ;; becomes ''

I used to do it this way
```
keymap @ :
keymap ' ;
keymap j h
keymap k j
keymap l k:
keymap ; l

keymap L J
keymap J H
keymap : L
```

-   Steps to reproduce:

run the above commands then try to reset the config, it appears the keymap remains the same. Uninstalling the beta extension and re-installing doesn't have any effect, I can't recover the original keymap

-   Tridactyl version (`:version`):
1.23.0pre6760-a5196759

-   Firefox version (Top right menu > Help > About Firefox):
112.0

-   URL of the website the bug happens on:
all

Is there some file that I should clear to reset the config? I don't have a `tridactylrc`.
Also, I see that keymap is deprecated, what is the best way to do the changes I want now? `keymap` is very error prone for me and seems to get in a state that is impossible to recover from sometimes

edit: I was able to get the config removed after re-installing it and restarting firefox several times, but the "reset tridactyl config" button never worked. I am still curious if someone knows of the proper way to adjust the keymap though, as it seems my old way no longer works properly.

**Comment by treapster** [comment] 2023-04-13 23:48
It's surprising that the old keymap was stuck and i have no idea why, but currently the proper way to remap characters is to do `set keyboardlayoutforce true` (which will probably become default someday) and then `set keyboardlayoutoverrides.[Code] [char][CharForUpperRegister]` to whatever you need using language-independent codes(see `help keyboardlayoutoverrides`). To move the home row on qwerty right, you need something like
```
set keyboardlayoutoverrides.KeyJ hH
set keyboardlayoutoverrides.KeyK jJ
set keyboardlayoutoverrides.KeyL kK
set keyboardlayoutoverrides.Semicolon lL
set keyboardlayoutoverrides.Quote ;:
```
If you're not using qwerty, look into `help keyboardlayoutbase` . And in that case KeyX may not correspond to what you you use to type x, so [this](https://gistpreview.github.io/?324119c773fac31651f6422087b36804) may help.
Not super convenient, but it will work with any layout once configured.
On the other hand, the old keymap should work fine as long as keyboardlayoutforce is disabled and usekeytranslatemap is enabled. What issues are you experiencing with keymap?

**Comment by treapster** [comment] 2023-04-13 23:58
Also there is another way - instead of configuring some weird layout, you can just use `bind` to rebind commands to non-default keys, e.g
```
bind J back
bind j scrollpx -50
bind k scrollline 10
bind K tabprev
```
and etc.

**Comment by leshow** [comment] 2023-04-15 15:10
> What issues are you experiencing with keymap?

previously, and I'm not sure which version this broke in exactly, but when I pressed `f` to go into hint mode and say there was a combination on the screen like `js` pressing `j` would in fact press `h` in the selection. I'm guessing because the remap was now active in the hint mode and not just "normal" mode. 


If I just use `bind` will that also work for combinations like `;` ? Like does `bind ' hint` so I can use `''`/`'y`/... instead of `;;`/`;y`?

**Comment by bovine3dom** [comment] 2023-04-15 15:36
Ah, yes, that was removed in #4439 - sorry.

I merged it telling myself I would add per-mode settings as discussed in #3635 which would allow you to disable keymaps/keyboardlayoutforce again in hint mode before it got into a stable release ... but I forgot.

You could downgrade Tridactyl to 1.22.1 to get the old behaviour back - https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/versions/ - you might need to disable autoupdates afterwards.

For now I'll close this as a duplicate of #3635 - you might want to follow that issue to find out when it is fixed.

**Closed** 2023-04-15 15:36 UTC
Labels: bug, P4

**Comment by bovine3dom** [comment] 2023-04-15 15:38
> If I just use bind will that also work for combinations like ; ? Like does bind ' hint so I can use ''/'y/... instead of ;;/;y?

No, sorry. You would need to rebind everything. You could do it with a script but you would need to make sure you didn't end up with an infinite loop.

**Comment by leshow** [comment] 2023-04-16 05:44
Thank you for looking into it and getting back to me. I'm just using the default config for now, but when it becomes possible to shift all the home row keys one to the right in normal mode I  will give it a shot again.
