### ISSUE TITLE
"t" opens 2 tabs instead of one

### ISSUE THREAD

**Issue by sajaysurya** [tridactyl/tridactyl#1330] opened 2019-02-06 16:26 UTC
*   Brief description of the problem: if I open a new tab using "t" (while I have gmail open in the current tab) it opens two tabs instead of one

*   Steps to reproduce:

    1.  open gmail in the current tab
    2.  press "t" and type "hello" and press enter
    3.  google search for "hello" is opened as expected
    4.  additionally, a newtab (the tridactyl overridden page) is also opened with the address bar activated. So, it is also difficult to close this page

*   Tridactyl version (`:version`): 1.14.6

*   Firefox version (Top right menu > Help > About Firefox): 65.0

*   URL of the website the bug happens on: gmail.com

*   Config (in a new tab, run `:viewconfig`, copy the url and paste it somewhere like gist.github.com): cd"https://gist.github.com/sajaysurya/883e5cedeede244ece30723fc0952858.js"

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist):

```
" Place this at $XDG_CONFIG_DIR/tridactyl/tridactylrc (that's
" ~/.config/tridactyl/tridactylrc to mere mortals) or ~/.tridactylrc and
" install the native messenger (:installnative in Tridactyl). Run :source to
" get it in the browser, or just restart.

" NB: If you want "vim-like" behaviour where removing a line from 
" here makes the setting disappear, uncomment the line below.

"sanitise tridactyllocal tridactylsync

"
" Binds
"
bind J tabprev
bind K tabnext

" 
" Custom Search Engines
"
set searchurls.ddg https://duckduckgo.com/?q=
set searchurls.azn https://www.amazon.co.uk/s/ref=nb_sb_noss?url=search-alias%3Daps&field-keywords=
set searchurls.dic https://www.vocabulary.com/dictionary/

"
" Misc settings
"
set searchengine google
set allowautofocus false
set theme dark

"
" Blacklists
"
blacklistadd localhost

" This will have to do until someone writes us a nice syntax file :)
" vim: set filetype=vim:

```

**Comment by bovine3dom** [comment] 2019-02-06 16:32
Duplicate of #1273. Thanks for reporting :)

**Closed by bovine3dom** 2019-02-06 16:32 UTC
