### ISSUE TITLE
Suggestion: add quick help windows

### ISSUE THREAD

**Issue by jimrs** [tridactyl/tridactyl#3503] opened 2021-03-21 18:06 UTC
Hi guys!

I'm coming from Vimium and there was a nice thing when you pressed ? it showed up a small windows with basic usage keybinds. It was helpful when learning all the new keybinds fast. Is there any function like that or could it be added please?

Thanks,
jim

**Comment by bovine3dom** [comment] 2021-03-21 19:08
it would be as easy as fixing issue #123

Closing as duplicate of that issue : )

The closest we have is `:tutor` and the list on the new tab page. Otherwise there's `:viewconfig nmaps` but there are far too many binds for it to be particularly useful.

**Closed by bovine3dom** 2021-03-21 19:08 UTC
