### ISSUE TITLE
findnext -1 throws `ArgError`

### ISSUE THREAD

**Issue by Henry78** [tridactyl/tridactyl#4642] opened 2023-03-23 21:21 UTC
-   Brief description of the problem: `findnext -1` throws an `ArgError`, `findnext 1` works

-   Steps to reproduce:

    1. `find abc`
    2. `find next 1` # works as expected 
    3. `find next -1` throws 
    ```
    controller in excmd:  ArgError: unknown or unexpected option: -1
      ArgError index.js:5
      arg2 index.js:132
      findnext .excmds_content.generated.ts:1308
      acceptExCmd controller.ts:28
      handler messaging.ts:50
      onMessage messaging.ts:217
    ```

-   Tridactyl version : 1.23.0

-   Firefox version: 111.0.1

-   URL of the website the bug happens on: Various/All

-   Config: https://gist.github.com/Henry78/5f966a7e6339d0319c4a27463380f107

-   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): they don't

-   Operating system: Arch

I __really__ hope I didn't miss anything, this feel weird.

**Comment by bovine3dom** [comment] 2023-03-23 22:52
Thanks for reporting this.

The bug is fixed in the betas and will be fixed in the next stable release of Tridactyl. I'm closing this issue as a duplicate of #4482

**Closed by bovine3dom** 2023-03-23 22:52 UTC

**Comment by bovine3dom** [comment] 2023-03-23 22:54
While you're waiting for the next stable release you can use `:findnext -? 1` instead :)
