### ISSUE TITLE
Native Messenger fails to install on M1 Macs

### ISSUE THREAD

**Issue by winterscar** [tridactyl/tridactyl#4528] opened 2023-01-07 15:49 UTC
-   Brief description of the problem:

The native messenger command copied to the clipboard fails to install an arm64 (Mac M1) compatible build of the native messenger.

-   Steps to reproduce:

    1. Buy M1 mac
    2. run `:nativeinstall`
    3. paste the resulting command into your shell
    4. run `:native` 

That command fails with the same error described here: https://github.com/tridactyl/tridactyl/issues/4298#issue-1292179947

(Really, that's the same issue, but it's closed so I'm opening a new one)

-   Tridactyl version (`:version`): 1.23.0

-   Operating system: MacOS Ventura

**Comment by bovine3dom** [comment] 2023-01-09 14:31
I have a PR open for this - https://github.com/tridactyl/native_messenger/pull/9

I don't think it would be much effort to get it working, I just need to remember to do it. Feel free to remind me every few weeks until I actually get around to it.

Closing as duplicate of https://github.com/tridactyl/native_messenger/issues/2 :)

**Closed by bovine3dom** 2023-01-09 14:31 UTC

**Comment by winterscar** [comment] 2023-01-09 14:36
Will do, thanks!
