### ISSUE TITLE
How to mark the location of a Web page

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [tridactyl/tridactyl#2491] opened 2020-06-16 06:05 UTC
Tridactyl version: 1.19.1pre3928-53d0d18
Firefox version: Mozilla Firefox 75.0
Operating system: win

It's like the Pentadactyl's 'm' hotkey，this is very useful when visiting a long page

**Comment by bovine3dom** [comment] 2020-06-16 09:25
We don't have this feature, yet. We'd like it though :)

I'm closing this issue as a duplicate of #604.

**Closed by bovine3dom** 2020-06-16 09:25 UTC
