### ISSUE TITLE
Run shell script after clicking on a magnet link

### ISSUE THREAD

**Issue by n0ibe** [tridactyl/tridactyl#2421] opened 2020-05-25 10:31 UTC
Tridactyl version: 1.19.0pre3821-f4fa5b8
Firefox version: Mozilla Firefox 76.0.1
Operating system: mac

I'm new to tridactyl so forgive me if this is a dumb question. I'd like to run a shell script every time I click on a magnet link (with the mouse or with the keyboard hints) to download a torrent, passing the url of that magnet link as a parameter.

Is it possible to do this with the native messanger?

**Comment by bovine3dom** [comment] 2020-05-25 11:15
It might be but you're probably better off doing it via Firefox: http://kb.mozillazine.org/Register_protocol

**Comment by n0ibe** [comment] 2020-05-25 13:23
That link is from 9.5 years ago.

**Comment by bovine3dom** [comment] 2020-05-25 14:08
It is, and the information is still valid.

1. In about:config: `network.protocol-handler.expose.magnet -> true` (this is more important for uncommon protocols - I think magnets are handled automatically).
2. Click a new magnet link. If you haven't set an application in the past, it will come up with a prompt asking you to choose an application. Pick your shell script. `$1` will be the URI.

If you have previously set an application, go to about:preferences, search for "applications", search for "magnet", and pick your shell script there.

**Comment by n0ibe** [comment] 2020-05-25 14:24
If I go to the "Applications" sections in my about:preferences and try to pick an application for magnet links, a file manager pops up but the shell scripts are "greyed out", i.e. I can't select them.

**Comment by bovine3dom** [comment] 2020-05-25 14:43
Are you using OSX by any chance? I'm not at my PC now but I think I did it exactly as you stated on Linux a couple of years ago.

A simple solution would be to make your own hint bind, similar to our one for opening things in mpv. See `:bind ;v` and `:get exaliases.mpvsafe`

**Comment by n0ibe** [comment] 2020-05-25 16:09
Yep, I'm on macOS. The bind method is the next best thing, but that doesn't work if I click it with the mouse.

**Comment by bovine3dom** [comment] 2020-05-25 16:24
A little bit of googling gets me this - https://superuser.com/questions/524722/osx-firefox-pass-arguments-to-magnet-protocol-handler - does that work for you?

**Comment by bovine3dom** [comment] 2020-05-25 16:27
Managing links of a certain protocol with Tridactyl would require https://github.com/tridactyl/tridactyl/issues/1885, so I'm closing this issue as a duplicate of that. I'm still happy to help you here though : )

**Closed by bovine3dom** 2020-05-25 16:27 UTC

**Comment by n0ibe** [comment] 2020-05-29 18:16
> I don't use OSX, but a little bit of googling gets me this - https://superuser.com/questions/524722/osx-firefox-pass-arguments-to-magnet-protocol-handler - does that work for you?

I'm having the same problems that OP describes. I created a test application with the code `echo "$@" >> ~/test`. After clicking on a magnet link, the file `test` is created, so the app is executed, but it's empty, so no arguments are passed from firefox to the app.

**Comment by bovine3dom** [comment] 2020-05-29 18:55
At this point I am just googling for you, but have you tried https://support.shotgunsoftware.com/hc/en-us/articles/219031308-Launching-applications-using-custom-browser-protocols?mobile_site=true#osx ? Swapping "shotgun" for "magnet".
