### ISSUE TITLE
Tridactyl cannot read profiles.ini

### ISSUE THREAD

**Issue by syslino** [tridactyl/tridactyl#1515] opened 2019-05-03 09:58 UTC
Tridactyl version: 1.14.9-180-g542b5b0
Firefox version: Mozilla Firefox 66.0.3
Operating system: Arch linux, fully updated
Native: Native messenger is correctly installed, version 0.1.10

Hi, I have a problem with your wonderful plugin.
I just switched back to Firefox (after 10 years) and installed the latest "beta" build. No config, just messing around with all this new suff. So when I tried to ``guiset tabs none`` (or any other parameters) I get the following message:

`` controller in excmd:  Error: You found a bug! Tridactyl should have been able to match the profile you're using with the profiles found in "/home/lino/.mozilla/firefox/profiles.ini" but it couldn't. Please report this issue on https://github.com/tridactyl/tridactyl/issues .``

So here I am, doing as I was told. Any tips or hints - or additional data I could provide - to resolve this?

Thanks for your work on this plugin, I like it.

**Comment by glacambre** [comment] 2019-05-03 10:07
Hi, thanks for reporting this issue. Could you give us the command line used to start firefox (`cat "/proc/$(pidof firefox)/cmdline"`), the content of `/home/lino/.mozilla/firefox/profiles.ini` and a list of all directories in `/home/lino/.mozilla/firefox`?

**Comment by syslino** [comment] 2019-05-03 10:49
[Sure!](https://bin.doyle.la/olubbraptu), if there's something else I can do I'd be happy!

**Comment by glacambre** [comment] 2019-05-06 11:03
This is weird, I don't see how things could go wrong here. Could you try to take a look at what's happening in a debugger? This would require you to go through the following steps:

- open the developer console (`<CS-i>`)
- navigate to the debugger tab
- in the leftmost column, find a file named `content.js` which belongs to Tridactyl
- Select it and then use `<C-f>` to search for the string `You found a bug`
- Click on the line number on the left in order to place a breakpoint
- Trigger the bug by running `:js tri.native.getProfile()` in Tridactyl's command line

I would like to know what the `iniObject` and `profilecmd` variables looks like. You can find that out by either hovering your mouse over the name of these variables or by looking at the stack frames in the rightmost column.

**Comment by glacambre** [comment] 2019-05-06 16:30
I think I found what the problem is and opened https://github.com/tridactyl/tridactyl/pull/1529 to fix it.

**Comment by glacambre** [comment] 2019-05-08 06:55
Closing this. Let me know if you're still experiencing this bug with 1.14.10-207-g93df468 or greater.

**Closed by glacambre** 2019-05-08 06:55 UTC
