### ISSUE TITLE
Excmd for going to audio playing tab

### ISSUE THREAD

**Issue by aduros** [tridactyl/tridactyl#3183] opened 2021-01-05 15:13 UTC
It would be useful to have an excmd+keybind for going to the tab currently playing audio. Would you guys accept a PR for this? I'd be happy to take a crack at it.

Thanks for tridactyl! It's the main reason I switched back to Firefox :)

**Comment by bovine3dom** [comment] 2021-01-05 15:42
Potentially a duplicate of #2811 - I'd love a PR that did that : )

Then your use case becomes e.g.

```
:set completions.Tab.audiomarker *
:bind ,n buffer *
```

If you don't like that idea I'd be happy to merge a PR that added a dedicated ex-command.

**Comment by aduros** [comment] 2021-01-05 16:02
Hmm, in that approach wouldn't it also match tabs with * in the title?

I think I'll start with a tabaudio excmd and if things go well, maybe implement #2811 after :) Would it be possible to include a default binding of "ga"?

**Closed** 2021-01-07 06:25 UTC
