### ISSUE TITLE
New tab race condition: loses URL bar input

### ISSUE THREAD

**Issue by braham-snyder** [tridactyl/tridactyl#3200] opened 2021-01-09 02:33 UTC
Tridactyl version: 1.20.4
Firefox version: Mozilla Firefox 84.0.1
Operating system: mac

*   Brief description of the problem: If I open a new tab, then immediately type into the URL bar, my inputs in the URL bar often disappear due to a race condition. The issue gets worse the more tabs I have open, but even at 350 tabs I often lose at least the first character of my input to the URL bar.

*   Steps to reproduce:

    1. If you don't already have many open tabs, open lots of tabs to make the issue apparent. 300 tridactyl homepage tabs would surely suffice on my 2015 macbook pro. I think `about:blank` tabs either do not cause the issue or are less problematic.
    2. Open another new tab with cmd-t
    3. Immediately input eg "j" to the URL bar
    4. See that the "j" disappears from the URL bar after a brief moment

*   `:viewconfig` output: https://gist.github.com/braham-snyder/cab089e381d5cc46e7d63a5e8aacf2a4

*   Contents of ~/.tridactylrc or ~/.config/tridactyl/tridactylrc (if they exist): 

```
" vim: set filetype=vim:
" General Settings
js tri.config.set("update", {"checkintervalsecs": 86400})
js tri.config.set("update", {"lastchecktime": 1570927457386})
js tri.config.set("update", {"lastnaggedversion": "1.17.0"})
js tri.config.set("update", {"nag": true})
js tri.config.set("update", {"nagwait": 7})
set configversion 1.7
set theme dark
set editorcmd auto
set profiledir /Users/bs/Library/Application Support/Firefox/Profiles/rs72cx9t.default-1509214190490/
set allowautofocus false
set smoothscroll true
set jumpdelay 300
set modeindicatorshowkeys true
" Q looks too much like O with dim display / f.lux, so get rid of it
set hintchars hjklasdfgyuiopwertnmzxcvb

" Binds
bind q tabclose
unbind f
bind fl hint
bind fk hint -b
bind fK hint -k
bind fw hint -w
bind fp hint -wp
bind f; hint -;
bind fs hint -s
bind fS hint -S
bind fa hint -a
bind fA hint -A
bind f# hint -#
bind fy composite hint -pipe * textContent | yank
bind fY hint -y
bind J tabnext
bind K tabprev
bind <S-Escape> mode ignore
unbind d
bind Q composite tabprev; tabclose #
bind P clipboard open
bind p clipboard tabopen
unbind <C-j>
bind <C-k> tabmove -1
bind fm hint -br
bind gw tabdetach
bind <AC-`> mode ignore
unbind <AC-~>
bind <A-p> pin
bind <A-m> mute toggle
bind <F1> help
bind o fillcmdline open
bind O current_url open
bind w fillcmdline winopen
bind W current_url winopen
bind t fillcmdline tabopen
bind ]] followpage next
bind [[ followpage prev
bind [c urlincrement -1
bind ]c urlincrement 1
bind <C-x> urlincrement -1
bind <C-a> urlincrement 1
bind T current_url tabopen
bind yy clipboard yank
bind ys clipboard yankshort
bind yc clipboard yankcanon
bind ym clipboard yankmd
bind yt clipboard yanktitle
bind gh home
bind gH home true
bind j scrollline 1.5
bind <C-e> scrollline 1.5
bind k scrollline -1.5
bind <C-y> scrollline -1.5
bind h scrollpx -50
bind l scrollpx 50
bind G scrollto 100
bind gg scrollto 0
bind <C-u> scrollpage -0.5
bind <C-d> scrollpage 0.5
bind <C-b> scrollpage -1
bind $ scrollto 100 x
bind ^ scrollto 0 x
bind <C-6> tab #
bind <C-^> tab #
bind H back
bind L forward
bind <C-o> jumpprev
bind <C-i> jumpnext
bind gx0 tabclosealltoleft
bind gx$ tabclosealltoright
bind << tabmove -1
bind >> tabmove +1
bind u undo
bind U undo window
bind r reload
bind R reloadhard
bind x stop
bind gi focusinput -l
bind g; changelistjump -1
bind gt tabnext_gt
bind gT tabprev
bind g^ tabfirst
bind g0 tabfirst
bind g$ tablast
bind gr reader
bind gu urlparent
bind gU urlroot
bind gf viewsource
bind : fillcmdline_notrail
bind s fillcmdline open search
bind S fillcmdline tabopen search
bind M gobble 1 quickmark
bind B fillcmdline taball
bind b fillcmdline tab
bind ZZ qall
bind F hint -b
bind gF hint -br
bind ;i hint -i
bind ;b hint -b
bind ;o hint
bind ;I hint -I
bind ;k hint -k
bind ;y hint -y
bind ;p composite hint -pipe * textContent | yank
bind ;P hint -P
bind ;r hint -r
bind ;s hint -s
bind ;S hint -S
bind ;a hint -a
bind ;A hint -A
bind ;; hint -;
bind ;# hint -#
bind ;v hint -W exclaim_quiet mpv
bind ;w hint -w
bind ;O hint -W fillcmdline_notrail open
bind ;W hint -W fillcmdline_notrail winopen
bind ;T hint -W fillcmdline_notrail tabopen
bind ;gi hint -qi
bind ;gI hint -qI
bind ;gk hint -qk
bind ;gy hint -qy
bind ;gp hint -qp
bind ;gP hint -qP
bind ;gr hint -qr
bind ;gs hint -qs
bind ;gS hint -qS
bind ;ga hint -qa
bind ;gA hint -qA
bind ;g; hint -q;
bind ;g# hint -q#
bind ;gv hint -qW exclaim_quiet mpv
bind ;gw hint -qw
bind ;gb hint -qb
bind <S-Insert> mode ignore
bind <AC-Escape> mode ignore
bind <Escape> composite mode normal ; hidecmdline
bind <C-[> composite mode normal ; hidecmdline
bind a current_url bmark
bind A bmark
bind zi zoom 0.1 true
bind zo zoom -0.1 true
bind zm zoom 0.5 true
bind zr zoom -0.5 true
bind zM zoom 0.5 true
bind zR zoom -0.5 true
bind zz zoom 1
bind zI zoom 3
bind zO zoom 0.3
bind . repeat
bind <AS-ArrowUp><AS-ArrowUp><AS-ArrowDown><AS-ArrowDown><AS-ArrowLeft><AS-ArrowRight><AS-ArrowLeft><AS-ArrowRight>ba open https://www.youtube.com/watch?v=M3iOROuTuMA
bind <C-?> viewconfig nmaps
bind fj hint -t
bind fz hint -z
bind <C-f> scrollpage 1
bind ;t hint -W tabopen
bind ;z hint -z
bind ;m composite hint -pipe img src | js -p tri.excmds.open('images.google.com/searchbyimage?image_url=' + JS_ARG)
bind ;M composite hint -pipe img src | jsb -p tri.excmds.tabopen('images.google.com/searchbyimage?image_url=' + JS_ARG)
bind D composite tabprev; tabclosealltoright
bind d$ composite tabprev; tabclosealltoright
bind d0 tabclosealltoleft
bind g? rot13
bind <CA-Escape> mode ignore
bind <CA-`> mode ignore
bind <SA-ArrowUp><SA-ArrowUp><SA-ArrowDown><SA-ArrowDown><SA-ArrowLeft><SA-ArrowRight><SA-ArrowLeft><SA-ArrowRight>ba open https://www.youtube.com/watch?v=M3iOROuTuMA
unbind --mode=ignore I
bind --mode=ignore <S-Insert> mode normal
bind --mode=ignore <AC-Escape> mode normal
bind --mode=ignore <AC-`> mode normal
bind --mode=ignore <S-Escape> mode normal
bind --mode=ignore <C-^> tab #
bind --mode=ignore <C-6> tab #
bind --mode=ignore <CA-Escape> mode normal
bind --mode=ignore <CA-`> mode normal

" Autocmds
autocmd DocLoad ^https://github.com/tridactyl/tridactyl/issues/new$ issue
autocmd TriStart .* source_quiet

blacklistadd https://.*.gather.town/app/.*
blacklistadd https://photos.google.com.*
blacklistadd localhost:.*/edit\?id.*

seturl localhost:.*/edit\?id.* allowautofocus true
seturl mail.google.com allowautofocus true
seturl www.overleaf.com allowautofocus true
seturl https://app.codesignal.com/.* allowautofocus true
seturl https://colab.research.google.com/.* allowautofocus true
```

<details>
<summary>
Click for more details on the influence of the number of tabs
</summary>

* It's difficult to reproduce when I keep my original 350 tabs open but open a separate profile with only 10 tridactyl homepage tabs
* Opening 70 tabs in the new profile makes the race condition obvious again on that new profile, on my machine (again, this is while I still have my 350 original tabs open as well)
* When I changed those 70 open tabs to `about:blank` tabs instead of tridactyl homepage tabs, the race condition was hard to reproduce

</details>

**Comment by bovine3dom** [comment] 2021-01-09 08:31
Thanks for the detailed issue!

I think this is a duplicate of #2840. Unfortunately I don't think there's anything we can fix - it's a Firefox bug. You can downgrade to Firefox ESR, use `t` rather than cmd-t, or use the no-new-tab builds mentioned in that issue.

**Closed by bovine3dom** 2021-01-09 08:31 UTC
